"""Generate web/tables.js from the decompiled scripts: the order screen's 48 order definitions
(sprite 490) and every (sprite, frame) that just stops its own timeline.

uv run --project ../../flash/tools python gen_tables.py
"""
import re, glob, json
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
CODE = ROOT / 'decompiled' / 'code'

stops = {}
for f in CODE.glob('sprite*.txt'):
    sid = re.search(r'sprite(\d+)', f.name).group(1)
    for m in re.finditer(r'## sprite\d+ frame (\d+) DoAction\n((?:(?!\n## ).)*)', f.read_text(), re.S):
        lines = [l for l in m.group(2).strip().split('\n') if l.strip()]
        if lines and lines[0].strip() == 'stop()':
            stops.setdefault(int(sid), []).append(int(m.group(1)))

orders = []
txt = (CODE / 'sprite490.txt').read_text()
for m in re.finditer(r'## sprite490 frame (\d+) DoAction\n((?:(?!\n## ).)*)', txt, re.S):
    body = m.group(2)
    texts = {t: e.replace("_root.LocaleText.getText", 'T') for t, e in re.findall(r"^(pizza|topping\d)\.text = (.*);$", body, re.M)}
    req = {k: (v == 'true' if v in ('true', 'false') else int(v)) for k, v in re.findall(r"_parent\.(\w+) = (\w+);", body)}
    orders.append({'frame': int(m.group(1)), 'texts': texts, 'req': req})

out = ['// Generated by tools/gen_tables.py from decompiled/code — do not edit.',
       '// STOPS: sprite id -> frames whose script is just stop().',
       'export const STOPS = ' + json.dumps({str(k): sorted(v) for k, v in sorted(stops.items())}) + ';',
       '// ORDERS: the order screen (sprite 490) frame by frame; T() looks up a locale string.',
       'export const ORDERS = (T) => [']
for o in orders:
    texts = ', '.join(f'{k}: {v}' for k, v in o['texts'].items())
    out.append(f"  {{ frame: {o['frame']}, texts: {{ {texts} }}, req: {json.dumps(o['req'])} }},")
out.append('];')
(ROOT / 'web' / 'tables.js').write_text('\n'.join(out) + '\n')
print('orders', len(orders), 'sprites with stops', len(stops))
