property FX_RAVEN_BOOM_01, FX_RAVEN_BOOM_02, FX_RAVEN_BOOM_03, FX_RAVEN_BOOM_04, FX_RAVEN_BOOM_05, FX_RAVEN_BOOM_06, FX_RAVEN_BOOM_07, FX_RAVEN_BOOM_08, FX_RAVEN_BOOM_09, FX_RAVEN_BOOM_10, FX_RAVEN_BOOM_11, FX_RAVEN_BOOM_12, FX_RAVEN_FALLING_OBJECTS_01A, FX_RAVEN_OBJ_COG_01A, FX_RAVEN_OBJ_CONCRETE_SM_01A, FX_RAVEN_OBJ_ENGINE_01A, FX_RAVEN_OBJ_IBEAM_SM_01A, FX_RAVEN_OBJ_TIRE_01A, FX_RAVEN_SPINNING_OBJECTS_01A, RAVEN_CHOP_01, RAVEN_CHOP_01D, RAVEN_CHOP_02, RAVEN_CHOP_02A, RAVEN_CHOP_02D, RAVEN_CHOP_03, RAVEN_CHOP_03D, RAVEN_DUCK_01, RAVEN_DUCK_01D, RAVEN_HIT_01, RAVEN_HIT_01D, RAVEN_HIT_02, RAVEN_HIT_02D, RAVEN_HIT_03, RAVEN_HIT_03D, RAVEN_HIT_04, RAVEN_HIT_04D, RAVEN_JUMP_01, RAVEN_JUMP_01D, RAVEN_JUMP_02, RAVEN_JUMP_02D, RAVEN_JUMP_03, RAVEN_JUMP_03D, RAVEN_JUMP_04, RAVEN_JUMP_04D, RAVEN_KICK_01, RAVEN_KICK_01D, RAVEN_KICK_02, RAVEN_KICK_02A, RAVEN_KICK_02D, RAVEN_KICK_03, RAVEN_KICK_03D, RAVEN_KICK_04, RAVEN_KICK_04D, RAVEN_SPECIAL_01, RAVEN_SPECIAL_01D, RAVEN_SPECIAL_02, RAVEN_SPECIAL_02D, RAVEN_SPECIAL_03D, RAVEN_SPECIAL_04D, RAVEN_SPECIAL_05D, RAVEN_SPECIAL_06D, RAVEN_SPECIAL_07D, RAVEN_STAND_01, RAVEN_STAND_01D, RAVEN_THROW_01, RAVEN_THROW_01D, RAVEN_THROW_02, RAVEN_THROW_02D, RAVEN_WALK_01, RAVEN_WALK_02, RAVEN_WALK_03, RAVEN_WALK_04, RAVEN_WALK_05, RAVEN_WALK_06, RAVEN_WALK_07, RAVEN_WALK_08, SFX_RAVEN_FLOATDOWN, SFX_RAVEN_FLOATHORIZONTAL, SFX_RAVEN_FLOATUP, SFX_RAVEN_LEVITATEDOBJECTSHIT, SFX_RAVEN_LEVITATEDOBJECTSMISS, SFX_RAVEN_LEVITATEOBJECT

on new me
  me.locateMembers()
  return me
end

on locateMembers me
  util = new(script("Class_Utility"))
  ASSET_CAST = "char_Raven"
  FX_RAVEN_BOOM_01 = util.findMember("fx_raven_boom_01", ASSET_CAST)
  FX_RAVEN_BOOM_02 = util.findMember("fx_raven_boom_02", ASSET_CAST)
  FX_RAVEN_BOOM_03 = util.findMember("fx_raven_boom_03", ASSET_CAST)
  FX_RAVEN_BOOM_04 = util.findMember("fx_raven_boom_04", ASSET_CAST)
  FX_RAVEN_BOOM_05 = util.findMember("fx_raven_boom_05", ASSET_CAST)
  FX_RAVEN_BOOM_06 = util.findMember("fx_raven_boom_06", ASSET_CAST)
  FX_RAVEN_BOOM_07 = util.findMember("fx_raven_boom_07", ASSET_CAST)
  FX_RAVEN_BOOM_08 = util.findMember("fx_raven_boom_08", ASSET_CAST)
  FX_RAVEN_BOOM_09 = util.findMember("fx_raven_boom_09", ASSET_CAST)
  FX_RAVEN_BOOM_10 = util.findMember("fx_raven_boom_10", ASSET_CAST)
  FX_RAVEN_BOOM_11 = util.findMember("fx_raven_boom_11", ASSET_CAST)
  FX_RAVEN_BOOM_12 = util.findMember("fx_raven_boom_12", ASSET_CAST)
  FX_RAVEN_FALLING_OBJECTS_01A = util.findMember("fx_raven_falling_objects_01a", ASSET_CAST)
  FX_RAVEN_OBJ_COG_01A = util.findMember("fx_raven_obj_cog_01a", ASSET_CAST)
  FX_RAVEN_OBJ_CONCRETE_SM_01A = util.findMember("fx_raven_obj_concrete_sm_01a", ASSET_CAST)
  FX_RAVEN_OBJ_ENGINE_01A = util.findMember("fx_raven_obj_engine_01a", ASSET_CAST)
  FX_RAVEN_OBJ_IBEAM_SM_01A = util.findMember("fx_raven_obj_ibeam_sm_01a", ASSET_CAST)
  FX_RAVEN_OBJ_TIRE_01A = util.findMember("fx_raven_obj_tire_01a", ASSET_CAST)
  FX_RAVEN_SPINNING_OBJECTS_01A = util.findMember("fx_raven_spinning_objects_01a", ASSET_CAST)
  RAVEN_CHOP_01 = util.findMember("raven_chop_01", ASSET_CAST)
  RAVEN_CHOP_01D = util.findMember("raven_chop_01d", ASSET_CAST)
  RAVEN_CHOP_02 = util.findMember("raven_chop_02", ASSET_CAST)
  RAVEN_CHOP_02A = util.findMember("raven_chop_02a", ASSET_CAST)
  RAVEN_CHOP_02D = util.findMember("raven_chop_02d", ASSET_CAST)
  RAVEN_CHOP_03 = util.findMember("raven_chop_03", ASSET_CAST)
  RAVEN_CHOP_03D = util.findMember("raven_chop_03d", ASSET_CAST)
  RAVEN_DUCK_01 = util.findMember("raven_duck_01", ASSET_CAST)
  RAVEN_DUCK_01D = util.findMember("raven_duck_01d", ASSET_CAST)
  RAVEN_HIT_01 = util.findMember("raven_hit_01", ASSET_CAST)
  RAVEN_HIT_01D = util.findMember("raven_hit_01d", ASSET_CAST)
  RAVEN_HIT_02 = util.findMember("raven_hit_02", ASSET_CAST)
  RAVEN_HIT_02D = util.findMember("raven_hit_02d", ASSET_CAST)
  RAVEN_HIT_03 = util.findMember("raven_hit_03", ASSET_CAST)
  RAVEN_HIT_03D = util.findMember("raven_hit_03d", ASSET_CAST)
  RAVEN_HIT_04 = util.findMember("raven_hit_04", ASSET_CAST)
  RAVEN_HIT_04D = util.findMember("raven_hit_04d", ASSET_CAST)
  RAVEN_JUMP_01 = util.findMember("raven_jump_01", ASSET_CAST)
  RAVEN_JUMP_01D = util.findMember("raven_jump_01d", ASSET_CAST)
  RAVEN_JUMP_02 = util.findMember("raven_jump_02", ASSET_CAST)
  RAVEN_JUMP_02D = util.findMember("raven_jump_02d", ASSET_CAST)
  RAVEN_JUMP_03 = util.findMember("raven_jump_03", ASSET_CAST)
  RAVEN_JUMP_03D = util.findMember("raven_jump_03d", ASSET_CAST)
  RAVEN_JUMP_04 = util.findMember("raven_jump_04", ASSET_CAST)
  RAVEN_JUMP_04D = util.findMember("raven_jump_04d", ASSET_CAST)
  RAVEN_KICK_01 = util.findMember("raven_kick_01", ASSET_CAST)
  RAVEN_KICK_01D = util.findMember("raven_kick_01d", ASSET_CAST)
  RAVEN_KICK_02 = util.findMember("raven_kick_02", ASSET_CAST)
  RAVEN_KICK_02A = util.findMember("raven_kick_02a", ASSET_CAST)
  RAVEN_KICK_02D = util.findMember("raven_kick_02d", ASSET_CAST)
  RAVEN_KICK_03 = util.findMember("raven_kick_03", ASSET_CAST)
  RAVEN_KICK_03D = util.findMember("raven_kick_03d", ASSET_CAST)
  RAVEN_KICK_04 = util.findMember("raven_kick_04", ASSET_CAST)
  RAVEN_KICK_04D = util.findMember("raven_kick_04d", ASSET_CAST)
  RAVEN_SPECIAL_01 = util.findMember("raven_special_01", ASSET_CAST)
  RAVEN_SPECIAL_01D = util.findMember("raven_special_01d", ASSET_CAST)
  RAVEN_SPECIAL_02 = util.findMember("raven_special_02", ASSET_CAST)
  RAVEN_SPECIAL_02D = util.findMember("raven_special_02d", ASSET_CAST)
  RAVEN_SPECIAL_03D = util.findMember("raven_special_03d", ASSET_CAST)
  RAVEN_SPECIAL_04D = util.findMember("raven_special_04d", ASSET_CAST)
  RAVEN_SPECIAL_05D = util.findMember("raven_special_05d", ASSET_CAST)
  RAVEN_SPECIAL_06D = util.findMember("raven_special_06d", ASSET_CAST)
  RAVEN_SPECIAL_07D = util.findMember("raven_special_07d", ASSET_CAST)
  RAVEN_STAND_01 = util.findMember("raven_stand_01", ASSET_CAST)
  RAVEN_STAND_01D = util.findMember("raven_stand_01d", ASSET_CAST)
  RAVEN_THROW_01 = util.findMember("raven_throw_01", ASSET_CAST)
  RAVEN_THROW_01D = util.findMember("raven_throw_01d", ASSET_CAST)
  RAVEN_THROW_02 = util.findMember("raven_throw_02", ASSET_CAST)
  RAVEN_THROW_02D = util.findMember("raven_throw_02d", ASSET_CAST)
  RAVEN_WALK_01 = util.findMember("raven_walk_01", ASSET_CAST)
  RAVEN_WALK_02 = util.findMember("raven_walk_02", ASSET_CAST)
  RAVEN_WALK_03 = util.findMember("raven_walk_03", ASSET_CAST)
  RAVEN_WALK_04 = util.findMember("raven_walk_04", ASSET_CAST)
  RAVEN_WALK_05 = util.findMember("raven_walk_05", ASSET_CAST)
  RAVEN_WALK_06 = util.findMember("raven_walk_06", ASSET_CAST)
  RAVEN_WALK_07 = util.findMember("raven_walk_07", ASSET_CAST)
  RAVEN_WALK_08 = util.findMember("raven_walk_08", ASSET_CAST)
  SFX_RAVEN_FLOATDOWN = util.findMember("sfx_raven_floatdown", ASSET_CAST)
  SFX_RAVEN_FLOATHORIZONTAL = util.findMember("sfx_raven_floathorizontal", ASSET_CAST)
  SFX_RAVEN_FLOATUP = util.findMember("sfx_raven_floatup", ASSET_CAST)
  SFX_RAVEN_LEVITATEDOBJECTSHIT = util.findMember("sfx_raven_levitatedobjectshit", ASSET_CAST)
  SFX_RAVEN_LEVITATEDOBJECTSMISS = util.findMember("sfx_raven_levitatedobjectsmiss", ASSET_CAST)
  SFX_RAVEN_LEVITATEOBJECT = util.findMember("sfx_raven_levitateobject", ASSET_CAST)
end

on precache me
  preloadMember(FX_RAVEN_BOOM_01)
  preloadMember(FX_RAVEN_BOOM_02)
  preloadMember(FX_RAVEN_BOOM_03)
  preloadMember(FX_RAVEN_BOOM_04)
  preloadMember(FX_RAVEN_BOOM_05)
  preloadMember(FX_RAVEN_BOOM_06)
  preloadMember(FX_RAVEN_BOOM_07)
  preloadMember(FX_RAVEN_BOOM_08)
  preloadMember(FX_RAVEN_BOOM_09)
  preloadMember(FX_RAVEN_BOOM_10)
  preloadMember(FX_RAVEN_BOOM_11)
  preloadMember(FX_RAVEN_BOOM_12)
  preloadMember(FX_RAVEN_FALLING_OBJECTS_01A)
  preloadMember(FX_RAVEN_OBJ_COG_01A)
  preloadMember(FX_RAVEN_OBJ_CONCRETE_SM_01A)
  preloadMember(FX_RAVEN_OBJ_ENGINE_01A)
  preloadMember(FX_RAVEN_OBJ_IBEAM_SM_01A)
  preloadMember(FX_RAVEN_OBJ_TIRE_01A)
  preloadMember(FX_RAVEN_SPINNING_OBJECTS_01A)
  preloadMember(RAVEN_CHOP_01)
  preloadMember(RAVEN_CHOP_01D)
  preloadMember(RAVEN_CHOP_02)
  preloadMember(RAVEN_CHOP_02A)
  preloadMember(RAVEN_CHOP_02D)
  preloadMember(RAVEN_CHOP_03)
  preloadMember(RAVEN_CHOP_03D)
  preloadMember(RAVEN_DUCK_01)
  preloadMember(RAVEN_DUCK_01D)
  preloadMember(RAVEN_HIT_01)
  preloadMember(RAVEN_HIT_01D)
  preloadMember(RAVEN_HIT_02)
  preloadMember(RAVEN_HIT_02D)
  preloadMember(RAVEN_HIT_03)
  preloadMember(RAVEN_HIT_03D)
  preloadMember(RAVEN_HIT_04)
  preloadMember(RAVEN_HIT_04D)
  preloadMember(RAVEN_JUMP_01)
  preloadMember(RAVEN_JUMP_01D)
  preloadMember(RAVEN_JUMP_02)
  preloadMember(RAVEN_JUMP_02D)
  preloadMember(RAVEN_JUMP_03)
  preloadMember(RAVEN_JUMP_03D)
  preloadMember(RAVEN_JUMP_04)
  preloadMember(RAVEN_JUMP_04D)
  preloadMember(RAVEN_KICK_01)
  preloadMember(RAVEN_KICK_01D)
  preloadMember(RAVEN_KICK_02)
  preloadMember(RAVEN_KICK_02A)
  preloadMember(RAVEN_KICK_02D)
  preloadMember(RAVEN_KICK_03)
  preloadMember(RAVEN_KICK_03D)
  preloadMember(RAVEN_KICK_04)
  preloadMember(RAVEN_KICK_04D)
  preloadMember(RAVEN_SPECIAL_01)
  preloadMember(RAVEN_SPECIAL_01D)
  preloadMember(RAVEN_SPECIAL_02)
  preloadMember(RAVEN_SPECIAL_02D)
  preloadMember(RAVEN_SPECIAL_03D)
  preloadMember(RAVEN_SPECIAL_04D)
  preloadMember(RAVEN_SPECIAL_05D)
  preloadMember(RAVEN_SPECIAL_06D)
  preloadMember(RAVEN_SPECIAL_07D)
  preloadMember(RAVEN_STAND_01)
  preloadMember(RAVEN_STAND_01D)
  preloadMember(RAVEN_THROW_01)
  preloadMember(RAVEN_THROW_01D)
  preloadMember(RAVEN_THROW_02)
  preloadMember(RAVEN_THROW_02D)
  preloadMember(RAVEN_WALK_01)
  preloadMember(RAVEN_WALK_02)
  preloadMember(RAVEN_WALK_03)
  preloadMember(RAVEN_WALK_04)
  preloadMember(RAVEN_WALK_05)
  preloadMember(RAVEN_WALK_06)
  preloadMember(RAVEN_WALK_07)
  preloadMember(RAVEN_WALK_08)
  preloadMember(SFX_RAVEN_FLOATDOWN)
  preloadMember(SFX_RAVEN_FLOATHORIZONTAL)
  preloadMember(SFX_RAVEN_FLOATUP)
  preloadMember(SFX_RAVEN_LEVITATEDOBJECTSHIT)
  preloadMember(SFX_RAVEN_LEVITATEDOBJECTSMISS)
  preloadMember(SFX_RAVEN_LEVITATEOBJECT)
end
