property HUD_BG, HUD_CLOCK_NUM_0, HUD_CLOCK_NUM_1, HUD_CLOCK_NUM_2, HUD_CLOCK_NUM_3, HUD_CLOCK_NUM_4, HUD_CLOCK_NUM_5, HUD_CLOCK_NUM_6, HUD_CLOCK_NUM_7, HUD_CLOCK_NUM_8, HUD_CLOCK_NUM_9, HUD_CLOCK_PIE_OFF_1, HUD_CLOCK_PIE_OFF_2, HUD_CLOCK_PIE_OFF_3, HUD_CLOCK_PIE_OFF_4, HUD_CLOCK_PIE_OFF_5, HUD_CLOCK_PIE_OFF_6, HUD_CLOCK_PIE_ON_1, HUD_CLOCK_PIE_ON_2, HUD_CLOCK_PIE_ON_3, HUD_CLOCK_PIE_ON_4, HUD_CLOCK_PIE_ON_5, HUD_CLOCK_PIE_ON_6, HUD_LIFEBAR_BG, HUD_LIFEBAR_END_GREEN_01, HUD_LIFEBAR_END_GREEN_02, HUD_LIFEBAR_END_GREEN_03, HUD_LIFEBAR_END_GREEN_04, HUD_LIFEBAR_END_GREEN_05, HUD_LIFEBAR_END_GREEN_06, HUD_LIFEBAR_END_ORANGE_01, HUD_LIFEBAR_END_ORANGE_02, HUD_LIFEBAR_END_ORANGE_03, HUD_LIFEBAR_END_ORANGE_04, HUD_LIFEBAR_END_ORANGE_05, HUD_LIFEBAR_END_ORANGE_06, HUD_LIFEBAR_END_RED_01, HUD_LIFEBAR_END_RED_02, HUD_LIFEBAR_END_RED_03, HUD_LIFEBAR_END_RED_04, HUD_LIFEBAR_END_RED_05, HUD_LIFEBAR_END_RED_06, HUD_LIFEBAR_END_WHITE_01, HUD_LIFEBAR_END_WHITE_02, HUD_LIFEBAR_END_WHITE_03, HUD_LIFEBAR_END_WHITE_04, HUD_LIFEBAR_END_WHITE_05, HUD_LIFEBAR_END_WHITE_06, HUD_LIFEBAR_MIDDLE_GREEN_01, HUD_LIFEBAR_MIDDLE_GREEN_02, HUD_LIFEBAR_MIDDLE_GREEN_03, HUD_LIFEBAR_MIDDLE_GREEN_04, HUD_LIFEBAR_MIDDLE_GREEN_05, HUD_LIFEBAR_MIDDLE_GREEN_06, HUD_LIFEBAR_MIDDLE_GREEN_07, HUD_LIFEBAR_MIDDLE_GREEN_08, HUD_LIFEBAR_MIDDLE_GREEN_09, HUD_LIFEBAR_MIDDLE_GREEN_10, HUD_LIFEBAR_MIDDLE_ORANGE_01, HUD_LIFEBAR_MIDDLE_ORANGE_02, HUD_LIFEBAR_MIDDLE_ORANGE_03, HUD_LIFEBAR_MIDDLE_ORANGE_04, HUD_LIFEBAR_MIDDLE_ORANGE_05, HUD_LIFEBAR_MIDDLE_ORANGE_06, HUD_LIFEBAR_MIDDLE_ORANGE_07, HUD_LIFEBAR_MIDDLE_ORANGE_08, HUD_LIFEBAR_MIDDLE_ORANGE_09, HUD_LIFEBAR_MIDDLE_ORANGE_10, HUD_LIFEBAR_MIDDLE_RED_01, HUD_LIFEBAR_MIDDLE_RED_02, HUD_LIFEBAR_MIDDLE_RED_03, HUD_LIFEBAR_MIDDLE_RED_04, HUD_LIFEBAR_MIDDLE_RED_05, HUD_LIFEBAR_MIDDLE_RED_06, HUD_LIFEBAR_MIDDLE_RED_07, HUD_LIFEBAR_MIDDLE_RED_08, HUD_LIFEBAR_MIDDLE_RED_09, HUD_LIFEBAR_MIDDLE_RED_10, HUD_LIFEBAR_MIDDLE_WHITE_01, HUD_LIFEBAR_MIDDLE_WHITE_02, HUD_LIFEBAR_MIDDLE_WHITE_03, HUD_LIFEBAR_MIDDLE_WHITE_04, HUD_LIFEBAR_MIDDLE_WHITE_05, HUD_LIFEBAR_MIDDLE_WHITE_06, HUD_LIFEBAR_MIDDLE_WHITE_07, HUD_LIFEBAR_MIDDLE_WHITE_08, HUD_LIFEBAR_MIDDLE_WHITE_09, HUD_LIFEBAR_MIDDLE_WHITE_10, HUD_NAME_BEASTBOY, HUD_NAME_CINDERBLOCK, HUD_NAME_CYBORG, HUD_NAME_GIZMO, HUD_NAME_JINX, HUD_NAME_MAMMOTH, HUD_NAME_PLASMUS, HUD_NAME_RAVEN, HUD_NAME_ROBIN, HUD_NAME_STARFIRE, HUD_PORTRAIT_BEASTBOY, HUD_PORTRAIT_CINDERBLOCK, HUD_PORTRAIT_CYBORG, HUD_PORTRAIT_GIZMO, HUD_PORTRAIT_JINX, HUD_PORTRAIT_MAMMOTH, HUD_PORTRAIT_PLASMUS, HUD_PORTRAIT_RAVEN, HUD_PORTRAIT_ROBIN, HUD_PORTRAIT_STARFIRE, HUD_SCORE_NUMBER_0, HUD_SCORE_NUMBER_1, HUD_SCORE_NUMBER_2, HUD_SCORE_NUMBER_3, HUD_SCORE_NUMBER_4, HUD_SCORE_NUMBER_5, HUD_SCORE_NUMBER_6, HUD_SCORE_NUMBER_7, HUD_SCORE_NUMBER_8, HUD_SCORE_NUMBER_9, HUD_SCREEN_FLASH, HUD_SUMMON_PORTRAIT_BEASTBOY, HUD_SUMMON_PORTRAIT_BEASTBOY_GREY, HUD_SUMMON_PORTRAIT_CYBORG, HUD_SUMMON_PORTRAIT_CYBORG_GREY, HUD_SUMMON_PORTRAIT_FLASH, HUD_SUMMON_PORTRAIT_RAVEN, HUD_SUMMON_PORTRAIT_RAVEN_GREY, HUD_SUMMON_PORTRAIT_ROBIN, HUD_SUMMON_PORTRAIT_ROBIN_GREY, HUD_SUMMON_PORTRAIT_STARFIRE, HUD_SUMMON_PORTRAIT_STARFIRE_GREY, HUD_WIN_LEFT_OFF, HUD_WIN_LEFT_ON, HUD_WIN_RIGHT_OFF, HUD_WIN_RIGHT_ON

on new me
  me.locateMembers()
  return me
end

on locateMembers me
  util = new(script("Class_Utility"))
  ASSET_CAST = "hud"
  HUD_BG = util.findMember("hud_bg", ASSET_CAST)
  HUD_CLOCK_NUM_0 = util.findMember("hud_clock_num_0", ASSET_CAST)
  HUD_CLOCK_NUM_1 = util.findMember("hud_clock_num_1", ASSET_CAST)
  HUD_CLOCK_NUM_2 = util.findMember("hud_clock_num_2", ASSET_CAST)
  HUD_CLOCK_NUM_3 = util.findMember("hud_clock_num_3", ASSET_CAST)
  HUD_CLOCK_NUM_4 = util.findMember("hud_clock_num_4", ASSET_CAST)
  HUD_CLOCK_NUM_5 = util.findMember("hud_clock_num_5", ASSET_CAST)
  HUD_CLOCK_NUM_6 = util.findMember("hud_clock_num_6", ASSET_CAST)
  HUD_CLOCK_NUM_7 = util.findMember("hud_clock_num_7", ASSET_CAST)
  HUD_CLOCK_NUM_8 = util.findMember("hud_clock_num_8", ASSET_CAST)
  HUD_CLOCK_NUM_9 = util.findMember("hud_clock_num_9", ASSET_CAST)
  HUD_CLOCK_PIE_OFF_1 = util.findMember("hud_clock_pie_off_1", ASSET_CAST)
  HUD_CLOCK_PIE_OFF_2 = util.findMember("hud_clock_pie_off_2", ASSET_CAST)
  HUD_CLOCK_PIE_OFF_3 = util.findMember("hud_clock_pie_off_3", ASSET_CAST)
  HUD_CLOCK_PIE_OFF_4 = util.findMember("hud_clock_pie_off_4", ASSET_CAST)
  HUD_CLOCK_PIE_OFF_5 = util.findMember("hud_clock_pie_off_5", ASSET_CAST)
  HUD_CLOCK_PIE_OFF_6 = util.findMember("hud_clock_pie_off_6", ASSET_CAST)
  HUD_CLOCK_PIE_ON_1 = util.findMember("hud_clock_pie_on_1", ASSET_CAST)
  HUD_CLOCK_PIE_ON_2 = util.findMember("hud_clock_pie_on_2", ASSET_CAST)
  HUD_CLOCK_PIE_ON_3 = util.findMember("hud_clock_pie_on_3", ASSET_CAST)
  HUD_CLOCK_PIE_ON_4 = util.findMember("hud_clock_pie_on_4", ASSET_CAST)
  HUD_CLOCK_PIE_ON_5 = util.findMember("hud_clock_pie_on_5", ASSET_CAST)
  HUD_CLOCK_PIE_ON_6 = util.findMember("hud_clock_pie_on_6", ASSET_CAST)
  HUD_LIFEBAR_BG = util.findMember("hud_lifebar_bg", ASSET_CAST)
  HUD_LIFEBAR_END_GREEN_01 = util.findMember("hud_lifebar_end_green_01", ASSET_CAST)
  HUD_LIFEBAR_END_GREEN_02 = util.findMember("hud_lifebar_end_green_02", ASSET_CAST)
  HUD_LIFEBAR_END_GREEN_03 = util.findMember("hud_lifebar_end_green_03", ASSET_CAST)
  HUD_LIFEBAR_END_GREEN_04 = util.findMember("hud_lifebar_end_green_04", ASSET_CAST)
  HUD_LIFEBAR_END_GREEN_05 = util.findMember("hud_lifebar_end_green_05", ASSET_CAST)
  HUD_LIFEBAR_END_GREEN_06 = util.findMember("hud_lifebar_end_green_06", ASSET_CAST)
  HUD_LIFEBAR_END_ORANGE_01 = util.findMember("hud_lifebar_end_orange_01", ASSET_CAST)
  HUD_LIFEBAR_END_ORANGE_02 = util.findMember("hud_lifebar_end_orange_02", ASSET_CAST)
  HUD_LIFEBAR_END_ORANGE_03 = util.findMember("hud_lifebar_end_orange_03", ASSET_CAST)
  HUD_LIFEBAR_END_ORANGE_04 = util.findMember("hud_lifebar_end_orange_04", ASSET_CAST)
  HUD_LIFEBAR_END_ORANGE_05 = util.findMember("hud_lifebar_end_orange_05", ASSET_CAST)
  HUD_LIFEBAR_END_ORANGE_06 = util.findMember("hud_lifebar_end_orange_06", ASSET_CAST)
  HUD_LIFEBAR_END_RED_01 = util.findMember("hud_lifebar_end_red_01", ASSET_CAST)
  HUD_LIFEBAR_END_RED_02 = util.findMember("hud_lifebar_end_red_02", ASSET_CAST)
  HUD_LIFEBAR_END_RED_03 = util.findMember("hud_lifebar_end_red_03", ASSET_CAST)
  HUD_LIFEBAR_END_RED_04 = util.findMember("hud_lifebar_end_red_04", ASSET_CAST)
  HUD_LIFEBAR_END_RED_05 = util.findMember("hud_lifebar_end_red_05", ASSET_CAST)
  HUD_LIFEBAR_END_RED_06 = util.findMember("hud_lifebar_end_red_06", ASSET_CAST)
  HUD_LIFEBAR_END_WHITE_01 = util.findMember("hud_lifebar_end_white_01", ASSET_CAST)
  HUD_LIFEBAR_END_WHITE_02 = util.findMember("hud_lifebar_end_white_02", ASSET_CAST)
  HUD_LIFEBAR_END_WHITE_03 = util.findMember("hud_lifebar_end_white_03", ASSET_CAST)
  HUD_LIFEBAR_END_WHITE_04 = util.findMember("hud_lifebar_end_white_04", ASSET_CAST)
  HUD_LIFEBAR_END_WHITE_05 = util.findMember("hud_lifebar_end_white_05", ASSET_CAST)
  HUD_LIFEBAR_END_WHITE_06 = util.findMember("hud_lifebar_end_white_06", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_GREEN_01 = util.findMember("hud_lifebar_middle_green_01", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_GREEN_02 = util.findMember("hud_lifebar_middle_green_02", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_GREEN_03 = util.findMember("hud_lifebar_middle_green_03", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_GREEN_04 = util.findMember("hud_lifebar_middle_green_04", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_GREEN_05 = util.findMember("hud_lifebar_middle_green_05", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_GREEN_06 = util.findMember("hud_lifebar_middle_green_06", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_GREEN_07 = util.findMember("hud_lifebar_middle_green_07", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_GREEN_08 = util.findMember("hud_lifebar_middle_green_08", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_GREEN_09 = util.findMember("hud_lifebar_middle_green_09", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_GREEN_10 = util.findMember("hud_lifebar_middle_green_10", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_ORANGE_01 = util.findMember("hud_lifebar_middle_orange_01", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_ORANGE_02 = util.findMember("hud_lifebar_middle_orange_02", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_ORANGE_03 = util.findMember("hud_lifebar_middle_orange_03", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_ORANGE_04 = util.findMember("hud_lifebar_middle_orange_04", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_ORANGE_05 = util.findMember("hud_lifebar_middle_orange_05", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_ORANGE_06 = util.findMember("hud_lifebar_middle_orange_06", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_ORANGE_07 = util.findMember("hud_lifebar_middle_orange_07", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_ORANGE_08 = util.findMember("hud_lifebar_middle_orange_08", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_ORANGE_09 = util.findMember("hud_lifebar_middle_orange_09", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_ORANGE_10 = util.findMember("hud_lifebar_middle_orange_10", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_RED_01 = util.findMember("hud_lifebar_middle_red_01", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_RED_02 = util.findMember("hud_lifebar_middle_red_02", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_RED_03 = util.findMember("hud_lifebar_middle_red_03", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_RED_04 = util.findMember("hud_lifebar_middle_red_04", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_RED_05 = util.findMember("hud_lifebar_middle_red_05", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_RED_06 = util.findMember("hud_lifebar_middle_red_06", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_RED_07 = util.findMember("hud_lifebar_middle_red_07", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_RED_08 = util.findMember("hud_lifebar_middle_red_08", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_RED_09 = util.findMember("hud_lifebar_middle_red_09", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_RED_10 = util.findMember("hud_lifebar_middle_red_10", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_WHITE_01 = util.findMember("hud_lifebar_middle_white_01", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_WHITE_02 = util.findMember("hud_lifebar_middle_white_02", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_WHITE_03 = util.findMember("hud_lifebar_middle_white_03", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_WHITE_04 = util.findMember("hud_lifebar_middle_white_04", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_WHITE_05 = util.findMember("hud_lifebar_middle_white_05", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_WHITE_06 = util.findMember("hud_lifebar_middle_white_06", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_WHITE_07 = util.findMember("hud_lifebar_middle_white_07", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_WHITE_08 = util.findMember("hud_lifebar_middle_white_08", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_WHITE_09 = util.findMember("hud_lifebar_middle_white_09", ASSET_CAST)
  HUD_LIFEBAR_MIDDLE_WHITE_10 = util.findMember("hud_lifebar_middle_white_10", ASSET_CAST)
  HUD_NAME_BEASTBOY = util.findMember("hud_name_beastboy", ASSET_CAST)
  HUD_NAME_CINDERBLOCK = util.findMember("hud_name_cinderblock", ASSET_CAST)
  HUD_NAME_CYBORG = util.findMember("hud_name_cyborg", ASSET_CAST)
  HUD_NAME_GIZMO = util.findMember("hud_name_gizmo", ASSET_CAST)
  HUD_NAME_JINX = util.findMember("hud_name_jinx", ASSET_CAST)
  HUD_NAME_MAMMOTH = util.findMember("hud_name_mammoth", ASSET_CAST)
  HUD_NAME_PLASMUS = util.findMember("hud_name_plasmus", ASSET_CAST)
  HUD_NAME_RAVEN = util.findMember("hud_name_raven", ASSET_CAST)
  HUD_NAME_ROBIN = util.findMember("hud_name_robin", ASSET_CAST)
  HUD_NAME_STARFIRE = util.findMember("hud_name_starfire", ASSET_CAST)
  HUD_PORTRAIT_BEASTBOY = util.findMember("hud_portrait_beastboy", ASSET_CAST)
  HUD_PORTRAIT_CINDERBLOCK = util.findMember("hud_portrait_cinderblock", ASSET_CAST)
  HUD_PORTRAIT_CYBORG = util.findMember("hud_portrait_cyborg", ASSET_CAST)
  HUD_PORTRAIT_GIZMO = util.findMember("hud_portrait_gizmo", ASSET_CAST)
  HUD_PORTRAIT_JINX = util.findMember("hud_portrait_jinx", ASSET_CAST)
  HUD_PORTRAIT_MAMMOTH = util.findMember("hud_portrait_mammoth", ASSET_CAST)
  HUD_PORTRAIT_PLASMUS = util.findMember("hud_portrait_plasmus", ASSET_CAST)
  HUD_PORTRAIT_RAVEN = util.findMember("hud_portrait_raven", ASSET_CAST)
  HUD_PORTRAIT_ROBIN = util.findMember("hud_portrait_robin", ASSET_CAST)
  HUD_PORTRAIT_STARFIRE = util.findMember("hud_portrait_starfire", ASSET_CAST)
  HUD_SCORE_NUMBER_0 = util.findMember("hud_score_number_0", ASSET_CAST)
  HUD_SCORE_NUMBER_1 = util.findMember("hud_score_number_1", ASSET_CAST)
  HUD_SCORE_NUMBER_2 = util.findMember("hud_score_number_2", ASSET_CAST)
  HUD_SCORE_NUMBER_3 = util.findMember("hud_score_number_3", ASSET_CAST)
  HUD_SCORE_NUMBER_4 = util.findMember("hud_score_number_4", ASSET_CAST)
  HUD_SCORE_NUMBER_5 = util.findMember("hud_score_number_5", ASSET_CAST)
  HUD_SCORE_NUMBER_6 = util.findMember("hud_score_number_6", ASSET_CAST)
  HUD_SCORE_NUMBER_7 = util.findMember("hud_score_number_7", ASSET_CAST)
  HUD_SCORE_NUMBER_8 = util.findMember("hud_score_number_8", ASSET_CAST)
  HUD_SCORE_NUMBER_9 = util.findMember("hud_score_number_9", ASSET_CAST)
  HUD_SCREEN_FLASH = util.findMember("hud_screen_flash", ASSET_CAST)
  HUD_SUMMON_PORTRAIT_BEASTBOY = util.findMember("hud_summon_portrait_beastboy", ASSET_CAST)
  HUD_SUMMON_PORTRAIT_BEASTBOY_GREY = util.findMember("hud_summon_portrait_beastboy_grey", ASSET_CAST)
  HUD_SUMMON_PORTRAIT_CYBORG = util.findMember("hud_summon_portrait_cyborg", ASSET_CAST)
  HUD_SUMMON_PORTRAIT_CYBORG_GREY = util.findMember("hud_summon_portrait_cyborg_grey", ASSET_CAST)
  HUD_SUMMON_PORTRAIT_FLASH = util.findMember("hud_summon_portrait_flash", ASSET_CAST)
  HUD_SUMMON_PORTRAIT_RAVEN = util.findMember("hud_summon_portrait_raven", ASSET_CAST)
  HUD_SUMMON_PORTRAIT_RAVEN_GREY = util.findMember("hud_summon_portrait_raven_grey", ASSET_CAST)
  HUD_SUMMON_PORTRAIT_ROBIN = util.findMember("hud_summon_portrait_robin", ASSET_CAST)
  HUD_SUMMON_PORTRAIT_ROBIN_GREY = util.findMember("hud_summon_portrait_robin_grey", ASSET_CAST)
  HUD_SUMMON_PORTRAIT_STARFIRE = util.findMember("hud_summon_portrait_starfire", ASSET_CAST)
  HUD_SUMMON_PORTRAIT_STARFIRE_GREY = util.findMember("hud_summon_portrait_starfire_grey", ASSET_CAST)
  HUD_WIN_LEFT_OFF = util.findMember("hud_win_left_off", ASSET_CAST)
  HUD_WIN_LEFT_ON = util.findMember("hud_win_left_on", ASSET_CAST)
  HUD_WIN_RIGHT_OFF = util.findMember("hud_win_right_off", ASSET_CAST)
  HUD_WIN_RIGHT_ON = util.findMember("hud_win_right_on", ASSET_CAST)
end

on precache me
  preloadMember(HUD_BG)
  preloadMember(HUD_CLOCK_NUM_0)
  preloadMember(HUD_CLOCK_NUM_1)
  preloadMember(HUD_CLOCK_NUM_2)
  preloadMember(HUD_CLOCK_NUM_3)
  preloadMember(HUD_CLOCK_NUM_4)
  preloadMember(HUD_CLOCK_NUM_5)
  preloadMember(HUD_CLOCK_NUM_6)
  preloadMember(HUD_CLOCK_NUM_7)
  preloadMember(HUD_CLOCK_NUM_8)
  preloadMember(HUD_CLOCK_NUM_9)
  preloadMember(HUD_CLOCK_PIE_OFF_1)
  preloadMember(HUD_CLOCK_PIE_OFF_2)
  preloadMember(HUD_CLOCK_PIE_OFF_3)
  preloadMember(HUD_CLOCK_PIE_OFF_4)
  preloadMember(HUD_CLOCK_PIE_OFF_5)
  preloadMember(HUD_CLOCK_PIE_OFF_6)
  preloadMember(HUD_CLOCK_PIE_ON_1)
  preloadMember(HUD_CLOCK_PIE_ON_2)
  preloadMember(HUD_CLOCK_PIE_ON_3)
  preloadMember(HUD_CLOCK_PIE_ON_4)
  preloadMember(HUD_CLOCK_PIE_ON_5)
  preloadMember(HUD_CLOCK_PIE_ON_6)
  preloadMember(HUD_LIFEBAR_BG)
  preloadMember(HUD_LIFEBAR_END_GREEN_01)
  preloadMember(HUD_LIFEBAR_END_GREEN_02)
  preloadMember(HUD_LIFEBAR_END_GREEN_03)
  preloadMember(HUD_LIFEBAR_END_GREEN_04)
  preloadMember(HUD_LIFEBAR_END_GREEN_05)
  preloadMember(HUD_LIFEBAR_END_GREEN_06)
  preloadMember(HUD_LIFEBAR_END_ORANGE_01)
  preloadMember(HUD_LIFEBAR_END_ORANGE_02)
  preloadMember(HUD_LIFEBAR_END_ORANGE_03)
  preloadMember(HUD_LIFEBAR_END_ORANGE_04)
  preloadMember(HUD_LIFEBAR_END_ORANGE_05)
  preloadMember(HUD_LIFEBAR_END_ORANGE_06)
  preloadMember(HUD_LIFEBAR_END_RED_01)
  preloadMember(HUD_LIFEBAR_END_RED_02)
  preloadMember(HUD_LIFEBAR_END_RED_03)
  preloadMember(HUD_LIFEBAR_END_RED_04)
  preloadMember(HUD_LIFEBAR_END_RED_05)
  preloadMember(HUD_LIFEBAR_END_RED_06)
  preloadMember(HUD_LIFEBAR_END_WHITE_01)
  preloadMember(HUD_LIFEBAR_END_WHITE_02)
  preloadMember(HUD_LIFEBAR_END_WHITE_03)
  preloadMember(HUD_LIFEBAR_END_WHITE_04)
  preloadMember(HUD_LIFEBAR_END_WHITE_05)
  preloadMember(HUD_LIFEBAR_END_WHITE_06)
  preloadMember(HUD_LIFEBAR_MIDDLE_GREEN_01)
  preloadMember(HUD_LIFEBAR_MIDDLE_GREEN_02)
  preloadMember(HUD_LIFEBAR_MIDDLE_GREEN_03)
  preloadMember(HUD_LIFEBAR_MIDDLE_GREEN_04)
  preloadMember(HUD_LIFEBAR_MIDDLE_GREEN_05)
  preloadMember(HUD_LIFEBAR_MIDDLE_GREEN_06)
  preloadMember(HUD_LIFEBAR_MIDDLE_GREEN_07)
  preloadMember(HUD_LIFEBAR_MIDDLE_GREEN_08)
  preloadMember(HUD_LIFEBAR_MIDDLE_GREEN_09)
  preloadMember(HUD_LIFEBAR_MIDDLE_GREEN_10)
  preloadMember(HUD_LIFEBAR_MIDDLE_ORANGE_01)
  preloadMember(HUD_LIFEBAR_MIDDLE_ORANGE_02)
  preloadMember(HUD_LIFEBAR_MIDDLE_ORANGE_03)
  preloadMember(HUD_LIFEBAR_MIDDLE_ORANGE_04)
  preloadMember(HUD_LIFEBAR_MIDDLE_ORANGE_05)
  preloadMember(HUD_LIFEBAR_MIDDLE_ORANGE_06)
  preloadMember(HUD_LIFEBAR_MIDDLE_ORANGE_07)
  preloadMember(HUD_LIFEBAR_MIDDLE_ORANGE_08)
  preloadMember(HUD_LIFEBAR_MIDDLE_ORANGE_09)
  preloadMember(HUD_LIFEBAR_MIDDLE_ORANGE_10)
  preloadMember(HUD_LIFEBAR_MIDDLE_RED_01)
  preloadMember(HUD_LIFEBAR_MIDDLE_RED_02)
  preloadMember(HUD_LIFEBAR_MIDDLE_RED_03)
  preloadMember(HUD_LIFEBAR_MIDDLE_RED_04)
  preloadMember(HUD_LIFEBAR_MIDDLE_RED_05)
  preloadMember(HUD_LIFEBAR_MIDDLE_RED_06)
  preloadMember(HUD_LIFEBAR_MIDDLE_RED_07)
  preloadMember(HUD_LIFEBAR_MIDDLE_RED_08)
  preloadMember(HUD_LIFEBAR_MIDDLE_RED_09)
  preloadMember(HUD_LIFEBAR_MIDDLE_RED_10)
  preloadMember(HUD_LIFEBAR_MIDDLE_WHITE_01)
  preloadMember(HUD_LIFEBAR_MIDDLE_WHITE_02)
  preloadMember(HUD_LIFEBAR_MIDDLE_WHITE_03)
  preloadMember(HUD_LIFEBAR_MIDDLE_WHITE_04)
  preloadMember(HUD_LIFEBAR_MIDDLE_WHITE_05)
  preloadMember(HUD_LIFEBAR_MIDDLE_WHITE_06)
  preloadMember(HUD_LIFEBAR_MIDDLE_WHITE_07)
  preloadMember(HUD_LIFEBAR_MIDDLE_WHITE_08)
  preloadMember(HUD_LIFEBAR_MIDDLE_WHITE_09)
  preloadMember(HUD_LIFEBAR_MIDDLE_WHITE_10)
  preloadMember(HUD_NAME_BEASTBOY)
  preloadMember(HUD_NAME_CINDERBLOCK)
  preloadMember(HUD_NAME_CYBORG)
  preloadMember(HUD_NAME_GIZMO)
  preloadMember(HUD_NAME_JINX)
  preloadMember(HUD_NAME_MAMMOTH)
  preloadMember(HUD_NAME_PLASMUS)
  preloadMember(HUD_NAME_RAVEN)
  preloadMember(HUD_NAME_ROBIN)
  preloadMember(HUD_NAME_STARFIRE)
  preloadMember(HUD_PORTRAIT_BEASTBOY)
  preloadMember(HUD_PORTRAIT_CINDERBLOCK)
  preloadMember(HUD_PORTRAIT_CYBORG)
  preloadMember(HUD_PORTRAIT_GIZMO)
  preloadMember(HUD_PORTRAIT_JINX)
  preloadMember(HUD_PORTRAIT_MAMMOTH)
  preloadMember(HUD_PORTRAIT_PLASMUS)
  preloadMember(HUD_PORTRAIT_RAVEN)
  preloadMember(HUD_PORTRAIT_ROBIN)
  preloadMember(HUD_PORTRAIT_STARFIRE)
  preloadMember(HUD_SCORE_NUMBER_0)
  preloadMember(HUD_SCORE_NUMBER_1)
  preloadMember(HUD_SCORE_NUMBER_2)
  preloadMember(HUD_SCORE_NUMBER_3)
  preloadMember(HUD_SCORE_NUMBER_4)
  preloadMember(HUD_SCORE_NUMBER_5)
  preloadMember(HUD_SCORE_NUMBER_6)
  preloadMember(HUD_SCORE_NUMBER_7)
  preloadMember(HUD_SCORE_NUMBER_8)
  preloadMember(HUD_SCORE_NUMBER_9)
  preloadMember(HUD_SCREEN_FLASH)
  preloadMember(HUD_SUMMON_PORTRAIT_BEASTBOY)
  preloadMember(HUD_SUMMON_PORTRAIT_BEASTBOY_GREY)
  preloadMember(HUD_SUMMON_PORTRAIT_CYBORG)
  preloadMember(HUD_SUMMON_PORTRAIT_CYBORG_GREY)
  preloadMember(HUD_SUMMON_PORTRAIT_FLASH)
  preloadMember(HUD_SUMMON_PORTRAIT_RAVEN)
  preloadMember(HUD_SUMMON_PORTRAIT_RAVEN_GREY)
  preloadMember(HUD_SUMMON_PORTRAIT_ROBIN)
  preloadMember(HUD_SUMMON_PORTRAIT_ROBIN_GREY)
  preloadMember(HUD_SUMMON_PORTRAIT_STARFIRE)
  preloadMember(HUD_SUMMON_PORTRAIT_STARFIRE_GREY)
  preloadMember(HUD_WIN_LEFT_OFF)
  preloadMember(HUD_WIN_LEFT_ON)
  preloadMember(HUD_WIN_RIGHT_OFF)
  preloadMember(HUD_WIN_RIGHT_ON)
end
