property BEASTBOY_APE_01, BEASTBOY_APE_01D, BEASTBOY_APE_02, BEASTBOY_APE_02D, BEASTBOY_APE_03, BEASTBOY_APE_03A, BEASTBOY_APE_03D, BEASTBOY_APE_TRANSFORM_01, BEASTBOY_APE_TRANSFORM_03, BEASTBOY_CROUCH_01, BEASTBOY_CROUCH_01D, BEASTBOY_CROUCH_TRANSFORM_01, BEASTBOY_EAGLE_01, BEASTBOY_EAGLE_01D, BEASTBOY_EAGLE_02, BEASTBOY_EAGLE_02A, BEASTBOY_EAGLE_03, BEASTBOY_EAGLE_TRANSFORM_01, BEASTBOY_EAGLE_TRANSFORM_03, BEASTBOY_FALL_01, BEASTBOY_FALL_01D, BEASTBOY_FALL_02, BEASTBOY_FALL_02D, BEASTBOY_HIT_01, BEASTBOY_HIT_01D, BEASTBOY_JUMP_01, BEASTBOY_JUMP_01D, BEASTBOY_JUMP_02, BEASTBOY_JUMP_02D, BEASTBOY_JUMP_03, BEASTBOY_JUMP_03D, BEASTBOY_JUMP_04, BEASTBOY_JUMP_04D, BEASTBOY_JUMP_TRANSFORM_02, BEASTBOY_JUMP_TRANSFORM_04, BEASTBOY_KICK_01, BEASTBOY_KICK_01D, BEASTBOY_KICK_02, BEASTBOY_KICK_02D, BEASTBOY_KICK_03, BEASTBOY_KICK_03A, BEASTBOY_KICK_03D, BEASTBOY_PTERODACTYL_01D, BEASTBOY_PTERODACTYL_02A, BEASTBOY_PTERODACTYL_02D, BEASTBOY_PTERODACTYL_03D, BEASTBOY_PTERODACTYL_TRANSFORM_01, BEASTBOY_PTERODACTYL_TRANSFORM_02, BEASTBOY_PUNCH_01, BEASTBOY_PUNCH_01D, BEASTBOY_PUNCH_02, BEASTBOY_PUNCH_02A, BEASTBOY_PUNCH_02D, BEASTBOY_PUNCH_03, BEASTBOY_PUNCH_03D, BEASTBOY_RHINO_ATTACK_01, BEASTBOY_RHINO_ATTACK_02, BEASTBOY_RHINO_ATTACK_02A, BEASTBOY_RHINO_RUN_01, BEASTBOY_RHINO_RUN_01D, BEASTBOY_RHINO_RUN_02, BEASTBOY_RHINO_RUN_03, BEASTBOY_RHINO_RUN_04, BEASTBOY_RHINO_TRANSFORM_01, BEASTBOY_RHINO_TRANSFORM_02, BEASTBOY_STAND_01, BEASTBOY_STAND_01D, BEASTBOY_STAND_TRANSFORM_01, BEASTBOY_STANDUP_01, BEASTBOY_STANDUP_01D, BEASTBOY_WALK_01, BEASTBOY_WALK_02, BEASTBOY_WALK_03, BEASTBOY_WALK_04, BEASTBOY_WALK_05, BEASTBOY_WALK_06, BEASTBOY_WALK_07, BEASTBOY_WALK_08, BEASTBOY_WAVE_PROJECTILE_01A, SFX_BEASTBOY_BIRD, SFX_BEASTBOY_GORILLA, SFX_BEASTBOY_GORILLAHIT, SFX_BEASTBOY_RHINOGALLOP, SFX_BEASTBOY_RHINOHIT, SFX_BEASTBOY_RHINOMISS, SFX_BEASTBOY_TRANSFORM, SFX_BEASTBOY_TRANSFORMBACK

on new me
  me.locateMembers()
  return me
end

on locateMembers me
  util = new(script("Class_Utility"))
  ASSET_CAST = "char_Beastboy"
  BEASTBOY_APE_01 = util.findMember("beastboy_ape_01", ASSET_CAST)
  BEASTBOY_APE_01D = util.findMember("beastboy_ape_01d", ASSET_CAST)
  BEASTBOY_APE_02 = util.findMember("beastboy_ape_02", ASSET_CAST)
  BEASTBOY_APE_02D = util.findMember("beastboy_ape_02d", ASSET_CAST)
  BEASTBOY_APE_03 = util.findMember("beastboy_ape_03", ASSET_CAST)
  BEASTBOY_APE_03A = util.findMember("beastboy_ape_03a", ASSET_CAST)
  BEASTBOY_APE_03D = util.findMember("beastboy_ape_03d", ASSET_CAST)
  BEASTBOY_APE_TRANSFORM_01 = util.findMember("beastboy_ape_transform_01", ASSET_CAST)
  BEASTBOY_APE_TRANSFORM_03 = util.findMember("beastboy_ape_transform_03", ASSET_CAST)
  BEASTBOY_CROUCH_01 = util.findMember("beastboy_crouch_01", ASSET_CAST)
  BEASTBOY_CROUCH_01D = util.findMember("beastboy_crouch_01d", ASSET_CAST)
  BEASTBOY_CROUCH_TRANSFORM_01 = util.findMember("beastboy_crouch_transform_01", ASSET_CAST)
  BEASTBOY_EAGLE_01 = util.findMember("beastboy_eagle_01", ASSET_CAST)
  BEASTBOY_EAGLE_01D = util.findMember("beastboy_eagle_01d", ASSET_CAST)
  BEASTBOY_EAGLE_02 = util.findMember("beastboy_eagle_02", ASSET_CAST)
  BEASTBOY_EAGLE_02A = util.findMember("beastboy_eagle_02a", ASSET_CAST)
  BEASTBOY_EAGLE_03 = util.findMember("beastboy_eagle_03", ASSET_CAST)
  BEASTBOY_EAGLE_TRANSFORM_01 = util.findMember("beastboy_eagle_transform_01", ASSET_CAST)
  BEASTBOY_EAGLE_TRANSFORM_03 = util.findMember("beastboy_eagle_transform_03", ASSET_CAST)
  BEASTBOY_FALL_01 = util.findMember("beastboy_fall_01", ASSET_CAST)
  BEASTBOY_FALL_01D = util.findMember("beastboy_fall_01d", ASSET_CAST)
  BEASTBOY_FALL_02 = util.findMember("beastboy_fall_02", ASSET_CAST)
  BEASTBOY_FALL_02D = util.findMember("beastboy_fall_02d", ASSET_CAST)
  BEASTBOY_HIT_01 = util.findMember("beastboy_hit_01", ASSET_CAST)
  BEASTBOY_HIT_01D = util.findMember("beastboy_hit_01d", ASSET_CAST)
  BEASTBOY_JUMP_01 = util.findMember("beastboy_jump_01", ASSET_CAST)
  BEASTBOY_JUMP_01D = util.findMember("beastboy_jump_01d", ASSET_CAST)
  BEASTBOY_JUMP_02 = util.findMember("beastboy_jump_02", ASSET_CAST)
  BEASTBOY_JUMP_02D = util.findMember("beastboy_jump_02d", ASSET_CAST)
  BEASTBOY_JUMP_03 = util.findMember("beastboy_jump_03", ASSET_CAST)
  BEASTBOY_JUMP_03D = util.findMember("beastboy_jump_03d", ASSET_CAST)
  BEASTBOY_JUMP_04 = util.findMember("beastboy_jump_04", ASSET_CAST)
  BEASTBOY_JUMP_04D = util.findMember("beastboy_jump_04d", ASSET_CAST)
  BEASTBOY_JUMP_TRANSFORM_02 = util.findMember("beastboy_jump_transform_02", ASSET_CAST)
  BEASTBOY_JUMP_TRANSFORM_04 = util.findMember("beastboy_jump_transform_04", ASSET_CAST)
  BEASTBOY_KICK_01 = util.findMember("beastboy_kick_01", ASSET_CAST)
  BEASTBOY_KICK_01D = util.findMember("beastboy_kick_01d", ASSET_CAST)
  BEASTBOY_KICK_02 = util.findMember("beastboy_kick_02", ASSET_CAST)
  BEASTBOY_KICK_02D = util.findMember("beastboy_kick_02d", ASSET_CAST)
  BEASTBOY_KICK_03 = util.findMember("beastboy_kick_03", ASSET_CAST)
  BEASTBOY_KICK_03A = util.findMember("beastboy_kick_03a", ASSET_CAST)
  BEASTBOY_KICK_03D = util.findMember("beastboy_kick_03d", ASSET_CAST)
  BEASTBOY_PTERODACTYL_01D = util.findMember("beastboy_pterodactyl_01d", ASSET_CAST)
  BEASTBOY_PTERODACTYL_02A = util.findMember("beastboy_pterodactyl_02a", ASSET_CAST)
  BEASTBOY_PTERODACTYL_02D = util.findMember("beastboy_pterodactyl_02d", ASSET_CAST)
  BEASTBOY_PTERODACTYL_03D = util.findMember("beastboy_pterodactyl_03d", ASSET_CAST)
  BEASTBOY_PTERODACTYL_TRANSFORM_01 = util.findMember("beastboy_pterodactyl_transform_01", ASSET_CAST)
  BEASTBOY_PTERODACTYL_TRANSFORM_02 = util.findMember("beastboy_pterodactyl_transform_02", ASSET_CAST)
  BEASTBOY_PUNCH_01 = util.findMember("beastboy_punch_01", ASSET_CAST)
  BEASTBOY_PUNCH_01D = util.findMember("beastboy_punch_01d", ASSET_CAST)
  BEASTBOY_PUNCH_02 = util.findMember("beastboy_punch_02", ASSET_CAST)
  BEASTBOY_PUNCH_02A = util.findMember("beastboy_punch_02a", ASSET_CAST)
  BEASTBOY_PUNCH_02D = util.findMember("beastboy_punch_02d", ASSET_CAST)
  BEASTBOY_PUNCH_03 = util.findMember("beastboy_punch_03", ASSET_CAST)
  BEASTBOY_PUNCH_03D = util.findMember("beastboy_punch_03d", ASSET_CAST)
  BEASTBOY_RHINO_ATTACK_01 = util.findMember("beastboy_rhino_attack_01", ASSET_CAST)
  BEASTBOY_RHINO_ATTACK_02 = util.findMember("beastboy_rhino_attack_02", ASSET_CAST)
  BEASTBOY_RHINO_ATTACK_02A = util.findMember("beastboy_rhino_attack_02a", ASSET_CAST)
  BEASTBOY_RHINO_RUN_01 = util.findMember("beastboy_rhino_run_01", ASSET_CAST)
  BEASTBOY_RHINO_RUN_01D = util.findMember("beastboy_rhino_run_01d", ASSET_CAST)
  BEASTBOY_RHINO_RUN_02 = util.findMember("beastboy_rhino_run_02", ASSET_CAST)
  BEASTBOY_RHINO_RUN_03 = util.findMember("beastboy_rhino_run_03", ASSET_CAST)
  BEASTBOY_RHINO_RUN_04 = util.findMember("beastboy_rhino_run_04", ASSET_CAST)
  BEASTBOY_RHINO_TRANSFORM_01 = util.findMember("beastboy_rhino_transform_01", ASSET_CAST)
  BEASTBOY_RHINO_TRANSFORM_02 = util.findMember("beastboy_rhino_transform_02", ASSET_CAST)
  BEASTBOY_STAND_01 = util.findMember("beastboy_stand_01", ASSET_CAST)
  BEASTBOY_STAND_01D = util.findMember("beastboy_stand_01d", ASSET_CAST)
  BEASTBOY_STAND_TRANSFORM_01 = util.findMember("beastboy_stand_transform_01", ASSET_CAST)
  BEASTBOY_STANDUP_01 = util.findMember("beastboy_standup_01", ASSET_CAST)
  BEASTBOY_STANDUP_01D = util.findMember("beastboy_standup_01d", ASSET_CAST)
  BEASTBOY_WALK_01 = util.findMember("beastboy_walk_01", ASSET_CAST)
  BEASTBOY_WALK_02 = util.findMember("beastboy_walk_02", ASSET_CAST)
  BEASTBOY_WALK_03 = util.findMember("beastboy_walk_03", ASSET_CAST)
  BEASTBOY_WALK_04 = util.findMember("beastboy_walk_04", ASSET_CAST)
  BEASTBOY_WALK_05 = util.findMember("beastboy_walk_05", ASSET_CAST)
  BEASTBOY_WALK_06 = util.findMember("beastboy_walk_06", ASSET_CAST)
  BEASTBOY_WALK_07 = util.findMember("beastboy_walk_07", ASSET_CAST)
  BEASTBOY_WALK_08 = util.findMember("beastboy_walk_08", ASSET_CAST)
  BEASTBOY_WAVE_PROJECTILE_01A = util.findMember("beastboy_wave_projectile_01a", ASSET_CAST)
  SFX_BEASTBOY_BIRD = util.findMember("sfx_beastboy_bird", ASSET_CAST)
  SFX_BEASTBOY_GORILLA = util.findMember("sfx_beastboy_gorilla", ASSET_CAST)
  SFX_BEASTBOY_GORILLAHIT = util.findMember("sfx_beastboy_gorillahit", ASSET_CAST)
  SFX_BEASTBOY_RHINOGALLOP = util.findMember("sfx_beastboy_rhinogallop", ASSET_CAST)
  SFX_BEASTBOY_RHINOHIT = util.findMember("sfx_beastboy_rhinohit", ASSET_CAST)
  SFX_BEASTBOY_RHINOMISS = util.findMember("sfx_beastboy_rhinomiss", ASSET_CAST)
  SFX_BEASTBOY_TRANSFORM = util.findMember("sfx_beastboy_transform", ASSET_CAST)
  SFX_BEASTBOY_TRANSFORMBACK = util.findMember("sfx_beastboy_transformback", ASSET_CAST)
end

on precache me
  preloadMember(BEASTBOY_APE_01)
  preloadMember(BEASTBOY_APE_01D)
  preloadMember(BEASTBOY_APE_02)
  preloadMember(BEASTBOY_APE_02D)
  preloadMember(BEASTBOY_APE_03)
  preloadMember(BEASTBOY_APE_03A)
  preloadMember(BEASTBOY_APE_03D)
  preloadMember(BEASTBOY_APE_TRANSFORM_01)
  preloadMember(BEASTBOY_APE_TRANSFORM_03)
  preloadMember(BEASTBOY_CROUCH_01)
  preloadMember(BEASTBOY_CROUCH_01D)
  preloadMember(BEASTBOY_CROUCH_TRANSFORM_01)
  preloadMember(BEASTBOY_EAGLE_01)
  preloadMember(BEASTBOY_EAGLE_01D)
  preloadMember(BEASTBOY_EAGLE_02)
  preloadMember(BEASTBOY_EAGLE_02A)
  preloadMember(BEASTBOY_EAGLE_03)
  preloadMember(BEASTBOY_EAGLE_TRANSFORM_01)
  preloadMember(BEASTBOY_EAGLE_TRANSFORM_03)
  preloadMember(BEASTBOY_FALL_01)
  preloadMember(BEASTBOY_FALL_01D)
  preloadMember(BEASTBOY_FALL_02)
  preloadMember(BEASTBOY_FALL_02D)
  preloadMember(BEASTBOY_HIT_01)
  preloadMember(BEASTBOY_HIT_01D)
  preloadMember(BEASTBOY_JUMP_01)
  preloadMember(BEASTBOY_JUMP_01D)
  preloadMember(BEASTBOY_JUMP_02)
  preloadMember(BEASTBOY_JUMP_02D)
  preloadMember(BEASTBOY_JUMP_03)
  preloadMember(BEASTBOY_JUMP_03D)
  preloadMember(BEASTBOY_JUMP_04)
  preloadMember(BEASTBOY_JUMP_04D)
  preloadMember(BEASTBOY_JUMP_TRANSFORM_02)
  preloadMember(BEASTBOY_JUMP_TRANSFORM_04)
  preloadMember(BEASTBOY_KICK_01)
  preloadMember(BEASTBOY_KICK_01D)
  preloadMember(BEASTBOY_KICK_02)
  preloadMember(BEASTBOY_KICK_02D)
  preloadMember(BEASTBOY_KICK_03)
  preloadMember(BEASTBOY_KICK_03A)
  preloadMember(BEASTBOY_KICK_03D)
  preloadMember(BEASTBOY_PTERODACTYL_01D)
  preloadMember(BEASTBOY_PTERODACTYL_02A)
  preloadMember(BEASTBOY_PTERODACTYL_02D)
  preloadMember(BEASTBOY_PTERODACTYL_03D)
  preloadMember(BEASTBOY_PTERODACTYL_TRANSFORM_01)
  preloadMember(BEASTBOY_PTERODACTYL_TRANSFORM_02)
  preloadMember(BEASTBOY_PUNCH_01)
  preloadMember(BEASTBOY_PUNCH_01D)
  preloadMember(BEASTBOY_PUNCH_02)
  preloadMember(BEASTBOY_PUNCH_02A)
  preloadMember(BEASTBOY_PUNCH_02D)
  preloadMember(BEASTBOY_PUNCH_03)
  preloadMember(BEASTBOY_PUNCH_03D)
  preloadMember(BEASTBOY_RHINO_ATTACK_01)
  preloadMember(BEASTBOY_RHINO_ATTACK_02)
  preloadMember(BEASTBOY_RHINO_ATTACK_02A)
  preloadMember(BEASTBOY_RHINO_RUN_01)
  preloadMember(BEASTBOY_RHINO_RUN_01D)
  preloadMember(BEASTBOY_RHINO_RUN_02)
  preloadMember(BEASTBOY_RHINO_RUN_03)
  preloadMember(BEASTBOY_RHINO_RUN_04)
  preloadMember(BEASTBOY_RHINO_TRANSFORM_01)
  preloadMember(BEASTBOY_RHINO_TRANSFORM_02)
  preloadMember(BEASTBOY_STAND_01)
  preloadMember(BEASTBOY_STAND_01D)
  preloadMember(BEASTBOY_STAND_TRANSFORM_01)
  preloadMember(BEASTBOY_STANDUP_01)
  preloadMember(BEASTBOY_STANDUP_01D)
  preloadMember(BEASTBOY_WALK_01)
  preloadMember(BEASTBOY_WALK_02)
  preloadMember(BEASTBOY_WALK_03)
  preloadMember(BEASTBOY_WALK_04)
  preloadMember(BEASTBOY_WALK_05)
  preloadMember(BEASTBOY_WALK_06)
  preloadMember(BEASTBOY_WALK_07)
  preloadMember(BEASTBOY_WALK_08)
  preloadMember(BEASTBOY_WAVE_PROJECTILE_01A)
  preloadMember(SFX_BEASTBOY_BIRD)
  preloadMember(SFX_BEASTBOY_GORILLA)
  preloadMember(SFX_BEASTBOY_GORILLAHIT)
  preloadMember(SFX_BEASTBOY_RHINOGALLOP)
  preloadMember(SFX_BEASTBOY_RHINOHIT)
  preloadMember(SFX_BEASTBOY_RHINOMISS)
  preloadMember(SFX_BEASTBOY_TRANSFORM)
  preloadMember(SFX_BEASTBOY_TRANSFORMBACK)
end
