property MAMMOTH_BACKGROUND, MAMMOTH_FALL_01, MAMMOTH_FALL_01D, MAMMOTH_FALL_02, MAMMOTH_FALL_02D, MAMMOTH_GROUNDPUNCH_01, MAMMOTH_GROUNDPUNCH_01D, MAMMOTH_GROUNDPUNCH_02, MAMMOTH_GROUNDPUNCH_02D, MAMMOTH_GROUNDPUNCH_03, MAMMOTH_GROUNDPUNCH_03D, MAMMOTH_GROUNDPUNCH_04, MAMMOTH_GROUNDPUNCH_04D, MAMMOTH_HIT_01, MAMMOTH_HIT_01D, MAMMOTH_JUMP_01, MAMMOTH_JUMP_01D, MAMMOTH_JUMP_02, MAMMOTH_JUMP_02D, MAMMOTH_JUMP_03, MAMMOTH_JUMP_03D, MAMMOTH_JUMPPUNCH_01, MAMMOTH_JUMPPUNCH_01D, MAMMOTH_JUMPPUNCH_02, MAMMOTH_JUMPPUNCH_02D, MAMMOTH_JUMPPUNCH_03, MAMMOTH_JUMPPUNCH_03D, MAMMOTH_JUMPPUNCH_04, MAMMOTH_JUMPPUNCH_04A, MAMMOTH_JUMPPUNCH_04D, MAMMOTH_JUMPPUNCH_05, MAMMOTH_JUMPPUNCH_05D, MAMMOTH_PUNCH_01, MAMMOTH_PUNCH_01D, MAMMOTH_PUNCH_02, MAMMOTH_PUNCH_02A, MAMMOTH_PUNCH_02D, MAMMOTH_PUNCH_03, MAMMOTH_PUNCH_03D, MAMMOTH_PUNCH_04, MAMMOTH_PUNCH_04D, MAMMOTH_SHOULDERBARGE_01A, MAMMOTH_STAND_01, MAMMOTH_STAND_01D, MAMMOTH_WALK_01, MAMMOTH_WALK_02, MAMMOTH_WALK_03, MAMMOTH_WALK_04, MAMMOTH_WALK_05, MAMMOTH_WALK_06, MAMMOTH_WAVE_PROJECTILE_01A, SFX_MAMMOTH_AMBIENT, SFX_MAMMOTH_JUMPSPIN, SFX_MAMMOTH_JUMPSPINHIT, SFX_MAMMOTH_JUMPSPINMISS, SFX_MAMMOTH_SHOCKWAVEPUNCH, SFX_MAMMOTH_SHOCKWAVEPUNCHHIT, SFX_MAMMOTH_SHOCKWAVEPUNCHMISS, SFX_MAMMOTH_SHOULDER_BARGE_RUN, SFX_MAMMOTH_SHOULDERBARGEHIT, SFX_MAMMOTH_SHOULDERBARGEMISS

on new me
  me.locateMembers()
  return me
end

on locateMembers me
  util = new(script("Class_Utility"))
  ASSET_CAST = "char_Mammoth"
  MAMMOTH_BACKGROUND = util.findMember("mammoth_background", ASSET_CAST)
  MAMMOTH_FALL_01 = util.findMember("mammoth_fall_01", ASSET_CAST)
  MAMMOTH_FALL_01D = util.findMember("mammoth_fall_01d", ASSET_CAST)
  MAMMOTH_FALL_02 = util.findMember("mammoth_fall_02", ASSET_CAST)
  MAMMOTH_FALL_02D = util.findMember("mammoth_fall_02d", ASSET_CAST)
  MAMMOTH_GROUNDPUNCH_01 = util.findMember("mammoth_groundpunch_01", ASSET_CAST)
  MAMMOTH_GROUNDPUNCH_01D = util.findMember("mammoth_groundpunch_01d", ASSET_CAST)
  MAMMOTH_GROUNDPUNCH_02 = util.findMember("mammoth_groundpunch_02", ASSET_CAST)
  MAMMOTH_GROUNDPUNCH_02D = util.findMember("mammoth_groundpunch_02d", ASSET_CAST)
  MAMMOTH_GROUNDPUNCH_03 = util.findMember("mammoth_groundpunch_03", ASSET_CAST)
  MAMMOTH_GROUNDPUNCH_03D = util.findMember("mammoth_groundpunch_03d", ASSET_CAST)
  MAMMOTH_GROUNDPUNCH_04 = util.findMember("mammoth_groundpunch_04", ASSET_CAST)
  MAMMOTH_GROUNDPUNCH_04D = util.findMember("mammoth_groundpunch_04d", ASSET_CAST)
  MAMMOTH_HIT_01 = util.findMember("mammoth_hit_01", ASSET_CAST)
  MAMMOTH_HIT_01D = util.findMember("mammoth_hit_01d", ASSET_CAST)
  MAMMOTH_JUMP_01 = util.findMember("mammoth_jump_01", ASSET_CAST)
  MAMMOTH_JUMP_01D = util.findMember("mammoth_jump_01d", ASSET_CAST)
  MAMMOTH_JUMP_02 = util.findMember("mammoth_jump_02", ASSET_CAST)
  MAMMOTH_JUMP_02D = util.findMember("mammoth_jump_02d", ASSET_CAST)
  MAMMOTH_JUMP_03 = util.findMember("mammoth_jump_03", ASSET_CAST)
  MAMMOTH_JUMP_03D = util.findMember("mammoth_jump_03d", ASSET_CAST)
  MAMMOTH_JUMPPUNCH_01 = util.findMember("mammoth_jumppunch_01", ASSET_CAST)
  MAMMOTH_JUMPPUNCH_01D = util.findMember("mammoth_jumppunch_01d", ASSET_CAST)
  MAMMOTH_JUMPPUNCH_02 = util.findMember("mammoth_jumppunch_02", ASSET_CAST)
  MAMMOTH_JUMPPUNCH_02D = util.findMember("mammoth_jumppunch_02d", ASSET_CAST)
  MAMMOTH_JUMPPUNCH_03 = util.findMember("mammoth_jumppunch_03", ASSET_CAST)
  MAMMOTH_JUMPPUNCH_03D = util.findMember("mammoth_jumppunch_03d", ASSET_CAST)
  MAMMOTH_JUMPPUNCH_04 = util.findMember("mammoth_jumppunch_04", ASSET_CAST)
  MAMMOTH_JUMPPUNCH_04A = util.findMember("mammoth_jumppunch_04a", ASSET_CAST)
  MAMMOTH_JUMPPUNCH_04D = util.findMember("mammoth_jumppunch_04d", ASSET_CAST)
  MAMMOTH_JUMPPUNCH_05 = util.findMember("mammoth_jumppunch_05", ASSET_CAST)
  MAMMOTH_JUMPPUNCH_05D = util.findMember("mammoth_jumppunch_05d", ASSET_CAST)
  MAMMOTH_PUNCH_01 = util.findMember("mammoth_punch_01", ASSET_CAST)
  MAMMOTH_PUNCH_01D = util.findMember("mammoth_punch_01d", ASSET_CAST)
  MAMMOTH_PUNCH_02 = util.findMember("mammoth_punch_02", ASSET_CAST)
  MAMMOTH_PUNCH_02A = util.findMember("mammoth_punch_02a", ASSET_CAST)
  MAMMOTH_PUNCH_02D = util.findMember("mammoth_punch_02d", ASSET_CAST)
  MAMMOTH_PUNCH_03 = util.findMember("mammoth_punch_03", ASSET_CAST)
  MAMMOTH_PUNCH_03D = util.findMember("mammoth_punch_03d", ASSET_CAST)
  MAMMOTH_PUNCH_04 = util.findMember("mammoth_punch_04", ASSET_CAST)
  MAMMOTH_PUNCH_04D = util.findMember("mammoth_punch_04d", ASSET_CAST)
  MAMMOTH_SHOULDERBARGE_01A = util.findMember("mammoth_shoulderbarge_01a", ASSET_CAST)
  MAMMOTH_STAND_01 = util.findMember("mammoth_stand_01", ASSET_CAST)
  MAMMOTH_STAND_01D = util.findMember("mammoth_stand_01d", ASSET_CAST)
  MAMMOTH_WALK_01 = util.findMember("mammoth_walk_01", ASSET_CAST)
  MAMMOTH_WALK_02 = util.findMember("mammoth_walk_02", ASSET_CAST)
  MAMMOTH_WALK_03 = util.findMember("mammoth_walk_03", ASSET_CAST)
  MAMMOTH_WALK_04 = util.findMember("mammoth_walk_04", ASSET_CAST)
  MAMMOTH_WALK_05 = util.findMember("mammoth_walk_05", ASSET_CAST)
  MAMMOTH_WALK_06 = util.findMember("mammoth_walk_06", ASSET_CAST)
  MAMMOTH_WAVE_PROJECTILE_01A = util.findMember("mammoth_wave_projectile_01a", ASSET_CAST)
  SFX_MAMMOTH_AMBIENT = util.findMember("sfx_mammoth_ambient", ASSET_CAST)
  SFX_MAMMOTH_JUMPSPIN = util.findMember("sfx_mammoth_jumpspin", ASSET_CAST)
  SFX_MAMMOTH_JUMPSPINHIT = util.findMember("sfx_mammoth_jumpspinhit", ASSET_CAST)
  SFX_MAMMOTH_JUMPSPINMISS = util.findMember("sfx_mammoth_jumpspinmiss", ASSET_CAST)
  SFX_MAMMOTH_SHOCKWAVEPUNCH = util.findMember("sfx_mammoth_shockwavepunch", ASSET_CAST)
  SFX_MAMMOTH_SHOCKWAVEPUNCHHIT = util.findMember("sfx_mammoth_shockwavepunchhit", ASSET_CAST)
  SFX_MAMMOTH_SHOCKWAVEPUNCHMISS = util.findMember("sfx_mammoth_shockwavepunchmiss", ASSET_CAST)
  SFX_MAMMOTH_SHOULDER_BARGE_RUN = util.findMember("sfx_mammoth_shoulder_barge_run", ASSET_CAST)
  SFX_MAMMOTH_SHOULDERBARGEHIT = util.findMember("sfx_mammoth_shoulderbargehit", ASSET_CAST)
  SFX_MAMMOTH_SHOULDERBARGEMISS = util.findMember("sfx_mammoth_shoulderbargemiss", ASSET_CAST)
end

on precache me
  preloadMember(MAMMOTH_BACKGROUND)
  preloadMember(MAMMOTH_FALL_01)
  preloadMember(MAMMOTH_FALL_01D)
  preloadMember(MAMMOTH_FALL_02)
  preloadMember(MAMMOTH_FALL_02D)
  preloadMember(MAMMOTH_GROUNDPUNCH_01)
  preloadMember(MAMMOTH_GROUNDPUNCH_01D)
  preloadMember(MAMMOTH_GROUNDPUNCH_02)
  preloadMember(MAMMOTH_GROUNDPUNCH_02D)
  preloadMember(MAMMOTH_GROUNDPUNCH_03)
  preloadMember(MAMMOTH_GROUNDPUNCH_03D)
  preloadMember(MAMMOTH_GROUNDPUNCH_04)
  preloadMember(MAMMOTH_GROUNDPUNCH_04D)
  preloadMember(MAMMOTH_HIT_01)
  preloadMember(MAMMOTH_HIT_01D)
  preloadMember(MAMMOTH_JUMP_01)
  preloadMember(MAMMOTH_JUMP_01D)
  preloadMember(MAMMOTH_JUMP_02)
  preloadMember(MAMMOTH_JUMP_02D)
  preloadMember(MAMMOTH_JUMP_03)
  preloadMember(MAMMOTH_JUMP_03D)
  preloadMember(MAMMOTH_JUMPPUNCH_01)
  preloadMember(MAMMOTH_JUMPPUNCH_01D)
  preloadMember(MAMMOTH_JUMPPUNCH_02)
  preloadMember(MAMMOTH_JUMPPUNCH_02D)
  preloadMember(MAMMOTH_JUMPPUNCH_03)
  preloadMember(MAMMOTH_JUMPPUNCH_03D)
  preloadMember(MAMMOTH_JUMPPUNCH_04)
  preloadMember(MAMMOTH_JUMPPUNCH_04A)
  preloadMember(MAMMOTH_JUMPPUNCH_04D)
  preloadMember(MAMMOTH_JUMPPUNCH_05)
  preloadMember(MAMMOTH_JUMPPUNCH_05D)
  preloadMember(MAMMOTH_PUNCH_01)
  preloadMember(MAMMOTH_PUNCH_01D)
  preloadMember(MAMMOTH_PUNCH_02)
  preloadMember(MAMMOTH_PUNCH_02A)
  preloadMember(MAMMOTH_PUNCH_02D)
  preloadMember(MAMMOTH_PUNCH_03)
  preloadMember(MAMMOTH_PUNCH_03D)
  preloadMember(MAMMOTH_PUNCH_04)
  preloadMember(MAMMOTH_PUNCH_04D)
  preloadMember(MAMMOTH_SHOULDERBARGE_01A)
  preloadMember(MAMMOTH_STAND_01)
  preloadMember(MAMMOTH_STAND_01D)
  preloadMember(MAMMOTH_WALK_01)
  preloadMember(MAMMOTH_WALK_02)
  preloadMember(MAMMOTH_WALK_03)
  preloadMember(MAMMOTH_WALK_04)
  preloadMember(MAMMOTH_WALK_05)
  preloadMember(MAMMOTH_WALK_06)
  preloadMember(MAMMOTH_WAVE_PROJECTILE_01A)
  preloadMember(SFX_MAMMOTH_AMBIENT)
  preloadMember(SFX_MAMMOTH_JUMPSPIN)
  preloadMember(SFX_MAMMOTH_JUMPSPINHIT)
  preloadMember(SFX_MAMMOTH_JUMPSPINMISS)
  preloadMember(SFX_MAMMOTH_SHOCKWAVEPUNCH)
  preloadMember(SFX_MAMMOTH_SHOCKWAVEPUNCHHIT)
  preloadMember(SFX_MAMMOTH_SHOCKWAVEPUNCHMISS)
  preloadMember(SFX_MAMMOTH_SHOULDER_BARGE_RUN)
  preloadMember(SFX_MAMMOTH_SHOULDERBARGEHIT)
  preloadMember(SFX_MAMMOTH_SHOULDERBARGEMISS)
end
