property FX_PLASMUS_BLOWUP_01, FX_PLASMUS_BLOWUP_02, FX_PLASMUS_BLOWUP_03, FX_PLASMUS_BLOWUP_04, FX_PLASMUS_BLOWUP_05, FX_PLASMUS_BLOWUP_06, PLASMUS_ARMSWIPE_01, PLASMUS_ARMSWIPE_01D, PLASMUS_ARMSWIPE_02, PLASMUS_ARMSWIPE_02D, PLASMUS_ARMSWIPE_03, PLASMUS_ARMSWIPE_03_ARM1, PLASMUS_ARMSWIPE_03_ARM2, PLASMUS_ARMSWIPE_03A, PLASMUS_ARMSWIPE_03D, PLASMUS_ARMSWIPE_04, PLASMUS_ARMSWIPE_04D, PLASMUS_BACKGROUND, PLASMUS_BLOCK_01, PLASMUS_BLOCK_01D, PLASMUS_CHEST_BLAST_01, PLASMUS_CHEST_BLAST_01D, PLASMUS_CHEST_BLAST_02, PLASMUS_CHEST_BLAST_02D, PLASMUS_CHEST_BLAST_03, PLASMUS_CHEST_BLAST_03D, PLASMUS_CHEST_BLAST_04, PLASMUS_CHEST_BLAST_04D, PLASMUS_CHEST_BLAST_05, PLASMUS_CHEST_BLAST_05D, PLASMUS_CRAB_01, PLASMUS_CRAB_01D, PLASMUS_CRAB_02, PLASMUS_CRAB_02D, PLASMUS_CRAB_03, PLASMUS_CRAB_03D, PLASMUS_CRAB_04, PLASMUS_CRAB_04D, PLASMUS_CRAB_05, PLASMUS_CRAB_05D, PLASMUS_CRAB_06, PLASMUS_CRAB_06A, PLASMUS_CRAB_06D, PLASMUS_CRAB_MELT_01, PLASMUS_CRAB_MELT_02, PLASMUS_CRAB_MELT_03, PLASMUS_CRAB_MELT_04, PLASMUS_CRAB_MELT_05, PLASMUS_CRAB_MELT_06, PLASMUS_CRAB_MELT_07, PLASMUS_CRAB_MELT_08, PLASMUS_CRAB_MELT_09, PLASMUS_CRAB_MELT_10, PLASMUS_CRAB_MELT_11, PLASMUS_CRAB_MELT_12, PLASMUS_CRAB_MELT_13, PLASMUS_DEFEAT_01, PLASMUS_DEFEAT_01D, PLASMUS_DEFEAT_02, PLASMUS_DEFEAT_02D, PLASMUS_DEFEAT_03, PLASMUS_DEFEAT_03D, PLASMUS_FIST_CLENCH_01, PLASMUS_FIST_CLENCH_02, PLASMUS_FIST_CLENCH_03, PLASMUS_GLOBULE_01, PLASMUS_GLOBULE_01A, PLASMUS_GLOBULE_02, PLASMUS_GLOBULE_02A, PLASMUS_GLOBULE_03, PLASMUS_GLOBULE_03A, PLASMUS_GLOBULE_04, PLASMUS_GLOBULE_05, PLASMUS_HIT_01, PLASMUS_HIT_01D, PLASMUS_HIT_SPLATTER_01, PLASMUS_PUNCH_01, PLASMUS_PUNCH_01D, PLASMUS_PUNCH_02, PLASMUS_PUNCH_02_ARM1, PLASMUS_PUNCH_02_ARM2, PLASMUS_PUNCH_02A, PLASMUS_PUNCH_02D, PLASMUS_PUNCH_03, PLASMUS_PUNCH_03D, PLASMUS_SLUDGE_01, PLASMUS_SLUDGE_01A, PLASMUS_SLUDGE_02, PLASMUS_SLUDGE_03, PLASMUS_SLUDGE_04, PLASMUS_SLUDGE_05, PLASMUS_SLUDGE_06, PLASMUS_SLUDGE_07, PLASMUS_SLUDGE_08, PLASMUS_SLUDGE_09, PLASMUS_SLUDGE_10, PLASMUS_SLUDGE_11, PLASMUS_SLUDGE_12, PLASMUS_SLUDGE_13, PLASMUS_SLUDGE_14, PLASMUS_SLUDGE_15, PLASMUS_SLUDGE_16, PLASMUS_SPLATTER_01, PLASMUS_SPLATTER_02, PLASMUS_SPLATTER_03, PLASMUS_SPLATTER_04, PLASMUS_SPLATTER_05, PLASMUS_SPLATTER_06, PLASMUS_STAND_01D, PLASMUS_TOSS_01, PLASMUS_TOSS_01D, PLASMUS_TOSS_02, PLASMUS_TOSS_02D, PLASMUS_TOSS_03, PLASMUS_TOSS_03D, PLASMUS_TOSS_04, PLASMUS_TOSS_04D, PLASMUS_TOSS_05, PLASMUS_TOSS_05D, PLASMUS_TOSS_06, PLASMUS_TOSS_06D, PLASMUS_WALK_01, PLASMUS_WALK_02, PLASMUS_WALK_03, PLASMUS_WALK_04, PLASMUS_WALK_05, PLASMUS_WALK_06, SFX_PLASMUS_AMBIENTLOOPSCARIER, SFX_PLASMUS_CRABBITE, SFX_PLASMUS_CRABHIT, SFX_PLASMUS_CRABMISS, SFX_PLASMUS_CRABTHROW, SFX_PLASMUS_CRABWALK, SFX_PLASMUS_GLOBULEHIT, SFX_PLASMUS_GLOBULEMISS, SFX_PLASMUS_GLOBULETHROW, SFX_PLASMUS_GLOBULEWOOSH, SFX_PLASMUS_PUNCH_HIT, SFX_PLASMUS_ROAR_BIG, SFX_PLASMUS_ROAR_SMALL, SFX_PLASMUS_SHAMBLE, SFX_PLASMUS_SLUDGE_THROW, SFX_PLASMUS_STRETCH_1, SFX_PLASMUS_STRETCH_2, SFX_PLASMUS_STRETCHMISS, SFX_PLASMUS_TRANSFORM

on new me
  me.locateMembers()
  return me
end

on locateMembers me
  util = new(script("Class_Utility"))
  ASSET_CAST = "char_Plasmus"
  FX_PLASMUS_BLOWUP_01 = util.findMember("fx_plasmus_blowup_01", ASSET_CAST)
  FX_PLASMUS_BLOWUP_02 = util.findMember("fx_plasmus_blowup_02", ASSET_CAST)
  FX_PLASMUS_BLOWUP_03 = util.findMember("fx_plasmus_blowup_03", ASSET_CAST)
  FX_PLASMUS_BLOWUP_04 = util.findMember("fx_plasmus_blowup_04", ASSET_CAST)
  FX_PLASMUS_BLOWUP_05 = util.findMember("fx_plasmus_blowup_05", ASSET_CAST)
  FX_PLASMUS_BLOWUP_06 = util.findMember("fx_plasmus_blowup_06", ASSET_CAST)
  PLASMUS_ARMSWIPE_01 = util.findMember("plasmus_armswipe_01", ASSET_CAST)
  PLASMUS_ARMSWIPE_01D = util.findMember("plasmus_armswipe_01d", ASSET_CAST)
  PLASMUS_ARMSWIPE_02 = util.findMember("plasmus_armswipe_02", ASSET_CAST)
  PLASMUS_ARMSWIPE_02D = util.findMember("plasmus_armswipe_02d", ASSET_CAST)
  PLASMUS_ARMSWIPE_03 = util.findMember("plasmus_armswipe_03", ASSET_CAST)
  PLASMUS_ARMSWIPE_03_ARM1 = util.findMember("plasmus_armswipe_03_arm1", ASSET_CAST)
  PLASMUS_ARMSWIPE_03_ARM2 = util.findMember("plasmus_armswipe_03_arm2", ASSET_CAST)
  PLASMUS_ARMSWIPE_03A = util.findMember("plasmus_armswipe_03a", ASSET_CAST)
  PLASMUS_ARMSWIPE_03D = util.findMember("plasmus_armswipe_03d", ASSET_CAST)
  PLASMUS_ARMSWIPE_04 = util.findMember("plasmus_armswipe_04", ASSET_CAST)
  PLASMUS_ARMSWIPE_04D = util.findMember("plasmus_armswipe_04d", ASSET_CAST)
  PLASMUS_BACKGROUND = util.findMember("plasmus_background", ASSET_CAST)
  PLASMUS_BLOCK_01 = util.findMember("plasmus_block_01", ASSET_CAST)
  PLASMUS_BLOCK_01D = util.findMember("plasmus_block_01d", ASSET_CAST)
  PLASMUS_CHEST_BLAST_01 = util.findMember("plasmus_chest_blast_01", ASSET_CAST)
  PLASMUS_CHEST_BLAST_01D = util.findMember("plasmus_chest_blast_01d", ASSET_CAST)
  PLASMUS_CHEST_BLAST_02 = util.findMember("plasmus_chest_blast_02", ASSET_CAST)
  PLASMUS_CHEST_BLAST_02D = util.findMember("plasmus_chest_blast_02d", ASSET_CAST)
  PLASMUS_CHEST_BLAST_03 = util.findMember("plasmus_chest_blast_03", ASSET_CAST)
  PLASMUS_CHEST_BLAST_03D = util.findMember("plasmus_chest_blast_03d", ASSET_CAST)
  PLASMUS_CHEST_BLAST_04 = util.findMember("plasmus_chest_blast_04", ASSET_CAST)
  PLASMUS_CHEST_BLAST_04D = util.findMember("plasmus_chest_blast_04d", ASSET_CAST)
  PLASMUS_CHEST_BLAST_05 = util.findMember("plasmus_chest_blast_05", ASSET_CAST)
  PLASMUS_CHEST_BLAST_05D = util.findMember("plasmus_chest_blast_05d", ASSET_CAST)
  PLASMUS_CRAB_01 = util.findMember("plasmus_crab_01", ASSET_CAST)
  PLASMUS_CRAB_01D = util.findMember("plasmus_crab_01d", ASSET_CAST)
  PLASMUS_CRAB_02 = util.findMember("plasmus_crab_02", ASSET_CAST)
  PLASMUS_CRAB_02D = util.findMember("plasmus_crab_02d", ASSET_CAST)
  PLASMUS_CRAB_03 = util.findMember("plasmus_crab_03", ASSET_CAST)
  PLASMUS_CRAB_03D = util.findMember("plasmus_crab_03d", ASSET_CAST)
  PLASMUS_CRAB_04 = util.findMember("plasmus_crab_04", ASSET_CAST)
  PLASMUS_CRAB_04D = util.findMember("plasmus_crab_04d", ASSET_CAST)
  PLASMUS_CRAB_05 = util.findMember("plasmus_crab_05", ASSET_CAST)
  PLASMUS_CRAB_05D = util.findMember("plasmus_crab_05d", ASSET_CAST)
  PLASMUS_CRAB_06 = util.findMember("plasmus_crab_06", ASSET_CAST)
  PLASMUS_CRAB_06A = util.findMember("plasmus_crab_06a", ASSET_CAST)
  PLASMUS_CRAB_06D = util.findMember("plasmus_crab_06d", ASSET_CAST)
  PLASMUS_CRAB_MELT_01 = util.findMember("plasmus_crab_melt_01", ASSET_CAST)
  PLASMUS_CRAB_MELT_02 = util.findMember("plasmus_crab_melt_02", ASSET_CAST)
  PLASMUS_CRAB_MELT_03 = util.findMember("plasmus_crab_melt_03", ASSET_CAST)
  PLASMUS_CRAB_MELT_04 = util.findMember("plasmus_crab_melt_04", ASSET_CAST)
  PLASMUS_CRAB_MELT_05 = util.findMember("plasmus_crab_melt_05", ASSET_CAST)
  PLASMUS_CRAB_MELT_06 = util.findMember("plasmus_crab_melt_06", ASSET_CAST)
  PLASMUS_CRAB_MELT_07 = util.findMember("plasmus_crab_melt_07", ASSET_CAST)
  PLASMUS_CRAB_MELT_08 = util.findMember("plasmus_crab_melt_08", ASSET_CAST)
  PLASMUS_CRAB_MELT_09 = util.findMember("plasmus_crab_melt_09", ASSET_CAST)
  PLASMUS_CRAB_MELT_10 = util.findMember("plasmus_crab_melt_10", ASSET_CAST)
  PLASMUS_CRAB_MELT_11 = util.findMember("plasmus_crab_melt_11", ASSET_CAST)
  PLASMUS_CRAB_MELT_12 = util.findMember("plasmus_crab_melt_12", ASSET_CAST)
  PLASMUS_CRAB_MELT_13 = util.findMember("plasmus_crab_melt_13", ASSET_CAST)
  PLASMUS_DEFEAT_01 = util.findMember("plasmus_defeat_01", ASSET_CAST)
  PLASMUS_DEFEAT_01D = util.findMember("plasmus_defeat_01d", ASSET_CAST)
  PLASMUS_DEFEAT_02 = util.findMember("plasmus_defeat_02", ASSET_CAST)
  PLASMUS_DEFEAT_02D = util.findMember("plasmus_defeat_02d", ASSET_CAST)
  PLASMUS_DEFEAT_03 = util.findMember("plasmus_defeat_03", ASSET_CAST)
  PLASMUS_DEFEAT_03D = util.findMember("plasmus_defeat_03d", ASSET_CAST)
  PLASMUS_FIST_CLENCH_01 = util.findMember("plasmus_fist_clench_01", ASSET_CAST)
  PLASMUS_FIST_CLENCH_02 = util.findMember("plasmus_fist_clench_02", ASSET_CAST)
  PLASMUS_FIST_CLENCH_03 = util.findMember("plasmus_fist_clench_03", ASSET_CAST)
  PLASMUS_GLOBULE_01 = util.findMember("plasmus_globule_01", ASSET_CAST)
  PLASMUS_GLOBULE_01A = util.findMember("plasmus_globule_01a", ASSET_CAST)
  PLASMUS_GLOBULE_02 = util.findMember("plasmus_globule_02", ASSET_CAST)
  PLASMUS_GLOBULE_02A = util.findMember("plasmus_globule_02a", ASSET_CAST)
  PLASMUS_GLOBULE_03 = util.findMember("plasmus_globule_03", ASSET_CAST)
  PLASMUS_GLOBULE_03A = util.findMember("plasmus_globule_03a", ASSET_CAST)
  PLASMUS_GLOBULE_04 = util.findMember("plasmus_globule_04", ASSET_CAST)
  PLASMUS_GLOBULE_05 = util.findMember("plasmus_globule_05", ASSET_CAST)
  PLASMUS_HIT_01 = util.findMember("plasmus_hit_01", ASSET_CAST)
  PLASMUS_HIT_01D = util.findMember("plasmus_hit_01d", ASSET_CAST)
  PLASMUS_HIT_SPLATTER_01 = util.findMember("plasmus_hit_splatter_01", ASSET_CAST)
  PLASMUS_PUNCH_01 = util.findMember("plasmus_punch_01", ASSET_CAST)
  PLASMUS_PUNCH_01D = util.findMember("plasmus_punch_01d", ASSET_CAST)
  PLASMUS_PUNCH_02 = util.findMember("plasmus_punch_02", ASSET_CAST)
  PLASMUS_PUNCH_02_ARM1 = util.findMember("plasmus_punch_02_arm1", ASSET_CAST)
  PLASMUS_PUNCH_02_ARM2 = util.findMember("plasmus_punch_02_arm2", ASSET_CAST)
  PLASMUS_PUNCH_02A = util.findMember("plasmus_punch_02a", ASSET_CAST)
  PLASMUS_PUNCH_02D = util.findMember("plasmus_punch_02d", ASSET_CAST)
  PLASMUS_PUNCH_03 = util.findMember("plasmus_punch_03", ASSET_CAST)
  PLASMUS_PUNCH_03D = util.findMember("plasmus_punch_03d", ASSET_CAST)
  PLASMUS_SLUDGE_01 = util.findMember("plasmus_sludge_01", ASSET_CAST)
  PLASMUS_SLUDGE_01A = util.findMember("plasmus_sludge_01a", ASSET_CAST)
  PLASMUS_SLUDGE_02 = util.findMember("plasmus_sludge_02", ASSET_CAST)
  PLASMUS_SLUDGE_03 = util.findMember("plasmus_sludge_03", ASSET_CAST)
  PLASMUS_SLUDGE_04 = util.findMember("plasmus_sludge_04", ASSET_CAST)
  PLASMUS_SLUDGE_05 = util.findMember("plasmus_sludge_05", ASSET_CAST)
  PLASMUS_SLUDGE_06 = util.findMember("plasmus_sludge_06", ASSET_CAST)
  PLASMUS_SLUDGE_07 = util.findMember("plasmus_sludge_07", ASSET_CAST)
  PLASMUS_SLUDGE_08 = util.findMember("plasmus_sludge_08", ASSET_CAST)
  PLASMUS_SLUDGE_09 = util.findMember("plasmus_sludge_09", ASSET_CAST)
  PLASMUS_SLUDGE_10 = util.findMember("plasmus_sludge_10", ASSET_CAST)
  PLASMUS_SLUDGE_11 = util.findMember("plasmus_sludge_11", ASSET_CAST)
  PLASMUS_SLUDGE_12 = util.findMember("plasmus_sludge_12", ASSET_CAST)
  PLASMUS_SLUDGE_13 = util.findMember("plasmus_sludge_13", ASSET_CAST)
  PLASMUS_SLUDGE_14 = util.findMember("plasmus_sludge_14", ASSET_CAST)
  PLASMUS_SLUDGE_15 = util.findMember("plasmus_sludge_15", ASSET_CAST)
  PLASMUS_SLUDGE_16 = util.findMember("plasmus_sludge_16", ASSET_CAST)
  PLASMUS_SPLATTER_01 = util.findMember("plasmus_splatter_01", ASSET_CAST)
  PLASMUS_SPLATTER_02 = util.findMember("plasmus_splatter_02", ASSET_CAST)
  PLASMUS_SPLATTER_03 = util.findMember("plasmus_splatter_03", ASSET_CAST)
  PLASMUS_SPLATTER_04 = util.findMember("plasmus_splatter_04", ASSET_CAST)
  PLASMUS_SPLATTER_05 = util.findMember("plasmus_splatter_05", ASSET_CAST)
  PLASMUS_SPLATTER_06 = util.findMember("plasmus_splatter_06", ASSET_CAST)
  PLASMUS_STAND_01D = util.findMember("plasmus_stand_01d", ASSET_CAST)
  PLASMUS_TOSS_01 = util.findMember("plasmus_toss_01", ASSET_CAST)
  PLASMUS_TOSS_01D = util.findMember("plasmus_toss_01d", ASSET_CAST)
  PLASMUS_TOSS_02 = util.findMember("plasmus_toss_02", ASSET_CAST)
  PLASMUS_TOSS_02D = util.findMember("plasmus_toss_02d", ASSET_CAST)
  PLASMUS_TOSS_03 = util.findMember("plasmus_toss_03", ASSET_CAST)
  PLASMUS_TOSS_03D = util.findMember("plasmus_toss_03d", ASSET_CAST)
  PLASMUS_TOSS_04 = util.findMember("plasmus_toss_04", ASSET_CAST)
  PLASMUS_TOSS_04D = util.findMember("plasmus_toss_04d", ASSET_CAST)
  PLASMUS_TOSS_05 = util.findMember("plasmus_toss_05", ASSET_CAST)
  PLASMUS_TOSS_05D = util.findMember("plasmus_toss_05d", ASSET_CAST)
  PLASMUS_TOSS_06 = util.findMember("plasmus_toss_06", ASSET_CAST)
  PLASMUS_TOSS_06D = util.findMember("plasmus_toss_06d", ASSET_CAST)
  PLASMUS_WALK_01 = util.findMember("plasmus_walk_01", ASSET_CAST)
  PLASMUS_WALK_02 = util.findMember("plasmus_walk_02", ASSET_CAST)
  PLASMUS_WALK_03 = util.findMember("plasmus_walk_03", ASSET_CAST)
  PLASMUS_WALK_04 = util.findMember("plasmus_walk_04", ASSET_CAST)
  PLASMUS_WALK_05 = util.findMember("plasmus_walk_05", ASSET_CAST)
  PLASMUS_WALK_06 = util.findMember("plasmus_walk_06", ASSET_CAST)
  SFX_PLASMUS_AMBIENTLOOPSCARIER = util.findMember("sfx_plasmus_ambientloopscarier", ASSET_CAST)
  SFX_PLASMUS_CRABBITE = util.findMember("sfx_plasmus_crabbite", ASSET_CAST)
  SFX_PLASMUS_CRABHIT = util.findMember("sfx_plasmus_crabhit", ASSET_CAST)
  SFX_PLASMUS_CRABMISS = util.findMember("sfx_plasmus_crabmiss", ASSET_CAST)
  SFX_PLASMUS_CRABTHROW = util.findMember("sfx_plasmus_crabthrow", ASSET_CAST)
  SFX_PLASMUS_CRABWALK = util.findMember("sfx_plasmus_crabwalk", ASSET_CAST)
  SFX_PLASMUS_GLOBULEHIT = util.findMember("sfx_plasmus_globulehit", ASSET_CAST)
  SFX_PLASMUS_GLOBULEMISS = util.findMember("sfx_plasmus_globulemiss", ASSET_CAST)
  SFX_PLASMUS_GLOBULETHROW = util.findMember("sfx_plasmus_globulethrow", ASSET_CAST)
  SFX_PLASMUS_GLOBULEWOOSH = util.findMember("sfx_plasmus_globulewoosh", ASSET_CAST)
  SFX_PLASMUS_PUNCH_HIT = util.findMember("sfx_plasmus_punch_hit", ASSET_CAST)
  SFX_PLASMUS_ROAR_BIG = util.findMember("sfx_plasmus_roar_big", ASSET_CAST)
  SFX_PLASMUS_ROAR_SMALL = util.findMember("sfx_plasmus_roar_small", ASSET_CAST)
  SFX_PLASMUS_SHAMBLE = util.findMember("sfx_plasmus_shamble", ASSET_CAST)
  SFX_PLASMUS_SLUDGE_THROW = util.findMember("sfx_plasmus_sludge_throw", ASSET_CAST)
  SFX_PLASMUS_STRETCH_1 = util.findMember("sfx_plasmus_stretch_1", ASSET_CAST)
  SFX_PLASMUS_STRETCH_2 = util.findMember("sfx_plasmus_stretch_2", ASSET_CAST)
  SFX_PLASMUS_STRETCHMISS = util.findMember("sfx_plasmus_stretchmiss", ASSET_CAST)
  SFX_PLASMUS_TRANSFORM = util.findMember("sfx_plasmus_transform", ASSET_CAST)
end

on precache me
  preloadMember(FX_PLASMUS_BLOWUP_01)
  preloadMember(FX_PLASMUS_BLOWUP_02)
  preloadMember(FX_PLASMUS_BLOWUP_03)
  preloadMember(FX_PLASMUS_BLOWUP_04)
  preloadMember(FX_PLASMUS_BLOWUP_05)
  preloadMember(FX_PLASMUS_BLOWUP_06)
  preloadMember(PLASMUS_ARMSWIPE_01)
  preloadMember(PLASMUS_ARMSWIPE_01D)
  preloadMember(PLASMUS_ARMSWIPE_02)
  preloadMember(PLASMUS_ARMSWIPE_02D)
  preloadMember(PLASMUS_ARMSWIPE_03)
  preloadMember(PLASMUS_ARMSWIPE_03_ARM1)
  preloadMember(PLASMUS_ARMSWIPE_03_ARM2)
  preloadMember(PLASMUS_ARMSWIPE_03A)
  preloadMember(PLASMUS_ARMSWIPE_03D)
  preloadMember(PLASMUS_ARMSWIPE_04)
  preloadMember(PLASMUS_ARMSWIPE_04D)
  preloadMember(PLASMUS_BACKGROUND)
  preloadMember(PLASMUS_BLOCK_01)
  preloadMember(PLASMUS_BLOCK_01D)
  preloadMember(PLASMUS_CHEST_BLAST_01)
  preloadMember(PLASMUS_CHEST_BLAST_01D)
  preloadMember(PLASMUS_CHEST_BLAST_02)
  preloadMember(PLASMUS_CHEST_BLAST_02D)
  preloadMember(PLASMUS_CHEST_BLAST_03)
  preloadMember(PLASMUS_CHEST_BLAST_03D)
  preloadMember(PLASMUS_CHEST_BLAST_04)
  preloadMember(PLASMUS_CHEST_BLAST_04D)
  preloadMember(PLASMUS_CHEST_BLAST_05)
  preloadMember(PLASMUS_CHEST_BLAST_05D)
  preloadMember(PLASMUS_CRAB_01)
  preloadMember(PLASMUS_CRAB_01D)
  preloadMember(PLASMUS_CRAB_02)
  preloadMember(PLASMUS_CRAB_02D)
  preloadMember(PLASMUS_CRAB_03)
  preloadMember(PLASMUS_CRAB_03D)
  preloadMember(PLASMUS_CRAB_04)
  preloadMember(PLASMUS_CRAB_04D)
  preloadMember(PLASMUS_CRAB_05)
  preloadMember(PLASMUS_CRAB_05D)
  preloadMember(PLASMUS_CRAB_06)
  preloadMember(PLASMUS_CRAB_06A)
  preloadMember(PLASMUS_CRAB_06D)
  preloadMember(PLASMUS_CRAB_MELT_01)
  preloadMember(PLASMUS_CRAB_MELT_02)
  preloadMember(PLASMUS_CRAB_MELT_03)
  preloadMember(PLASMUS_CRAB_MELT_04)
  preloadMember(PLASMUS_CRAB_MELT_05)
  preloadMember(PLASMUS_CRAB_MELT_06)
  preloadMember(PLASMUS_CRAB_MELT_07)
  preloadMember(PLASMUS_CRAB_MELT_08)
  preloadMember(PLASMUS_CRAB_MELT_09)
  preloadMember(PLASMUS_CRAB_MELT_10)
  preloadMember(PLASMUS_CRAB_MELT_11)
  preloadMember(PLASMUS_CRAB_MELT_12)
  preloadMember(PLASMUS_CRAB_MELT_13)
  preloadMember(PLASMUS_DEFEAT_01)
  preloadMember(PLASMUS_DEFEAT_01D)
  preloadMember(PLASMUS_DEFEAT_02)
  preloadMember(PLASMUS_DEFEAT_02D)
  preloadMember(PLASMUS_DEFEAT_03)
  preloadMember(PLASMUS_DEFEAT_03D)
  preloadMember(PLASMUS_FIST_CLENCH_01)
  preloadMember(PLASMUS_FIST_CLENCH_02)
  preloadMember(PLASMUS_FIST_CLENCH_03)
  preloadMember(PLASMUS_GLOBULE_01)
  preloadMember(PLASMUS_GLOBULE_01A)
  preloadMember(PLASMUS_GLOBULE_02)
  preloadMember(PLASMUS_GLOBULE_02A)
  preloadMember(PLASMUS_GLOBULE_03)
  preloadMember(PLASMUS_GLOBULE_03A)
  preloadMember(PLASMUS_GLOBULE_04)
  preloadMember(PLASMUS_GLOBULE_05)
  preloadMember(PLASMUS_HIT_01)
  preloadMember(PLASMUS_HIT_01D)
  preloadMember(PLASMUS_HIT_SPLATTER_01)
  preloadMember(PLASMUS_PUNCH_01)
  preloadMember(PLASMUS_PUNCH_01D)
  preloadMember(PLASMUS_PUNCH_02)
  preloadMember(PLASMUS_PUNCH_02_ARM1)
  preloadMember(PLASMUS_PUNCH_02_ARM2)
  preloadMember(PLASMUS_PUNCH_02A)
  preloadMember(PLASMUS_PUNCH_02D)
  preloadMember(PLASMUS_PUNCH_03)
  preloadMember(PLASMUS_PUNCH_03D)
  preloadMember(PLASMUS_SLUDGE_01)
  preloadMember(PLASMUS_SLUDGE_01A)
  preloadMember(PLASMUS_SLUDGE_02)
  preloadMember(PLASMUS_SLUDGE_03)
  preloadMember(PLASMUS_SLUDGE_04)
  preloadMember(PLASMUS_SLUDGE_05)
  preloadMember(PLASMUS_SLUDGE_06)
  preloadMember(PLASMUS_SLUDGE_07)
  preloadMember(PLASMUS_SLUDGE_08)
  preloadMember(PLASMUS_SLUDGE_09)
  preloadMember(PLASMUS_SLUDGE_10)
  preloadMember(PLASMUS_SLUDGE_11)
  preloadMember(PLASMUS_SLUDGE_12)
  preloadMember(PLASMUS_SLUDGE_13)
  preloadMember(PLASMUS_SLUDGE_14)
  preloadMember(PLASMUS_SLUDGE_15)
  preloadMember(PLASMUS_SLUDGE_16)
  preloadMember(PLASMUS_SPLATTER_01)
  preloadMember(PLASMUS_SPLATTER_02)
  preloadMember(PLASMUS_SPLATTER_03)
  preloadMember(PLASMUS_SPLATTER_04)
  preloadMember(PLASMUS_SPLATTER_05)
  preloadMember(PLASMUS_SPLATTER_06)
  preloadMember(PLASMUS_STAND_01D)
  preloadMember(PLASMUS_TOSS_01)
  preloadMember(PLASMUS_TOSS_01D)
  preloadMember(PLASMUS_TOSS_02)
  preloadMember(PLASMUS_TOSS_02D)
  preloadMember(PLASMUS_TOSS_03)
  preloadMember(PLASMUS_TOSS_03D)
  preloadMember(PLASMUS_TOSS_04)
  preloadMember(PLASMUS_TOSS_04D)
  preloadMember(PLASMUS_TOSS_05)
  preloadMember(PLASMUS_TOSS_05D)
  preloadMember(PLASMUS_TOSS_06)
  preloadMember(PLASMUS_TOSS_06D)
  preloadMember(PLASMUS_WALK_01)
  preloadMember(PLASMUS_WALK_02)
  preloadMember(PLASMUS_WALK_03)
  preloadMember(PLASMUS_WALK_04)
  preloadMember(PLASMUS_WALK_05)
  preloadMember(PLASMUS_WALK_06)
  preloadMember(SFX_PLASMUS_AMBIENTLOOPSCARIER)
  preloadMember(SFX_PLASMUS_CRABBITE)
  preloadMember(SFX_PLASMUS_CRABHIT)
  preloadMember(SFX_PLASMUS_CRABMISS)
  preloadMember(SFX_PLASMUS_CRABTHROW)
  preloadMember(SFX_PLASMUS_CRABWALK)
  preloadMember(SFX_PLASMUS_GLOBULEHIT)
  preloadMember(SFX_PLASMUS_GLOBULEMISS)
  preloadMember(SFX_PLASMUS_GLOBULETHROW)
  preloadMember(SFX_PLASMUS_GLOBULEWOOSH)
  preloadMember(SFX_PLASMUS_PUNCH_HIT)
  preloadMember(SFX_PLASMUS_ROAR_BIG)
  preloadMember(SFX_PLASMUS_ROAR_SMALL)
  preloadMember(SFX_PLASMUS_SHAMBLE)
  preloadMember(SFX_PLASMUS_SLUDGE_THROW)
  preloadMember(SFX_PLASMUS_STRETCH_1)
  preloadMember(SFX_PLASMUS_STRETCH_2)
  preloadMember(SFX_PLASMUS_STRETCHMISS)
  preloadMember(SFX_PLASMUS_TRANSFORM)
end
