property FX_EXPLODE_01, FX_EXPLODE_02, FX_EXPLODE_03, FX_EXPLODE_04, FX_EXPLODE_05, FX_EXPLODE_06, FX_EXPLODE_07, FX_EXPLODE_08, FX_EXPLODE_09, FX_EXPLODE_10, FX_EXPLODE_11, FX_EXPLODE_12, FX_EXPLODE_13, FX_GIZMO_CANNON_BLAST_01, FX_GIZMO_CANNON_BLAST_02, FX_GIZMO_CANNON_BLAST_03, FX_GIZMO_CANNON_BLAST_04, FX_GIZMO_CANNON_SHOT_01, FX_GIZMO_CANNON_SHOT_01A, FX_GIZMO_CANNON_SHOT_02, FX_GIZMO_CANNON_SHOT_03, FX_GIZMO_CANNON_SHOT_04, FX_GIZMO_CANNON_SHOT_05, FX_GIZMO_CANNON_SHOT_06, FX_GIZMO_ELECTRO_PUNCH_01, FX_GIZMO_ELECTRO_PUNCH_02, FX_GIZMO_ELECTRO_PUNCH_03, FX_GIZMO_ELECTRO_PUNCH_04, FX_GIZMO_ELECTRO_PUNCH_05, FX_GIZMO_ELECTRO_PUNCH_06, FX_GIZMO_ELECTRO_PUNCH_07, fx_gizmo_electro_punch_08, GIZMO_AIRBORNE_FALL_01, GIZMO_AIRBORNE_FALL_01D, GIZMO_AIRBORNE_FALL_02, GIZMO_AIRBORNE_FALL_02D, GIZMO_AIRBORNE_HIT_01, GIZMO_AIRBORNE_HIT_01D, GIZMO_BACKGROUND, GIZMO_ELECTRO_PUNCH_01, GIZMO_ELECTRO_PUNCH_02, GIZMO_ELECTRO_PUNCH_03, GIZMO_ELECTRO_PUNCH_03A, GIZMO_FALL_01, GIZMO_FALL_01D, GIZMO_FALL_02, GIZMO_FALL_02D, GIZMO_HIT_01, GIZMO_HIT_01D, GIZMO_HOVER_01, GIZMO_HOVER_01D, GIZMO_LAND_01, GIZMO_LAND_01D, GIZMO_LAND_02, GIZMO_LAND_02D, GIZMO_LAND_03, GIZMO_LAND_03D, GIZMO_MACHINEGUN_01, GIZMO_MACHINEGUN_02, GIZMO_MACHINEGUN_03, GIZMO_MACHINEGUN_04, GIZMO_MACHINEGUN_05, GIZMO_MACHINEGUN_06, GIZMO_MACHINEGUN_07, GIZMO_MACHINEGUN_08, GIZMO_MISSILE_PROJECTILE_01A, GIZMO_MISSILE01_00, GIZMO_MISSILE01_01, GIZMO_MISSILE01_02, GIZMO_MISSILE01_03, GIZMO_MISSILE01_04, GIZMO_MISSILE01_05, GIZMO_MISSILE01_06, GIZMO_MISSILE01_07, GIZMO_MISSILE01_08, GIZMO_MISSILE01_09, GIZMO_MISSILE01_10, GIZMO_MISSILE01_11, GIZMO_MISSILE01_12, GIZMO_MISSILE01_13, GIZMO_MISSILE01_14, GIZMO_MISSILE01_15, GIZMO_MISSILE01_16, GIZMO_MISSILE01_17, GIZMO_MISSILE01_18, GIZMO_MISSILE01_19, GIZMO_MISSILE01_20, GIZMO_MISSILE01_21, GIZMO_MISSILE01_22, GIZMO_MISSILE02_00, GIZMO_MISSILE02_01, GIZMO_MISSILE02_02, GIZMO_MISSILE02_03, GIZMO_MISSILE02_04, GIZMO_MISSILE02_05, GIZMO_MISSILE02_06, GIZMO_MISSILE02_07, GIZMO_MISSILE02_08, GIZMO_MISSILE02_09, GIZMO_MISSILE02_10, GIZMO_MISSILE02_11, GIZMO_MISSILE02_12, GIZMO_MISSILE02_13, GIZMO_MISSILE02_14, GIZMO_STAND_01, GIZMO_STAND_01D, GIZMO_TAKEOFF_01, GIZMO_TAKEOFF_01D, GIZMO_TAKEOFF_02, GIZMO_TAKEOFF_02D, GIZMO_TAKEOFF_03, GIZMO_TAKEOFF_03D, GIZMO_TAKEOFF_04, GIZMO_TAKEOFF_04D, GIZMO_TAKEOFF_05, GIZMO_TAKEOFF_05D, GIZMO_TAKEOFF_06, GIZMO_TAKEOFF_06D, GIZMO_TAKEOFF_07, GIZMO_TAKEOFF_07D, GIZMO_TAKEOFF_08, GIZMO_TAKEOFF_08D, GIZMO_TAKEOFF_09, GIZMO_TAKEOFF_09D, GIZMO_TAKEOFF_10, GIZMO_TAKEOFF_10D, GIZMO_TAKEOFF_11, GIZMO_TAKEOFF_11D, GIZMO_WALK_01, GIZMO_WALK_02, GIZMO_WALK_03, GIZMO_WALK_04, GIZMO_WALK_05, GIZMO_WALK_06, SFX_GIZMO_AMBIENTBACKGROUNDLOOP, SFX_GIZMO_BACKPACKCANNONEMERGING, SFX_GIZMO_BACKPACKCANNONEMERGING3, SFX_GIZMO_BACKPACKCANNONSHOOTING, SFX_GIZMO_CANNONHIT, SFX_GIZMO_CANNONMISS, SFX_GIZMO_FLY, sfx_gizmo_fly2, SFX_GIZMO_MISSILEFIRE, SFX_GIZMO_MISSILEHIT, SFX_GIZMO_MISSILEINFLIGHT, SFX_GIZMO_WINGSFOLDIN, SFX_GIZMO_WINGSUNFURL

on new me
  me.locateMembers()
  return me
end

on locateMembers me
  util = new(script("Class_Utility"))
  ASSET_CAST = "char_Gizmo"
  FX_EXPLODE_01 = util.findMember("fx_explode_01", ASSET_CAST)
  FX_EXPLODE_02 = util.findMember("fx_explode_02", ASSET_CAST)
  FX_EXPLODE_03 = util.findMember("fx_explode_03", ASSET_CAST)
  FX_EXPLODE_04 = util.findMember("fx_explode_04", ASSET_CAST)
  FX_EXPLODE_05 = util.findMember("fx_explode_05", ASSET_CAST)
  FX_EXPLODE_06 = util.findMember("fx_explode_06", ASSET_CAST)
  FX_EXPLODE_07 = util.findMember("fx_explode_07", ASSET_CAST)
  FX_EXPLODE_08 = util.findMember("fx_explode_08", ASSET_CAST)
  FX_EXPLODE_09 = util.findMember("fx_explode_09", ASSET_CAST)
  FX_EXPLODE_10 = util.findMember("fx_explode_10", ASSET_CAST)
  FX_EXPLODE_11 = util.findMember("fx_explode_11", ASSET_CAST)
  FX_EXPLODE_12 = util.findMember("fx_explode_12", ASSET_CAST)
  FX_EXPLODE_13 = util.findMember("fx_explode_13", ASSET_CAST)
  FX_GIZMO_CANNON_BLAST_01 = util.findMember("fx_gizmo_cannon_blast_01", ASSET_CAST)
  FX_GIZMO_CANNON_BLAST_02 = util.findMember("fx_gizmo_cannon_blast_02", ASSET_CAST)
  FX_GIZMO_CANNON_BLAST_03 = util.findMember("fx_gizmo_cannon_blast_03", ASSET_CAST)
  FX_GIZMO_CANNON_BLAST_04 = util.findMember("fx_gizmo_cannon_blast_04", ASSET_CAST)
  FX_GIZMO_CANNON_SHOT_01 = util.findMember("fx_gizmo_cannon_shot_01", ASSET_CAST)
  FX_GIZMO_CANNON_SHOT_01A = util.findMember("fx_gizmo_cannon_shot_01a", ASSET_CAST)
  FX_GIZMO_CANNON_SHOT_02 = util.findMember("fx_gizmo_cannon_shot_02", ASSET_CAST)
  FX_GIZMO_CANNON_SHOT_03 = util.findMember("fx_gizmo_cannon_shot_03", ASSET_CAST)
  FX_GIZMO_CANNON_SHOT_04 = util.findMember("fx_gizmo_cannon_shot_04", ASSET_CAST)
  FX_GIZMO_CANNON_SHOT_05 = util.findMember("fx_gizmo_cannon_shot_05", ASSET_CAST)
  FX_GIZMO_CANNON_SHOT_06 = util.findMember("fx_gizmo_cannon_shot_06", ASSET_CAST)
  FX_GIZMO_ELECTRO_PUNCH_01 = util.findMember("fx_gizmo_electro_punch_01", ASSET_CAST)
  FX_GIZMO_ELECTRO_PUNCH_02 = util.findMember("fx_gizmo_electro_punch_02", ASSET_CAST)
  FX_GIZMO_ELECTRO_PUNCH_03 = util.findMember("fx_gizmo_electro_punch_03", ASSET_CAST)
  FX_GIZMO_ELECTRO_PUNCH_04 = util.findMember("fx_gizmo_electro_punch_04", ASSET_CAST)
  FX_GIZMO_ELECTRO_PUNCH_05 = util.findMember("fx_gizmo_electro_punch_05", ASSET_CAST)
  FX_GIZMO_ELECTRO_PUNCH_06 = util.findMember("fx_gizmo_electro_punch_06", ASSET_CAST)
  FX_GIZMO_ELECTRO_PUNCH_07 = util.findMember("fx_gizmo_electro_punch_07", ASSET_CAST)
  fx_gizmo_electro_punch_08 = util.findMember("fx_gizmo_electro_punch_08", ASSET_CAST)
  GIZMO_AIRBORNE_FALL_01 = util.findMember("gizmo_airborne_fall_01", ASSET_CAST)
  GIZMO_AIRBORNE_FALL_01D = util.findMember("gizmo_airborne_fall_01d", ASSET_CAST)
  GIZMO_AIRBORNE_FALL_02 = util.findMember("gizmo_airborne_fall_02", ASSET_CAST)
  GIZMO_AIRBORNE_FALL_02D = util.findMember("gizmo_airborne_fall_02d", ASSET_CAST)
  GIZMO_AIRBORNE_HIT_01 = util.findMember("gizmo_airborne_hit_01", ASSET_CAST)
  GIZMO_AIRBORNE_HIT_01D = util.findMember("gizmo_airborne_hit_01d", ASSET_CAST)
  GIZMO_BACKGROUND = util.findMember("gizmo_background", ASSET_CAST)
  GIZMO_ELECTRO_PUNCH_01 = util.findMember("gizmo_electro_punch_01", ASSET_CAST)
  GIZMO_ELECTRO_PUNCH_02 = util.findMember("gizmo_electro_punch_02", ASSET_CAST)
  GIZMO_ELECTRO_PUNCH_03 = util.findMember("gizmo_electro_punch_03", ASSET_CAST)
  GIZMO_ELECTRO_PUNCH_03A = util.findMember("gizmo_electro_punch_03a", ASSET_CAST)
  GIZMO_FALL_01 = util.findMember("gizmo_fall_01", ASSET_CAST)
  GIZMO_FALL_01D = util.findMember("gizmo_fall_01d", ASSET_CAST)
  GIZMO_FALL_02 = util.findMember("gizmo_fall_02", ASSET_CAST)
  GIZMO_FALL_02D = util.findMember("gizmo_fall_02d", ASSET_CAST)
  GIZMO_HIT_01 = util.findMember("gizmo_hit_01", ASSET_CAST)
  GIZMO_HIT_01D = util.findMember("gizmo_hit_01d", ASSET_CAST)
  GIZMO_HOVER_01 = util.findMember("gizmo_hover_01", ASSET_CAST)
  GIZMO_HOVER_01D = util.findMember("gizmo_hover_01d", ASSET_CAST)
  GIZMO_LAND_01 = util.findMember("gizmo_land_01", ASSET_CAST)
  GIZMO_LAND_01D = util.findMember("gizmo_land_01d", ASSET_CAST)
  GIZMO_LAND_02 = util.findMember("gizmo_land_02", ASSET_CAST)
  GIZMO_LAND_02D = util.findMember("gizmo_land_02d", ASSET_CAST)
  GIZMO_LAND_03 = util.findMember("gizmo_land_03", ASSET_CAST)
  GIZMO_LAND_03D = util.findMember("gizmo_land_03d", ASSET_CAST)
  GIZMO_MACHINEGUN_01 = util.findMember("gizmo_machinegun_01", ASSET_CAST)
  GIZMO_MACHINEGUN_02 = util.findMember("gizmo_machinegun_02", ASSET_CAST)
  GIZMO_MACHINEGUN_03 = util.findMember("gizmo_machinegun_03", ASSET_CAST)
  GIZMO_MACHINEGUN_04 = util.findMember("gizmo_machinegun_04", ASSET_CAST)
  GIZMO_MACHINEGUN_05 = util.findMember("gizmo_machinegun_05", ASSET_CAST)
  GIZMO_MACHINEGUN_06 = util.findMember("gizmo_machinegun_06", ASSET_CAST)
  GIZMO_MACHINEGUN_07 = util.findMember("gizmo_machinegun_07", ASSET_CAST)
  GIZMO_MACHINEGUN_08 = util.findMember("gizmo_machinegun_08", ASSET_CAST)
  GIZMO_MISSILE_PROJECTILE_01A = util.findMember("gizmo_missile_projectile_01a", ASSET_CAST)
  GIZMO_MISSILE01_00 = util.findMember("gizmo_missile01_00", ASSET_CAST)
  GIZMO_MISSILE01_01 = util.findMember("gizmo_missile01_01", ASSET_CAST)
  GIZMO_MISSILE01_02 = util.findMember("gizmo_missile01_02", ASSET_CAST)
  GIZMO_MISSILE01_03 = util.findMember("gizmo_missile01_03", ASSET_CAST)
  GIZMO_MISSILE01_04 = util.findMember("gizmo_missile01_04", ASSET_CAST)
  GIZMO_MISSILE01_05 = util.findMember("gizmo_missile01_05", ASSET_CAST)
  GIZMO_MISSILE01_06 = util.findMember("gizmo_missile01_06", ASSET_CAST)
  GIZMO_MISSILE01_07 = util.findMember("gizmo_missile01_07", ASSET_CAST)
  GIZMO_MISSILE01_08 = util.findMember("gizmo_missile01_08", ASSET_CAST)
  GIZMO_MISSILE01_09 = util.findMember("gizmo_missile01_09", ASSET_CAST)
  GIZMO_MISSILE01_10 = util.findMember("gizmo_missile01_10", ASSET_CAST)
  GIZMO_MISSILE01_11 = util.findMember("gizmo_missile01_11", ASSET_CAST)
  GIZMO_MISSILE01_12 = util.findMember("gizmo_missile01_12", ASSET_CAST)
  GIZMO_MISSILE01_13 = util.findMember("gizmo_missile01_13", ASSET_CAST)
  GIZMO_MISSILE01_14 = util.findMember("gizmo_missile01_14", ASSET_CAST)
  GIZMO_MISSILE01_15 = util.findMember("gizmo_missile01_15", ASSET_CAST)
  GIZMO_MISSILE01_16 = util.findMember("gizmo_missile01_16", ASSET_CAST)
  GIZMO_MISSILE01_17 = util.findMember("gizmo_missile01_17", ASSET_CAST)
  GIZMO_MISSILE01_18 = util.findMember("gizmo_missile01_18", ASSET_CAST)
  GIZMO_MISSILE01_19 = util.findMember("gizmo_missile01_19", ASSET_CAST)
  GIZMO_MISSILE01_20 = util.findMember("gizmo_missile01_20", ASSET_CAST)
  GIZMO_MISSILE01_21 = util.findMember("gizmo_missile01_21", ASSET_CAST)
  GIZMO_MISSILE01_22 = util.findMember("gizmo_missile01_22", ASSET_CAST)
  GIZMO_MISSILE02_00 = util.findMember("gizmo_missile02_00", ASSET_CAST)
  GIZMO_MISSILE02_01 = util.findMember("gizmo_missile02_01", ASSET_CAST)
  GIZMO_MISSILE02_02 = util.findMember("gizmo_missile02_02", ASSET_CAST)
  GIZMO_MISSILE02_03 = util.findMember("gizmo_missile02_03", ASSET_CAST)
  GIZMO_MISSILE02_04 = util.findMember("gizmo_missile02_04", ASSET_CAST)
  GIZMO_MISSILE02_05 = util.findMember("gizmo_missile02_05", ASSET_CAST)
  GIZMO_MISSILE02_06 = util.findMember("gizmo_missile02_06", ASSET_CAST)
  GIZMO_MISSILE02_07 = util.findMember("gizmo_missile02_07", ASSET_CAST)
  GIZMO_MISSILE02_08 = util.findMember("gizmo_missile02_08", ASSET_CAST)
  GIZMO_MISSILE02_09 = util.findMember("gizmo_missile02_09", ASSET_CAST)
  GIZMO_MISSILE02_10 = util.findMember("gizmo_missile02_10", ASSET_CAST)
  GIZMO_MISSILE02_11 = util.findMember("gizmo_missile02_11", ASSET_CAST)
  GIZMO_MISSILE02_12 = util.findMember("gizmo_missile02_12", ASSET_CAST)
  GIZMO_MISSILE02_13 = util.findMember("gizmo_missile02_13", ASSET_CAST)
  GIZMO_MISSILE02_14 = util.findMember("gizmo_missile02_14", ASSET_CAST)
  GIZMO_STAND_01 = util.findMember("gizmo_stand_01", ASSET_CAST)
  GIZMO_STAND_01D = util.findMember("gizmo_stand_01d", ASSET_CAST)
  GIZMO_TAKEOFF_01 = util.findMember("gizmo_takeoff_01", ASSET_CAST)
  GIZMO_TAKEOFF_01D = util.findMember("gizmo_takeoff_01d", ASSET_CAST)
  GIZMO_TAKEOFF_02 = util.findMember("gizmo_takeoff_02", ASSET_CAST)
  GIZMO_TAKEOFF_02D = util.findMember("gizmo_takeoff_02d", ASSET_CAST)
  GIZMO_TAKEOFF_03 = util.findMember("gizmo_takeoff_03", ASSET_CAST)
  GIZMO_TAKEOFF_03D = util.findMember("gizmo_takeoff_03d", ASSET_CAST)
  GIZMO_TAKEOFF_04 = util.findMember("gizmo_takeoff_04", ASSET_CAST)
  GIZMO_TAKEOFF_04D = util.findMember("gizmo_takeoff_04d", ASSET_CAST)
  GIZMO_TAKEOFF_05 = util.findMember("gizmo_takeoff_05", ASSET_CAST)
  GIZMO_TAKEOFF_05D = util.findMember("gizmo_takeoff_05d", ASSET_CAST)
  GIZMO_TAKEOFF_06 = util.findMember("gizmo_takeoff_06", ASSET_CAST)
  GIZMO_TAKEOFF_06D = util.findMember("gizmo_takeoff_06d", ASSET_CAST)
  GIZMO_TAKEOFF_07 = util.findMember("gizmo_takeoff_07", ASSET_CAST)
  GIZMO_TAKEOFF_07D = util.findMember("gizmo_takeoff_07d", ASSET_CAST)
  GIZMO_TAKEOFF_08 = util.findMember("gizmo_takeoff_08", ASSET_CAST)
  GIZMO_TAKEOFF_08D = util.findMember("gizmo_takeoff_08d", ASSET_CAST)
  GIZMO_TAKEOFF_09 = util.findMember("gizmo_takeoff_09", ASSET_CAST)
  GIZMO_TAKEOFF_09D = util.findMember("gizmo_takeoff_09d", ASSET_CAST)
  GIZMO_TAKEOFF_10 = util.findMember("gizmo_takeoff_10", ASSET_CAST)
  GIZMO_TAKEOFF_10D = util.findMember("gizmo_takeoff_10d", ASSET_CAST)
  GIZMO_TAKEOFF_11 = util.findMember("gizmo_takeoff_11", ASSET_CAST)
  GIZMO_TAKEOFF_11D = util.findMember("gizmo_takeoff_11d", ASSET_CAST)
  GIZMO_WALK_01 = util.findMember("gizmo_walk_01", ASSET_CAST)
  GIZMO_WALK_02 = util.findMember("gizmo_walk_02", ASSET_CAST)
  GIZMO_WALK_03 = util.findMember("gizmo_walk_03", ASSET_CAST)
  GIZMO_WALK_04 = util.findMember("gizmo_walk_04", ASSET_CAST)
  GIZMO_WALK_05 = util.findMember("gizmo_walk_05", ASSET_CAST)
  GIZMO_WALK_06 = util.findMember("gizmo_walk_06", ASSET_CAST)
  SFX_GIZMO_AMBIENTBACKGROUNDLOOP = util.findMember("sfx_gizmo_ambientbackgroundloop", ASSET_CAST)
  SFX_GIZMO_BACKPACKCANNONEMERGING = util.findMember("sfx_gizmo_backpackcannonemerging", ASSET_CAST)
  SFX_GIZMO_BACKPACKCANNONEMERGING3 = util.findMember("sfx_gizmo_backpackcannonemerging3", ASSET_CAST)
  SFX_GIZMO_BACKPACKCANNONSHOOTING = util.findMember("sfx_gizmo_backpackcannonshooting", ASSET_CAST)
  SFX_GIZMO_CANNONHIT = util.findMember("sfx_gizmo_cannonhit", ASSET_CAST)
  SFX_GIZMO_CANNONMISS = util.findMember("sfx_gizmo_cannonmiss", ASSET_CAST)
  SFX_GIZMO_FLY = util.findMember("sfx_gizmo_fly", ASSET_CAST)
  sfx_gizmo_fly2 = util.findMember("sfx_gizmo_fly2", ASSET_CAST)
  SFX_GIZMO_MISSILEFIRE = util.findMember("sfx_gizmo_missilefire", ASSET_CAST)
  SFX_GIZMO_MISSILEHIT = util.findMember("sfx_gizmo_missilehit", ASSET_CAST)
  SFX_GIZMO_MISSILEINFLIGHT = util.findMember("sfx_gizmo_missileinflight", ASSET_CAST)
  SFX_GIZMO_WINGSFOLDIN = util.findMember("sfx_gizmo_wingsfoldin", ASSET_CAST)
  SFX_GIZMO_WINGSUNFURL = util.findMember("sfx_gizmo_wingsunfurl", ASSET_CAST)
end

on precache me
  preloadMember(FX_EXPLODE_01)
  preloadMember(FX_EXPLODE_02)
  preloadMember(FX_EXPLODE_03)
  preloadMember(FX_EXPLODE_04)
  preloadMember(FX_EXPLODE_05)
  preloadMember(FX_EXPLODE_06)
  preloadMember(FX_EXPLODE_07)
  preloadMember(FX_EXPLODE_08)
  preloadMember(FX_EXPLODE_09)
  preloadMember(FX_EXPLODE_10)
  preloadMember(FX_EXPLODE_11)
  preloadMember(FX_EXPLODE_12)
  preloadMember(FX_EXPLODE_13)
  preloadMember(FX_GIZMO_CANNON_BLAST_01)
  preloadMember(FX_GIZMO_CANNON_BLAST_02)
  preloadMember(FX_GIZMO_CANNON_BLAST_03)
  preloadMember(FX_GIZMO_CANNON_BLAST_04)
  preloadMember(FX_GIZMO_CANNON_SHOT_01)
  preloadMember(FX_GIZMO_CANNON_SHOT_01A)
  preloadMember(FX_GIZMO_CANNON_SHOT_02)
  preloadMember(FX_GIZMO_CANNON_SHOT_03)
  preloadMember(FX_GIZMO_CANNON_SHOT_04)
  preloadMember(FX_GIZMO_CANNON_SHOT_05)
  preloadMember(FX_GIZMO_CANNON_SHOT_06)
  preloadMember(FX_GIZMO_ELECTRO_PUNCH_01)
  preloadMember(FX_GIZMO_ELECTRO_PUNCH_02)
  preloadMember(FX_GIZMO_ELECTRO_PUNCH_03)
  preloadMember(FX_GIZMO_ELECTRO_PUNCH_04)
  preloadMember(FX_GIZMO_ELECTRO_PUNCH_05)
  preloadMember(FX_GIZMO_ELECTRO_PUNCH_06)
  preloadMember(FX_GIZMO_ELECTRO_PUNCH_07)
  preloadMember(fx_gizmo_electro_punch_08)
  preloadMember(GIZMO_AIRBORNE_FALL_01)
  preloadMember(GIZMO_AIRBORNE_FALL_01D)
  preloadMember(GIZMO_AIRBORNE_FALL_02)
  preloadMember(GIZMO_AIRBORNE_FALL_02D)
  preloadMember(GIZMO_AIRBORNE_HIT_01)
  preloadMember(GIZMO_AIRBORNE_HIT_01D)
  preloadMember(GIZMO_BACKGROUND)
  preloadMember(GIZMO_ELECTRO_PUNCH_01)
  preloadMember(GIZMO_ELECTRO_PUNCH_02)
  preloadMember(GIZMO_ELECTRO_PUNCH_03)
  preloadMember(GIZMO_ELECTRO_PUNCH_03A)
  preloadMember(GIZMO_FALL_01)
  preloadMember(GIZMO_FALL_01D)
  preloadMember(GIZMO_FALL_02)
  preloadMember(GIZMO_FALL_02D)
  preloadMember(GIZMO_HIT_01)
  preloadMember(GIZMO_HIT_01D)
  preloadMember(GIZMO_HOVER_01)
  preloadMember(GIZMO_HOVER_01D)
  preloadMember(GIZMO_LAND_01)
  preloadMember(GIZMO_LAND_01D)
  preloadMember(GIZMO_LAND_02)
  preloadMember(GIZMO_LAND_02D)
  preloadMember(GIZMO_LAND_03)
  preloadMember(GIZMO_LAND_03D)
  preloadMember(GIZMO_MACHINEGUN_01)
  preloadMember(GIZMO_MACHINEGUN_02)
  preloadMember(GIZMO_MACHINEGUN_03)
  preloadMember(GIZMO_MACHINEGUN_04)
  preloadMember(GIZMO_MACHINEGUN_05)
  preloadMember(GIZMO_MACHINEGUN_06)
  preloadMember(GIZMO_MACHINEGUN_07)
  preloadMember(GIZMO_MACHINEGUN_08)
  preloadMember(GIZMO_MISSILE_PROJECTILE_01A)
  preloadMember(GIZMO_MISSILE01_00)
  preloadMember(GIZMO_MISSILE01_01)
  preloadMember(GIZMO_MISSILE01_02)
  preloadMember(GIZMO_MISSILE01_03)
  preloadMember(GIZMO_MISSILE01_04)
  preloadMember(GIZMO_MISSILE01_05)
  preloadMember(GIZMO_MISSILE01_06)
  preloadMember(GIZMO_MISSILE01_07)
  preloadMember(GIZMO_MISSILE01_08)
  preloadMember(GIZMO_MISSILE01_09)
  preloadMember(GIZMO_MISSILE01_10)
  preloadMember(GIZMO_MISSILE01_11)
  preloadMember(GIZMO_MISSILE01_12)
  preloadMember(GIZMO_MISSILE01_13)
  preloadMember(GIZMO_MISSILE01_14)
  preloadMember(GIZMO_MISSILE01_15)
  preloadMember(GIZMO_MISSILE01_16)
  preloadMember(GIZMO_MISSILE01_17)
  preloadMember(GIZMO_MISSILE01_18)
  preloadMember(GIZMO_MISSILE01_19)
  preloadMember(GIZMO_MISSILE01_20)
  preloadMember(GIZMO_MISSILE01_21)
  preloadMember(GIZMO_MISSILE01_22)
  preloadMember(GIZMO_MISSILE02_00)
  preloadMember(GIZMO_MISSILE02_01)
  preloadMember(GIZMO_MISSILE02_02)
  preloadMember(GIZMO_MISSILE02_03)
  preloadMember(GIZMO_MISSILE02_04)
  preloadMember(GIZMO_MISSILE02_05)
  preloadMember(GIZMO_MISSILE02_06)
  preloadMember(GIZMO_MISSILE02_07)
  preloadMember(GIZMO_MISSILE02_08)
  preloadMember(GIZMO_MISSILE02_09)
  preloadMember(GIZMO_MISSILE02_10)
  preloadMember(GIZMO_MISSILE02_11)
  preloadMember(GIZMO_MISSILE02_12)
  preloadMember(GIZMO_MISSILE02_13)
  preloadMember(GIZMO_MISSILE02_14)
  preloadMember(GIZMO_STAND_01)
  preloadMember(GIZMO_STAND_01D)
  preloadMember(GIZMO_TAKEOFF_01)
  preloadMember(GIZMO_TAKEOFF_01D)
  preloadMember(GIZMO_TAKEOFF_02)
  preloadMember(GIZMO_TAKEOFF_02D)
  preloadMember(GIZMO_TAKEOFF_03)
  preloadMember(GIZMO_TAKEOFF_03D)
  preloadMember(GIZMO_TAKEOFF_04)
  preloadMember(GIZMO_TAKEOFF_04D)
  preloadMember(GIZMO_TAKEOFF_05)
  preloadMember(GIZMO_TAKEOFF_05D)
  preloadMember(GIZMO_TAKEOFF_06)
  preloadMember(GIZMO_TAKEOFF_06D)
  preloadMember(GIZMO_TAKEOFF_07)
  preloadMember(GIZMO_TAKEOFF_07D)
  preloadMember(GIZMO_TAKEOFF_08)
  preloadMember(GIZMO_TAKEOFF_08D)
  preloadMember(GIZMO_TAKEOFF_09)
  preloadMember(GIZMO_TAKEOFF_09D)
  preloadMember(GIZMO_TAKEOFF_10)
  preloadMember(GIZMO_TAKEOFF_10D)
  preloadMember(GIZMO_TAKEOFF_11)
  preloadMember(GIZMO_TAKEOFF_11D)
  preloadMember(GIZMO_WALK_01)
  preloadMember(GIZMO_WALK_02)
  preloadMember(GIZMO_WALK_03)
  preloadMember(GIZMO_WALK_04)
  preloadMember(GIZMO_WALK_05)
  preloadMember(GIZMO_WALK_06)
  preloadMember(SFX_GIZMO_AMBIENTBACKGROUNDLOOP)
  preloadMember(SFX_GIZMO_BACKPACKCANNONEMERGING)
  preloadMember(SFX_GIZMO_BACKPACKCANNONEMERGING3)
  preloadMember(SFX_GIZMO_BACKPACKCANNONSHOOTING)
  preloadMember(SFX_GIZMO_CANNONHIT)
  preloadMember(SFX_GIZMO_CANNONMISS)
  preloadMember(SFX_GIZMO_FLY)
  preloadMember(sfx_gizmo_fly2)
  preloadMember(SFX_GIZMO_MISSILEFIRE)
  preloadMember(SFX_GIZMO_MISSILEHIT)
  preloadMember(SFX_GIZMO_MISSILEINFLIGHT)
  preloadMember(SFX_GIZMO_WINGSFOLDIN)
  preloadMember(SFX_GIZMO_WINGSUNFURL)
end
