property MUSIC_KEYBOARD_LOOP, MUSIC_LOOP2, MUSIC_LOOP3, MUSIC_LOOP4, MUSIC_LOOP5, MUSIC_TEEN_LOOP, MUSIC_WHOLE_SONG, sfx_blocked_attack, SFX_CHARACTERSWITCH2, SFX_CHARACTERSWITCH3, SFX_INTERFACE_MISCLICK, SFX_INTERFACE_MOUSEDOWNCHARACTERSWITCH, SFX_INTERFACE_MOUSEDOWNFIGHT, SFX_INTERFACE_MOUSEOVER, SFX_INTERFACE_MOUSEOVERCHARACTERS, SFX_JUMP_0, SFX_JUMP_1, SFX_JUMP_2, SFX_KICK_BLOCK, SFX_KICK_LANDING, SFX_KICK_WOOSH, SFX_LANDING_BIG_PERSON, SFX_LANDING_SMALL_PERSON, SFX_PUNCH_BLOCK, SFX_PUNCH_LANDING, SFX_PUNCH_WOOSH, SFX_SLUMP_TO_FLOOR, SFX_SUMMON_TITAN, SFX_TIME_WARNING, SFX_TITLES_FIGHT, SFX_TITLES_KO, SFX_TITLES_ROUND, SFX_WALKING_BIG_PERSON_1, SFX_WALKING_BIG_PERSON_2, SFX_WALKING_MEDIUM_PERSON_1, SFX_WALKING_MEDIUM_PERSON_2, SFX_WALKING_SMALL_PERSON_1, SFX_WALKING_SMALL_PERSON_2, SFX_WALL_SLAM

on new me
  me.locateMembers()
  return me
end

on locateMembers me
  util = new(script("Class_Utility"))
  ASSET_CAST = "audio"
  MUSIC_KEYBOARD_LOOP = util.findMember("music_keyboard_loop", ASSET_CAST)
  MUSIC_LOOP2 = util.findMember("music_loop2", ASSET_CAST)
  MUSIC_LOOP3 = util.findMember("music_loop3", ASSET_CAST)
  MUSIC_LOOP4 = util.findMember("music_loop4", ASSET_CAST)
  MUSIC_LOOP5 = util.findMember("music_loop5", ASSET_CAST)
  MUSIC_TEEN_LOOP = util.findMember("music_teen_loop", ASSET_CAST)
  MUSIC_WHOLE_SONG = util.findMember("music_whole_song", ASSET_CAST)
  sfx_blocked_attack = util.findMember("sfx_blocked_attack", ASSET_CAST)
  SFX_CHARACTERSWITCH2 = util.findMember("sfx_characterswitch2", ASSET_CAST)
  SFX_CHARACTERSWITCH3 = util.findMember("sfx_characterswitch3", ASSET_CAST)
  SFX_INTERFACE_MISCLICK = util.findMember("sfx_interface_misclick", ASSET_CAST)
  SFX_INTERFACE_MOUSEDOWNCHARACTERSWITCH = util.findMember("sfx_interface_mousedowncharacterswitch", ASSET_CAST)
  SFX_INTERFACE_MOUSEDOWNFIGHT = util.findMember("sfx_interface_mousedownfight", ASSET_CAST)
  SFX_INTERFACE_MOUSEOVER = util.findMember("sfx_interface_mouseover", ASSET_CAST)
  SFX_INTERFACE_MOUSEOVERCHARACTERS = util.findMember("sfx_interface_mouseovercharacters", ASSET_CAST)
  SFX_JUMP_0 = util.findMember("sfx_jump_0", ASSET_CAST)
  SFX_JUMP_1 = util.findMember("sfx_jump_1", ASSET_CAST)
  SFX_JUMP_2 = util.findMember("sfx_jump_2", ASSET_CAST)
  SFX_KICK_BLOCK = util.findMember("sfx_kick_block", ASSET_CAST)
  SFX_KICK_LANDING = util.findMember("sfx_kick_landing", ASSET_CAST)
  SFX_KICK_WOOSH = util.findMember("sfx_kick_woosh", ASSET_CAST)
  SFX_LANDING_BIG_PERSON = util.findMember("sfx_landing_big_person", ASSET_CAST)
  SFX_LANDING_SMALL_PERSON = util.findMember("sfx_landing_small_person", ASSET_CAST)
  SFX_PUNCH_BLOCK = util.findMember("sfx_punch_block", ASSET_CAST)
  SFX_PUNCH_LANDING = util.findMember("sfx_punch_landing", ASSET_CAST)
  SFX_PUNCH_WOOSH = util.findMember("sfx_punch_woosh", ASSET_CAST)
  SFX_SLUMP_TO_FLOOR = util.findMember("sfx_slump_to_floor", ASSET_CAST)
  SFX_SUMMON_TITAN = util.findMember("sfx_summon_titan", ASSET_CAST)
  SFX_TIME_WARNING = util.findMember("sfx_time_warning", ASSET_CAST)
  SFX_TITLES_FIGHT = util.findMember("sfx_titles_fight", ASSET_CAST)
  SFX_TITLES_KO = util.findMember("sfx_titles_ko", ASSET_CAST)
  SFX_TITLES_ROUND = util.findMember("sfx_titles_round", ASSET_CAST)
  SFX_WALKING_BIG_PERSON_1 = util.findMember("sfx_walking_big_person_1", ASSET_CAST)
  SFX_WALKING_BIG_PERSON_2 = util.findMember("sfx_walking_big_person_2", ASSET_CAST)
  SFX_WALKING_MEDIUM_PERSON_1 = util.findMember("sfx_walking_medium_person_1", ASSET_CAST)
  SFX_WALKING_MEDIUM_PERSON_2 = util.findMember("sfx_walking_medium_person_2", ASSET_CAST)
  SFX_WALKING_SMALL_PERSON_1 = util.findMember("sfx_walking_small_person_1", ASSET_CAST)
  SFX_WALKING_SMALL_PERSON_2 = util.findMember("sfx_walking_small_person_2", ASSET_CAST)
  SFX_WALL_SLAM = util.findMember("sfx_wall_slam", ASSET_CAST)
end

on precache me
  preloadMember(MUSIC_KEYBOARD_LOOP)
  preloadMember(MUSIC_LOOP2)
  preloadMember(MUSIC_LOOP3)
  preloadMember(MUSIC_LOOP4)
  preloadMember(MUSIC_LOOP5)
  preloadMember(MUSIC_TEEN_LOOP)
  preloadMember(MUSIC_WHOLE_SONG)
  preloadMember(sfx_blocked_attack)
  preloadMember(SFX_CHARACTERSWITCH2)
  preloadMember(SFX_CHARACTERSWITCH3)
  preloadMember(SFX_INTERFACE_MISCLICK)
  preloadMember(SFX_INTERFACE_MOUSEDOWNCHARACTERSWITCH)
  preloadMember(SFX_INTERFACE_MOUSEDOWNFIGHT)
  preloadMember(SFX_INTERFACE_MOUSEOVER)
  preloadMember(SFX_INTERFACE_MOUSEOVERCHARACTERS)
  preloadMember(SFX_JUMP_0)
  preloadMember(SFX_JUMP_1)
  preloadMember(SFX_JUMP_2)
  preloadMember(SFX_KICK_BLOCK)
  preloadMember(SFX_KICK_LANDING)
  preloadMember(SFX_KICK_WOOSH)
  preloadMember(SFX_LANDING_BIG_PERSON)
  preloadMember(SFX_LANDING_SMALL_PERSON)
  preloadMember(SFX_PUNCH_BLOCK)
  preloadMember(SFX_PUNCH_LANDING)
  preloadMember(SFX_PUNCH_WOOSH)
  preloadMember(SFX_SLUMP_TO_FLOOR)
  preloadMember(SFX_SUMMON_TITAN)
  preloadMember(SFX_TIME_WARNING)
  preloadMember(SFX_TITLES_FIGHT)
  preloadMember(SFX_TITLES_KO)
  preloadMember(SFX_TITLES_ROUND)
  preloadMember(SFX_WALKING_BIG_PERSON_1)
  preloadMember(SFX_WALKING_BIG_PERSON_2)
  preloadMember(SFX_WALKING_MEDIUM_PERSON_1)
  preloadMember(SFX_WALKING_MEDIUM_PERSON_2)
  preloadMember(SFX_WALKING_SMALL_PERSON_1)
  preloadMember(SFX_WALKING_SMALL_PERSON_2)
  preloadMember(SFX_WALL_SLAM)
end
