property CINDERBLOCK_BACKGROUND, CINDERBLOCK_BACKHAND_01, CINDERBLOCK_BACKHAND_01D, CINDERBLOCK_BACKHAND_02, CINDERBLOCK_BACKHAND_02A, CINDERBLOCK_BACKHAND_02D, CINDERBLOCK_BACKHAND_03, CINDERBLOCK_BACKHAND_03D, CINDERBLOCK_BACKHAND_04, CINDERBLOCK_BACKHAND_04D, CINDERBLOCK_BACKHAND_05, CINDERBLOCK_BACKHAND_05D, CINDERBLOCK_FALL_01, CINDERBLOCK_FALL_01D, CINDERBLOCK_FALL_02, CINDERBLOCK_FALL_02D, CINDERBLOCK_FALL_03, CINDERBLOCK_FALL_03D, CINDERBLOCK_HIT_01, CINDERBLOCK_HIT_01D, CINDERBLOCK_PUNCH_01, CINDERBLOCK_PUNCH_01D, CINDERBLOCK_PUNCH_02, CINDERBLOCK_PUNCH_02D, CINDERBLOCK_PUNCH_03, CINDERBLOCK_PUNCH_03A, CINDERBLOCK_PUNCH_03D, CINDERBLOCK_PUNCH_04, CINDERBLOCK_PUNCH_04D, CINDERBLOCK_PUNCH_05, CINDERBLOCK_PUNCH_05A, CINDERBLOCK_PUNCH_05D, CINDERBLOCK_PUNCH_06, CINDERBLOCK_PUNCH_06D, CINDERBLOCK_STAND_01, CINDERBLOCK_STAND_01D, CINDERBLOCK_STOMP_01, CINDERBLOCK_STOMP_01D, CINDERBLOCK_STOMP_02, CINDERBLOCK_STOMP_02D, CINDERBLOCK_STOMP_03, CINDERBLOCK_STOMP_03A, CINDERBLOCK_STOMP_03D, CINDERBLOCK_STOMP_04, CINDERBLOCK_STOMP_04D, CINDERBLOCK_WALK_01, CINDERBLOCK_WALK_02, CINDERBLOCK_WALK_03, CINDERBLOCK_WALK_04, CINDERBLOCK_WALK_05, CINDERBLOCK_WALK_06, CINDERBLOCK_WALK_07, CINDERBLOCK_WALK_08, CINDERBLOCK_WAVE_PROJECTILE_01A, FX_CINDERBLOCK_ENERGY_01, FX_CINDERBLOCK_ENERGY_02, FX_CINDERBLOCK_ENERGY_03, FX_CINDERBLOCK_ENERGY_04, FX_CINDERBLOCK_ENERGY_05, FX_CINDERBLOCK_ENERGY_06, FX_CINDERBLOCK_ENERGY_07, FX_CINDERBLOCK_ENERGY_08, SFX_CINDERBLOCK_BACKHANDHIT, SFX_CINDERBLOCK_BACKHANDMISS, SFX_CINDERBLOCK_BACKHANDWOOSH, SFX_CINDERBLOCK_BG_SIRENS, SFX_CINDERBLOCK_GROUNDSTOMP, SFX_CINDERBLOCK_SHOCKWAVEHIT, SFX_CINDERBLOCK_SHOCKWAVEMISS

on new me
  me.locateMembers()
  return me
end

on locateMembers me
  util = new(script("Class_Utility"))
  ASSET_CAST = "char_Cinderblock"
  CINDERBLOCK_BACKGROUND = util.findMember("cinderblock_background", ASSET_CAST)
  CINDERBLOCK_BACKHAND_01 = util.findMember("cinderblock_backhand_01", ASSET_CAST)
  CINDERBLOCK_BACKHAND_01D = util.findMember("cinderblock_backhand_01d", ASSET_CAST)
  CINDERBLOCK_BACKHAND_02 = util.findMember("cinderblock_backhand_02", ASSET_CAST)
  CINDERBLOCK_BACKHAND_02A = util.findMember("cinderblock_backhand_02a", ASSET_CAST)
  CINDERBLOCK_BACKHAND_02D = util.findMember("cinderblock_backhand_02d", ASSET_CAST)
  CINDERBLOCK_BACKHAND_03 = util.findMember("cinderblock_backhand_03", ASSET_CAST)
  CINDERBLOCK_BACKHAND_03D = util.findMember("cinderblock_backhand_03d", ASSET_CAST)
  CINDERBLOCK_BACKHAND_04 = util.findMember("cinderblock_backhand_04", ASSET_CAST)
  CINDERBLOCK_BACKHAND_04D = util.findMember("cinderblock_backhand_04d", ASSET_CAST)
  CINDERBLOCK_BACKHAND_05 = util.findMember("cinderblock_backhand_05", ASSET_CAST)
  CINDERBLOCK_BACKHAND_05D = util.findMember("cinderblock_backhand_05d", ASSET_CAST)
  CINDERBLOCK_FALL_01 = util.findMember("cinderblock_fall_01", ASSET_CAST)
  CINDERBLOCK_FALL_01D = util.findMember("cinderblock_fall_01d", ASSET_CAST)
  CINDERBLOCK_FALL_02 = util.findMember("cinderblock_fall_02", ASSET_CAST)
  CINDERBLOCK_FALL_02D = util.findMember("cinderblock_fall_02d", ASSET_CAST)
  CINDERBLOCK_FALL_03 = util.findMember("cinderblock_fall_03", ASSET_CAST)
  CINDERBLOCK_FALL_03D = util.findMember("cinderblock_fall_03d", ASSET_CAST)
  CINDERBLOCK_HIT_01 = util.findMember("cinderblock_hit_01", ASSET_CAST)
  CINDERBLOCK_HIT_01D = util.findMember("cinderblock_hit_01d", ASSET_CAST)
  CINDERBLOCK_PUNCH_01 = util.findMember("cinderblock_punch_01", ASSET_CAST)
  CINDERBLOCK_PUNCH_01D = util.findMember("cinderblock_punch_01d", ASSET_CAST)
  CINDERBLOCK_PUNCH_02 = util.findMember("cinderblock_punch_02", ASSET_CAST)
  CINDERBLOCK_PUNCH_02D = util.findMember("cinderblock_punch_02d", ASSET_CAST)
  CINDERBLOCK_PUNCH_03 = util.findMember("cinderblock_punch_03", ASSET_CAST)
  CINDERBLOCK_PUNCH_03A = util.findMember("cinderblock_punch_03a", ASSET_CAST)
  CINDERBLOCK_PUNCH_03D = util.findMember("cinderblock_punch_03d", ASSET_CAST)
  CINDERBLOCK_PUNCH_04 = util.findMember("cinderblock_punch_04", ASSET_CAST)
  CINDERBLOCK_PUNCH_04D = util.findMember("cinderblock_punch_04d", ASSET_CAST)
  CINDERBLOCK_PUNCH_05 = util.findMember("cinderblock_punch_05", ASSET_CAST)
  CINDERBLOCK_PUNCH_05A = util.findMember("cinderblock_punch_05a", ASSET_CAST)
  CINDERBLOCK_PUNCH_05D = util.findMember("cinderblock_punch_05d", ASSET_CAST)
  CINDERBLOCK_PUNCH_06 = util.findMember("cinderblock_punch_06", ASSET_CAST)
  CINDERBLOCK_PUNCH_06D = util.findMember("cinderblock_punch_06d", ASSET_CAST)
  CINDERBLOCK_STAND_01 = util.findMember("cinderblock_stand_01", ASSET_CAST)
  CINDERBLOCK_STAND_01D = util.findMember("cinderblock_stand_01d", ASSET_CAST)
  CINDERBLOCK_STOMP_01 = util.findMember("cinderblock_stomp_01", ASSET_CAST)
  CINDERBLOCK_STOMP_01D = util.findMember("cinderblock_stomp_01d", ASSET_CAST)
  CINDERBLOCK_STOMP_02 = util.findMember("cinderblock_stomp_02", ASSET_CAST)
  CINDERBLOCK_STOMP_02D = util.findMember("cinderblock_stomp_02d", ASSET_CAST)
  CINDERBLOCK_STOMP_03 = util.findMember("cinderblock_stomp_03", ASSET_CAST)
  CINDERBLOCK_STOMP_03A = util.findMember("cinderblock_stomp_03a", ASSET_CAST)
  CINDERBLOCK_STOMP_03D = util.findMember("cinderblock_stomp_03d", ASSET_CAST)
  CINDERBLOCK_STOMP_04 = util.findMember("cinderblock_stomp_04", ASSET_CAST)
  CINDERBLOCK_STOMP_04D = util.findMember("cinderblock_stomp_04d", ASSET_CAST)
  CINDERBLOCK_WALK_01 = util.findMember("cinderblock_walk_01", ASSET_CAST)
  CINDERBLOCK_WALK_02 = util.findMember("cinderblock_walk_02", ASSET_CAST)
  CINDERBLOCK_WALK_03 = util.findMember("cinderblock_walk_03", ASSET_CAST)
  CINDERBLOCK_WALK_04 = util.findMember("cinderblock_walk_04", ASSET_CAST)
  CINDERBLOCK_WALK_05 = util.findMember("cinderblock_walk_05", ASSET_CAST)
  CINDERBLOCK_WALK_06 = util.findMember("cinderblock_walk_06", ASSET_CAST)
  CINDERBLOCK_WALK_07 = util.findMember("cinderblock_walk_07", ASSET_CAST)
  CINDERBLOCK_WALK_08 = util.findMember("cinderblock_walk_08", ASSET_CAST)
  CINDERBLOCK_WAVE_PROJECTILE_01A = util.findMember("cinderblock_wave_projectile_01a", ASSET_CAST)
  FX_CINDERBLOCK_ENERGY_01 = util.findMember("fx_cinderblock_energy_01", ASSET_CAST)
  FX_CINDERBLOCK_ENERGY_02 = util.findMember("fx_cinderblock_energy_02", ASSET_CAST)
  FX_CINDERBLOCK_ENERGY_03 = util.findMember("fx_cinderblock_energy_03", ASSET_CAST)
  FX_CINDERBLOCK_ENERGY_04 = util.findMember("fx_cinderblock_energy_04", ASSET_CAST)
  FX_CINDERBLOCK_ENERGY_05 = util.findMember("fx_cinderblock_energy_05", ASSET_CAST)
  FX_CINDERBLOCK_ENERGY_06 = util.findMember("fx_cinderblock_energy_06", ASSET_CAST)
  FX_CINDERBLOCK_ENERGY_07 = util.findMember("fx_cinderblock_energy_07", ASSET_CAST)
  FX_CINDERBLOCK_ENERGY_08 = util.findMember("fx_cinderblock_energy_08", ASSET_CAST)
  SFX_CINDERBLOCK_BACKHANDHIT = util.findMember("sfx_cinderblock_backhandhit", ASSET_CAST)
  SFX_CINDERBLOCK_BACKHANDMISS = util.findMember("sfx_cinderblock_backhandmiss", ASSET_CAST)
  SFX_CINDERBLOCK_BACKHANDWOOSH = util.findMember("sfx_cinderblock_backhandwoosh", ASSET_CAST)
  SFX_CINDERBLOCK_BG_SIRENS = util.findMember("sfx_cinderblock_bg_sirens", ASSET_CAST)
  SFX_CINDERBLOCK_GROUNDSTOMP = util.findMember("sfx_cinderblock_groundstomp", ASSET_CAST)
  SFX_CINDERBLOCK_SHOCKWAVEHIT = util.findMember("sfx_cinderblock_shockwavehit", ASSET_CAST)
  SFX_CINDERBLOCK_SHOCKWAVEMISS = util.findMember("sfx_cinderblock_shockwavemiss", ASSET_CAST)
end

on precache me
  preloadMember(CINDERBLOCK_BACKGROUND)
  preloadMember(CINDERBLOCK_BACKHAND_01)
  preloadMember(CINDERBLOCK_BACKHAND_01D)
  preloadMember(CINDERBLOCK_BACKHAND_02)
  preloadMember(CINDERBLOCK_BACKHAND_02A)
  preloadMember(CINDERBLOCK_BACKHAND_02D)
  preloadMember(CINDERBLOCK_BACKHAND_03)
  preloadMember(CINDERBLOCK_BACKHAND_03D)
  preloadMember(CINDERBLOCK_BACKHAND_04)
  preloadMember(CINDERBLOCK_BACKHAND_04D)
  preloadMember(CINDERBLOCK_BACKHAND_05)
  preloadMember(CINDERBLOCK_BACKHAND_05D)
  preloadMember(CINDERBLOCK_FALL_01)
  preloadMember(CINDERBLOCK_FALL_01D)
  preloadMember(CINDERBLOCK_FALL_02)
  preloadMember(CINDERBLOCK_FALL_02D)
  preloadMember(CINDERBLOCK_FALL_03)
  preloadMember(CINDERBLOCK_FALL_03D)
  preloadMember(CINDERBLOCK_HIT_01)
  preloadMember(CINDERBLOCK_HIT_01D)
  preloadMember(CINDERBLOCK_PUNCH_01)
  preloadMember(CINDERBLOCK_PUNCH_01D)
  preloadMember(CINDERBLOCK_PUNCH_02)
  preloadMember(CINDERBLOCK_PUNCH_02D)
  preloadMember(CINDERBLOCK_PUNCH_03)
  preloadMember(CINDERBLOCK_PUNCH_03A)
  preloadMember(CINDERBLOCK_PUNCH_03D)
  preloadMember(CINDERBLOCK_PUNCH_04)
  preloadMember(CINDERBLOCK_PUNCH_04D)
  preloadMember(CINDERBLOCK_PUNCH_05)
  preloadMember(CINDERBLOCK_PUNCH_05A)
  preloadMember(CINDERBLOCK_PUNCH_05D)
  preloadMember(CINDERBLOCK_PUNCH_06)
  preloadMember(CINDERBLOCK_PUNCH_06D)
  preloadMember(CINDERBLOCK_STAND_01)
  preloadMember(CINDERBLOCK_STAND_01D)
  preloadMember(CINDERBLOCK_STOMP_01)
  preloadMember(CINDERBLOCK_STOMP_01D)
  preloadMember(CINDERBLOCK_STOMP_02)
  preloadMember(CINDERBLOCK_STOMP_02D)
  preloadMember(CINDERBLOCK_STOMP_03)
  preloadMember(CINDERBLOCK_STOMP_03A)
  preloadMember(CINDERBLOCK_STOMP_03D)
  preloadMember(CINDERBLOCK_STOMP_04)
  preloadMember(CINDERBLOCK_STOMP_04D)
  preloadMember(CINDERBLOCK_WALK_01)
  preloadMember(CINDERBLOCK_WALK_02)
  preloadMember(CINDERBLOCK_WALK_03)
  preloadMember(CINDERBLOCK_WALK_04)
  preloadMember(CINDERBLOCK_WALK_05)
  preloadMember(CINDERBLOCK_WALK_06)
  preloadMember(CINDERBLOCK_WALK_07)
  preloadMember(CINDERBLOCK_WALK_08)
  preloadMember(CINDERBLOCK_WAVE_PROJECTILE_01A)
  preloadMember(FX_CINDERBLOCK_ENERGY_01)
  preloadMember(FX_CINDERBLOCK_ENERGY_02)
  preloadMember(FX_CINDERBLOCK_ENERGY_03)
  preloadMember(FX_CINDERBLOCK_ENERGY_04)
  preloadMember(FX_CINDERBLOCK_ENERGY_05)
  preloadMember(FX_CINDERBLOCK_ENERGY_06)
  preloadMember(FX_CINDERBLOCK_ENERGY_07)
  preloadMember(FX_CINDERBLOCK_ENERGY_08)
  preloadMember(SFX_CINDERBLOCK_BACKHANDHIT)
  preloadMember(SFX_CINDERBLOCK_BACKHANDMISS)
  preloadMember(SFX_CINDERBLOCK_BACKHANDWOOSH)
  preloadMember(SFX_CINDERBLOCK_BG_SIRENS)
  preloadMember(SFX_CINDERBLOCK_GROUNDSTOMP)
  preloadMember(SFX_CINDERBLOCK_SHOCKWAVEHIT)
  preloadMember(SFX_CINDERBLOCK_SHOCKWAVEMISS)
end
