property FX_STARFIRE_BALL_01, FX_STARFIRE_BALL_01A, FX_STARFIRE_BOLT_EXPLODE_01A, FX_STARFIRE_FIST_01, FX_STARFIRE_FIST_02, FX_STARFIRE_FIST_03, FX_STARFIRE_FIST_04, FX_STARFIRE_FIST_05, FX_STARFIRE_FIST_06, FX_STARFIRE_FIST_07, FX_STARFIRE_FIST_08, FX_STARFIRE_FIST_09, FX_STARFIRE_FIST_10, FX_STARFIRE_FIST_11, FX_STARFIRE_FIST_12, FX_STARFIRE_SUMMON_01, FX_STARFIRE_SUMMON_02, FX_STARFIRE_SUMMON_03, FX_STARFIRE_SUMMON_04, FX_STARFIRE_SUMMON_05, SFX_STARFIRE_STARBOLT_HIT, SFX_STARFIRE_STARBOLT_MISS, SFX_STARFIRE_STARBOLT_THROW, STARFIRE_ATTACK_01D, STARFIRE_ATTACK_02D, STARFIRE_ATTACK_03D, STARFIRE_ATTACK_04D, STARFIRE_FALL_01, STARFIRE_FALL_01D, STARFIRE_FALL_02, STARFIRE_FALL_02D, STARFIRE_FLOAT_FWD_01, STARFIRE_FLOAT_FWD_01D, STARFIRE_FLOAT_UP_01D, STARFIRE_FLYINGKICK_01, STARFIRE_FLYINGKICK_01D, STARFIRE_FLYINGKICK_02, STARFIRE_FLYINGKICK_02A, STARFIRE_FLYINGKICK_02D, STARFIRE_FLYINGKNEE_01, STARFIRE_FLYINGKNEE_01A, STARFIRE_FLYINGKNEE_01D, STARFIRE_FLYINGKNEE_02, STARFIRE_FLYINGKNEE_02A, STARFIRE_FLYINGKNEE_02D, STARFIRE_FLYINGKNEE_03, STARFIRE_FLYINGKNEE_03A, STARFIRE_FLYINGKNEE_03D, STARFIRE_HIT_01, STARFIRE_HIT_01D, STARFIRE_HIT_02, STARFIRE_HIT_02D, STARFIRE_HIT_03, STARFIRE_HIT_03D, STARFIRE_KICK_01, STARFIRE_KICK_01D, STARFIRE_KICK_02, STARFIRE_KICK_02A, STARFIRE_KICK_02D, STARFIRE_KICK_03, STARFIRE_KICK_03D, STARFIRE_PUNCH_01, STARFIRE_PUNCH_01D, STARFIRE_PUNCH_02, STARFIRE_PUNCH_02A, STARFIRE_PUNCH_02D, STARFIRE_PUNCH_03, STARFIRE_PUNCH_03D, STARFIRE_STAND_01, STARFIRE_STAND_01D

on new me
  me.locateMembers()
  return me
end

on locateMembers me
  util = new(script("Class_Utility"))
  ASSET_CAST = "char_Starfire"
  FX_STARFIRE_BALL_01 = util.findMember("fx_starfire_ball_01", ASSET_CAST)
  FX_STARFIRE_BALL_01A = util.findMember("fx_starfire_ball_01a", ASSET_CAST)
  FX_STARFIRE_BOLT_EXPLODE_01A = util.findMember("fx_starfire_bolt_explode_01a", ASSET_CAST)
  FX_STARFIRE_FIST_01 = util.findMember("fx_starfire_fist_01", ASSET_CAST)
  FX_STARFIRE_FIST_02 = util.findMember("fx_starfire_fist_02", ASSET_CAST)
  FX_STARFIRE_FIST_03 = util.findMember("fx_starfire_fist_03", ASSET_CAST)
  FX_STARFIRE_FIST_04 = util.findMember("fx_starfire_fist_04", ASSET_CAST)
  FX_STARFIRE_FIST_05 = util.findMember("fx_starfire_fist_05", ASSET_CAST)
  FX_STARFIRE_FIST_06 = util.findMember("fx_starfire_fist_06", ASSET_CAST)
  FX_STARFIRE_FIST_07 = util.findMember("fx_starfire_fist_07", ASSET_CAST)
  FX_STARFIRE_FIST_08 = util.findMember("fx_starfire_fist_08", ASSET_CAST)
  FX_STARFIRE_FIST_09 = util.findMember("fx_starfire_fist_09", ASSET_CAST)
  FX_STARFIRE_FIST_10 = util.findMember("fx_starfire_fist_10", ASSET_CAST)
  FX_STARFIRE_FIST_11 = util.findMember("fx_starfire_fist_11", ASSET_CAST)
  FX_STARFIRE_FIST_12 = util.findMember("fx_starfire_fist_12", ASSET_CAST)
  FX_STARFIRE_SUMMON_01 = util.findMember("fx_starfire_summon_01", ASSET_CAST)
  FX_STARFIRE_SUMMON_02 = util.findMember("fx_starfire_summon_02", ASSET_CAST)
  FX_STARFIRE_SUMMON_03 = util.findMember("fx_starfire_summon_03", ASSET_CAST)
  FX_STARFIRE_SUMMON_04 = util.findMember("fx_starfire_summon_04", ASSET_CAST)
  FX_STARFIRE_SUMMON_05 = util.findMember("fx_starfire_summon_05", ASSET_CAST)
  SFX_STARFIRE_STARBOLT_HIT = util.findMember("sfx_starfire_starbolt_hit", ASSET_CAST)
  SFX_STARFIRE_STARBOLT_MISS = util.findMember("sfx_starfire_starbolt_miss", ASSET_CAST)
  SFX_STARFIRE_STARBOLT_THROW = util.findMember("sfx_starfire_starbolt_throw", ASSET_CAST)
  STARFIRE_ATTACK_01D = util.findMember("starfire_attack_01d", ASSET_CAST)
  STARFIRE_ATTACK_02D = util.findMember("starfire_attack_02d", ASSET_CAST)
  STARFIRE_ATTACK_03D = util.findMember("starfire_attack_03d", ASSET_CAST)
  STARFIRE_ATTACK_04D = util.findMember("starfire_attack_04d", ASSET_CAST)
  STARFIRE_FALL_01 = util.findMember("starfire_fall_01", ASSET_CAST)
  STARFIRE_FALL_01D = util.findMember("starfire_fall_01d", ASSET_CAST)
  STARFIRE_FALL_02 = util.findMember("starfire_fall_02", ASSET_CAST)
  STARFIRE_FALL_02D = util.findMember("starfire_fall_02d", ASSET_CAST)
  STARFIRE_FLOAT_FWD_01 = util.findMember("starfire_float_fwd_01", ASSET_CAST)
  STARFIRE_FLOAT_FWD_01D = util.findMember("starfire_float_fwd_01d", ASSET_CAST)
  STARFIRE_FLOAT_UP_01D = util.findMember("starfire_float_up_01d", ASSET_CAST)
  STARFIRE_FLYINGKICK_01 = util.findMember("starfire_flyingkick_01", ASSET_CAST)
  STARFIRE_FLYINGKICK_01D = util.findMember("starfire_flyingkick_01d", ASSET_CAST)
  STARFIRE_FLYINGKICK_02 = util.findMember("starfire_flyingkick_02", ASSET_CAST)
  STARFIRE_FLYINGKICK_02A = util.findMember("starfire_flyingkick_02a", ASSET_CAST)
  STARFIRE_FLYINGKICK_02D = util.findMember("starfire_flyingkick_02d", ASSET_CAST)
  STARFIRE_FLYINGKNEE_01 = util.findMember("starfire_flyingknee_01", ASSET_CAST)
  STARFIRE_FLYINGKNEE_01A = util.findMember("starfire_flyingknee_01a", ASSET_CAST)
  STARFIRE_FLYINGKNEE_01D = util.findMember("starfire_flyingknee_01d", ASSET_CAST)
  STARFIRE_FLYINGKNEE_02 = util.findMember("starfire_flyingknee_02", ASSET_CAST)
  STARFIRE_FLYINGKNEE_02A = util.findMember("starfire_flyingknee_02a", ASSET_CAST)
  STARFIRE_FLYINGKNEE_02D = util.findMember("starfire_flyingknee_02d", ASSET_CAST)
  STARFIRE_FLYINGKNEE_03 = util.findMember("starfire_flyingknee_03", ASSET_CAST)
  STARFIRE_FLYINGKNEE_03A = util.findMember("starfire_flyingknee_03a", ASSET_CAST)
  STARFIRE_FLYINGKNEE_03D = util.findMember("starfire_flyingknee_03d", ASSET_CAST)
  STARFIRE_HIT_01 = util.findMember("starfire_hit_01", ASSET_CAST)
  STARFIRE_HIT_01D = util.findMember("starfire_hit_01d", ASSET_CAST)
  STARFIRE_HIT_02 = util.findMember("starfire_hit_02", ASSET_CAST)
  STARFIRE_HIT_02D = util.findMember("starfire_hit_02d", ASSET_CAST)
  STARFIRE_HIT_03 = util.findMember("starfire_hit_03", ASSET_CAST)
  STARFIRE_HIT_03D = util.findMember("starfire_hit_03d", ASSET_CAST)
  STARFIRE_KICK_01 = util.findMember("starfire_kick_01", ASSET_CAST)
  STARFIRE_KICK_01D = util.findMember("starfire_kick_01d", ASSET_CAST)
  STARFIRE_KICK_02 = util.findMember("starfire_kick_02", ASSET_CAST)
  STARFIRE_KICK_02A = util.findMember("starfire_kick_02a", ASSET_CAST)
  STARFIRE_KICK_02D = util.findMember("starfire_kick_02d", ASSET_CAST)
  STARFIRE_KICK_03 = util.findMember("starfire_kick_03", ASSET_CAST)
  STARFIRE_KICK_03D = util.findMember("starfire_kick_03d", ASSET_CAST)
  STARFIRE_PUNCH_01 = util.findMember("starfire_punch_01", ASSET_CAST)
  STARFIRE_PUNCH_01D = util.findMember("starfire_punch_01d", ASSET_CAST)
  STARFIRE_PUNCH_02 = util.findMember("starfire_punch_02", ASSET_CAST)
  STARFIRE_PUNCH_02A = util.findMember("starfire_punch_02a", ASSET_CAST)
  STARFIRE_PUNCH_02D = util.findMember("starfire_punch_02d", ASSET_CAST)
  STARFIRE_PUNCH_03 = util.findMember("starfire_punch_03", ASSET_CAST)
  STARFIRE_PUNCH_03D = util.findMember("starfire_punch_03d", ASSET_CAST)
  STARFIRE_STAND_01 = util.findMember("starfire_stand_01", ASSET_CAST)
  STARFIRE_STAND_01D = util.findMember("starfire_stand_01d", ASSET_CAST)
end

on precache me
  preloadMember(FX_STARFIRE_BALL_01)
  preloadMember(FX_STARFIRE_BALL_01A)
  preloadMember(FX_STARFIRE_BOLT_EXPLODE_01A)
  preloadMember(FX_STARFIRE_FIST_01)
  preloadMember(FX_STARFIRE_FIST_02)
  preloadMember(FX_STARFIRE_FIST_03)
  preloadMember(FX_STARFIRE_FIST_04)
  preloadMember(FX_STARFIRE_FIST_05)
  preloadMember(FX_STARFIRE_FIST_06)
  preloadMember(FX_STARFIRE_FIST_07)
  preloadMember(FX_STARFIRE_FIST_08)
  preloadMember(FX_STARFIRE_FIST_09)
  preloadMember(FX_STARFIRE_FIST_10)
  preloadMember(FX_STARFIRE_FIST_11)
  preloadMember(FX_STARFIRE_FIST_12)
  preloadMember(FX_STARFIRE_SUMMON_01)
  preloadMember(FX_STARFIRE_SUMMON_02)
  preloadMember(FX_STARFIRE_SUMMON_03)
  preloadMember(FX_STARFIRE_SUMMON_04)
  preloadMember(FX_STARFIRE_SUMMON_05)
  preloadMember(SFX_STARFIRE_STARBOLT_HIT)
  preloadMember(SFX_STARFIRE_STARBOLT_MISS)
  preloadMember(SFX_STARFIRE_STARBOLT_THROW)
  preloadMember(STARFIRE_ATTACK_01D)
  preloadMember(STARFIRE_ATTACK_02D)
  preloadMember(STARFIRE_ATTACK_03D)
  preloadMember(STARFIRE_ATTACK_04D)
  preloadMember(STARFIRE_FALL_01)
  preloadMember(STARFIRE_FALL_01D)
  preloadMember(STARFIRE_FALL_02)
  preloadMember(STARFIRE_FALL_02D)
  preloadMember(STARFIRE_FLOAT_FWD_01)
  preloadMember(STARFIRE_FLOAT_FWD_01D)
  preloadMember(STARFIRE_FLOAT_UP_01D)
  preloadMember(STARFIRE_FLYINGKICK_01)
  preloadMember(STARFIRE_FLYINGKICK_01D)
  preloadMember(STARFIRE_FLYINGKICK_02)
  preloadMember(STARFIRE_FLYINGKICK_02A)
  preloadMember(STARFIRE_FLYINGKICK_02D)
  preloadMember(STARFIRE_FLYINGKNEE_01)
  preloadMember(STARFIRE_FLYINGKNEE_01A)
  preloadMember(STARFIRE_FLYINGKNEE_01D)
  preloadMember(STARFIRE_FLYINGKNEE_02)
  preloadMember(STARFIRE_FLYINGKNEE_02A)
  preloadMember(STARFIRE_FLYINGKNEE_02D)
  preloadMember(STARFIRE_FLYINGKNEE_03)
  preloadMember(STARFIRE_FLYINGKNEE_03A)
  preloadMember(STARFIRE_FLYINGKNEE_03D)
  preloadMember(STARFIRE_HIT_01)
  preloadMember(STARFIRE_HIT_01D)
  preloadMember(STARFIRE_HIT_02)
  preloadMember(STARFIRE_HIT_02D)
  preloadMember(STARFIRE_HIT_03)
  preloadMember(STARFIRE_HIT_03D)
  preloadMember(STARFIRE_KICK_01)
  preloadMember(STARFIRE_KICK_01D)
  preloadMember(STARFIRE_KICK_02)
  preloadMember(STARFIRE_KICK_02A)
  preloadMember(STARFIRE_KICK_02D)
  preloadMember(STARFIRE_KICK_03)
  preloadMember(STARFIRE_KICK_03D)
  preloadMember(STARFIRE_PUNCH_01)
  preloadMember(STARFIRE_PUNCH_01D)
  preloadMember(STARFIRE_PUNCH_02)
  preloadMember(STARFIRE_PUNCH_02A)
  preloadMember(STARFIRE_PUNCH_02D)
  preloadMember(STARFIRE_PUNCH_03)
  preloadMember(STARFIRE_PUNCH_03D)
  preloadMember(STARFIRE_STAND_01)
  preloadMember(STARFIRE_STAND_01D)
end
