property BEASTBOY_PTERODACTYL_01, BEASTBOY_PTERODACTYL_02, BEASTBOY_PTERODACTYL_03, BG_EN_STRETCH_000, BG_EN_STRETCH_001, BG_EN_STRETCH_002, BG_TITANS_STRETCH_000, BG_TITANS_STRETCH_001, BG_TITANS_STRETCH_002, CYBORG_JUMP_PUNCH_01, CYBORG_JUMP_PUNCH_02, CYBORG_JUMP_PUNCH_ALT_01, CYBORG_JUMP_PUNCH_ALT_02, FX_CYBORG_LINES_01, FX_CYBORG_LINES_02, FX_CYBORG_LINES_03, FX_CYBORG_LINES_04, FX_CYBORG_LINES_05, FX_DUST_JUMP_01, FX_DUST_JUMP_02, FX_DUST_JUMP_03, FX_DUST_JUMP_04, FX_DUST_JUMP_05, FX_DUST_JUMP_06, FX_DUST_JUMP_07, FX_DUST_JUMP_08, FX_DUST_JUMP_09, FX_DUST_JUMP_10, FX_DUST_PUSH_01, FX_DUST_PUSH_02, FX_DUST_PUSH_03, FX_DUST_PUSH_04, FX_DUST_PUSH_05, FX_DUST_PUSH_06, FX_DUST_PUSH_07, FX_DUST_PUSH_08, FX_DUST_PUSH_09, FX_DUST_SKID_01, FX_DUST_SKID_02, FX_DUST_SKID_03, FX_DUST_SKID_04, FX_DUST_SKID_05, FX_DUST_SKID_06, FX_DUST_SKID_07, FX_FIST_IN_01, FX_FIST_IN_02, FX_FIST_IN_03, FX_FIST_IN_04, FX_FIST_IN_05, FX_FIST_IN_06, FX_GROUND_EXPLODE_01_01, FX_GROUND_EXPLODE_01_02, FX_GROUND_EXPLODE_01_03, FX_GROUND_EXPLODE_01_04, FX_GROUND_EXPLODE_01_05, FX_GROUND_EXPLODE_01_06, FX_GROUND_EXPLODE_01_07, FX_GROUND_EXPLODE_01_08, FX_GROUND_EXPLODE_01_09, FX_GROUND_EXPLODE_01_10, FX_GROUND_EXPLODE_01_11, FX_GROUND_EXPLODE_02_01, FX_GROUND_EXPLODE_02_02, FX_GROUND_EXPLODE_02_03, FX_GROUND_EXPLODE_02_04, FX_GROUND_EXPLODE_02_05, FX_GROUND_EXPLODE_02_06, FX_GROUND_EXPLODE_02_07, FX_GROUND_EXPLODE_02_08, FX_GROUND_EXPLODE_02_09, FX_GROUND_EXPLODE_02_10, FX_GROUND_WAVE_01, FX_GROUND_WAVE_02, FX_GROUND_WAVE_03, FX_GROUND_WAVE_04, FX_GROUND_WAVE_05, FX_GROUND_WAVE_06, FX_GROUND_WAVE_07, FX_GROUND_WAVE_08, FX_GROUND_WAVE_09, FX_GROUND_WAVE_10, FX_GROUND_WAVE_11, FX_GROUND_WAVE_12, FX_HIT_01_01, FX_HIT_01_02, FX_HIT_01_03, FX_HIT_01_04, FX_HIT_02_01, FX_HIT_02_02, FX_HIT_02_03, FX_LIGHT_COLUMN_01, FX_LIGHT_COLUMN_02, FX_LIGHT_COLUMN_03, FX_LIGHT_COLUMN_04, FX_LIGHT_COLUMN_05, FX_LIGHT_COLUMN_06, FX_PUFF_01, FX_PUFF_02, FX_PUFF_03, FX_PUFF_04, FX_PUFF_05, FX_PUFF_06, FX_RAVEN_OBJ_COG_01, FX_RAVEN_OBJ_CONCRETE_LG_01, FX_RAVEN_OBJ_CONCRETE_SM_01, FX_RAVEN_OBJ_CRATE_01, FX_RAVEN_OBJ_ENGINE_01, FX_RAVEN_OBJ_HOTDOGCART_01, FX_RAVEN_OBJ_IBEAM_LG_01, FX_RAVEN_OBJ_IBEAM_SM_01, FX_RAVEN_OBJ_MACHINE_01, FX_RAVEN_OBJ_TIRE_01, FX_RAVEN_SWIRL_01, FX_RAVEN_SWIRL_02, FX_RAVEN_SWIRL_03, FX_RAVEN_SWIRL_04, FX_RAVEN_SWIRL_05, FX_RAVEN_SWIRL_06, FX_RAVEN_SWIRL_07, FX_RAVEN_SWIRL_08, FX_RAVEN_SWIRL_09, FX_RAVEN_SWIRL_10, FX_RAVEN_SWIRL_11, FX_RAVEN_SWIRL_12, FX_RAVEN_SWIRL_13, FX_RAVEN_SWIRL_14, FX_RAVEN_SWIRL_15, FX_RAVEN_SWIRL_16, FX_RAVEN_SWIRL_17, FX_RAVEN_SWIRL_18, FX_SHADOW, FX_STARFIRE_BOLT_02, FX_STARFIRE_BOLT_03, FX_STARFIRE_BOLT_04, FX_STARFIRE_BOLT_05, FX_STARFIRE_BOLT_06, FX_STARFIRE_BOLT_06A, FX_STARFIRE_COLUMN_01, FX_STARFIRE_COLUMN_02, FX_STARFIRE_COLUMN_03, FX_STARFIRE_COLUMN_05, FX_STARFIRE_COLUMN_FULL_01, FX_STARFIRE_COLUMN_FULL_02, FX_STARFIRE_EXPLODE_01, FX_STARFIRE_EXPLODE_02, FX_STARFIRE_EXPLODE_03, FX_STARFIRE_EXPLODE_04, FX_STARFIRE_EXPLODE_05, FX_STARFIRE_EXPLODE_06, FX_STARFIRE_EXPLODE_07, FX_STARFIRE_EXPLODE_08, FX_STARFIRE_EXPLODE_09, FX_STARFIRE_EXPLODE_10, FX_STARFIRE_EXPLODE_11, FX_STARFIRE_EXPLODE_12, FX_STARFIRE_EXPLODE_13, FX_STARFIRE_EXPLODE_14, FX_STARFIRE_EXPLODE_15, FX_STARFIRE_EXPLODE_16, FX_STARFIRE_EXPLODE_17, FX_STARFIRE_EXPLODE_18, FX_STARFIRE_EXPLODE_19, FX_STARFIRE_EXPLODE_20, FX_STARFIRE_EXPLODE_21, FX_STARFIRE_EXPLODE_22, fx_starfire_summon_glow_bg_01, FX_STARFIRE_SWEEP_01, FX_STARFIRE_SWEEP_02, RAVEN_SPECIAL_03, RAVEN_SPECIAL_04, RAVEN_SPECIAL_05, RAVEN_SPECIAL_06, RAVEN_SPECIAL_07, ROBIN_FLYINGKICK_01, ROBIN_FLYINGKICK_02, SFX_BEASTBOY_PTERODACTYL, SFX_RAVEN_FLINGOBJECT, SFX_RAVEN_OBJECTS_HIT_GROUND, SFX_RAVEN_VORTEX, SFX_ROBIN_FLYING_KICK_WOOSH, SFX_STARFIRE_BOLT_BARRAGE, SFX_STARFIRE_MAKINGSTARBOLT, STARFIRE_ATTACK_01, STARFIRE_ATTACK_02, STARFIRE_ATTACK_03, STARFIRE_ATTACK_04, STARFIRE_FLOAT_UP_01

on new me
  me.locateMembers()
  return me
end

on locateMembers me
  util = new(script("Class_Utility"))
  ASSET_CAST = "char_shared"
  BEASTBOY_PTERODACTYL_01 = util.findMember("beastboy_pterodactyl_01", ASSET_CAST)
  BEASTBOY_PTERODACTYL_02 = util.findMember("beastboy_pterodactyl_02", ASSET_CAST)
  BEASTBOY_PTERODACTYL_03 = util.findMember("beastboy_pterodactyl_03", ASSET_CAST)
  BG_EN_STRETCH_000 = util.findMember("bg_en_stretch_000", ASSET_CAST)
  BG_EN_STRETCH_001 = util.findMember("bg_en_stretch_001", ASSET_CAST)
  BG_EN_STRETCH_002 = util.findMember("bg_en_stretch_002", ASSET_CAST)
  BG_TITANS_STRETCH_000 = util.findMember("bg_titans_stretch_000", ASSET_CAST)
  BG_TITANS_STRETCH_001 = util.findMember("bg_titans_stretch_001", ASSET_CAST)
  BG_TITANS_STRETCH_002 = util.findMember("bg_titans_stretch_002", ASSET_CAST)
  CYBORG_JUMP_PUNCH_01 = util.findMember("cyborg_jump_punch_01", ASSET_CAST)
  CYBORG_JUMP_PUNCH_02 = util.findMember("cyborg_jump_punch_02", ASSET_CAST)
  CYBORG_JUMP_PUNCH_ALT_01 = util.findMember("cyborg_jump_punch_ALT_01", ASSET_CAST)
  CYBORG_JUMP_PUNCH_ALT_02 = util.findMember("cyborg_jump_punch_ALT_02", ASSET_CAST)
  FX_CYBORG_LINES_01 = util.findMember("fx_cyborg_lines_01", ASSET_CAST)
  FX_CYBORG_LINES_02 = util.findMember("fx_cyborg_lines_02", ASSET_CAST)
  FX_CYBORG_LINES_03 = util.findMember("fx_cyborg_lines_03", ASSET_CAST)
  FX_CYBORG_LINES_04 = util.findMember("fx_cyborg_lines_04", ASSET_CAST)
  FX_CYBORG_LINES_05 = util.findMember("fx_cyborg_lines_05", ASSET_CAST)
  FX_DUST_JUMP_01 = util.findMember("FX_dust_jump_01", ASSET_CAST)
  FX_DUST_JUMP_02 = util.findMember("FX_dust_jump_02", ASSET_CAST)
  FX_DUST_JUMP_03 = util.findMember("FX_dust_jump_03", ASSET_CAST)
  FX_DUST_JUMP_04 = util.findMember("FX_dust_jump_04", ASSET_CAST)
  FX_DUST_JUMP_05 = util.findMember("FX_dust_jump_05", ASSET_CAST)
  FX_DUST_JUMP_06 = util.findMember("FX_dust_jump_06", ASSET_CAST)
  FX_DUST_JUMP_07 = util.findMember("FX_dust_jump_07", ASSET_CAST)
  FX_DUST_JUMP_08 = util.findMember("FX_dust_jump_08", ASSET_CAST)
  FX_DUST_JUMP_09 = util.findMember("FX_dust_jump_09", ASSET_CAST)
  FX_DUST_JUMP_10 = util.findMember("FX_dust_jump_10", ASSET_CAST)
  FX_DUST_PUSH_01 = util.findMember("FX_dust_push_01", ASSET_CAST)
  FX_DUST_PUSH_02 = util.findMember("FX_dust_push_02", ASSET_CAST)
  FX_DUST_PUSH_03 = util.findMember("FX_dust_push_03", ASSET_CAST)
  FX_DUST_PUSH_04 = util.findMember("FX_dust_push_04", ASSET_CAST)
  FX_DUST_PUSH_05 = util.findMember("FX_dust_push_05", ASSET_CAST)
  FX_DUST_PUSH_06 = util.findMember("FX_dust_push_06", ASSET_CAST)
  FX_DUST_PUSH_07 = util.findMember("FX_dust_push_07", ASSET_CAST)
  FX_DUST_PUSH_08 = util.findMember("FX_dust_push_08", ASSET_CAST)
  FX_DUST_PUSH_09 = util.findMember("FX_dust_push_09", ASSET_CAST)
  FX_DUST_SKID_01 = util.findMember("FX_dust_skid_01", ASSET_CAST)
  FX_DUST_SKID_02 = util.findMember("FX_dust_skid_02", ASSET_CAST)
  FX_DUST_SKID_03 = util.findMember("FX_dust_skid_03", ASSET_CAST)
  FX_DUST_SKID_04 = util.findMember("FX_dust_skid_04", ASSET_CAST)
  FX_DUST_SKID_05 = util.findMember("FX_dust_skid_05", ASSET_CAST)
  FX_DUST_SKID_06 = util.findMember("FX_dust_skid_06", ASSET_CAST)
  FX_DUST_SKID_07 = util.findMember("FX_dust_skid_07", ASSET_CAST)
  FX_FIST_IN_01 = util.findMember("FX_fist_in_01", ASSET_CAST)
  FX_FIST_IN_02 = util.findMember("FX_fist_in_02", ASSET_CAST)
  FX_FIST_IN_03 = util.findMember("FX_fist_in_03", ASSET_CAST)
  FX_FIST_IN_04 = util.findMember("FX_fist_in_04", ASSET_CAST)
  FX_FIST_IN_05 = util.findMember("FX_fist_in_05", ASSET_CAST)
  FX_FIST_IN_06 = util.findMember("FX_fist_in_06", ASSET_CAST)
  FX_GROUND_EXPLODE_01_01 = util.findMember("fx_ground_explode_01_01", ASSET_CAST)
  FX_GROUND_EXPLODE_01_02 = util.findMember("fx_ground_explode_01_02", ASSET_CAST)
  FX_GROUND_EXPLODE_01_03 = util.findMember("fx_ground_explode_01_03", ASSET_CAST)
  FX_GROUND_EXPLODE_01_04 = util.findMember("fx_ground_explode_01_04", ASSET_CAST)
  FX_GROUND_EXPLODE_01_05 = util.findMember("fx_ground_explode_01_05", ASSET_CAST)
  FX_GROUND_EXPLODE_01_06 = util.findMember("fx_ground_explode_01_06", ASSET_CAST)
  FX_GROUND_EXPLODE_01_07 = util.findMember("fx_ground_explode_01_07", ASSET_CAST)
  FX_GROUND_EXPLODE_01_08 = util.findMember("fx_ground_explode_01_08", ASSET_CAST)
  FX_GROUND_EXPLODE_01_09 = util.findMember("fx_ground_explode_01_09", ASSET_CAST)
  FX_GROUND_EXPLODE_01_10 = util.findMember("fx_ground_explode_01_10", ASSET_CAST)
  FX_GROUND_EXPLODE_01_11 = util.findMember("fx_ground_explode_01_11", ASSET_CAST)
  FX_GROUND_EXPLODE_02_01 = util.findMember("fx_ground_explode_02_01", ASSET_CAST)
  FX_GROUND_EXPLODE_02_02 = util.findMember("fx_ground_explode_02_02", ASSET_CAST)
  FX_GROUND_EXPLODE_02_03 = util.findMember("fx_ground_explode_02_03", ASSET_CAST)
  FX_GROUND_EXPLODE_02_04 = util.findMember("fx_ground_explode_02_04", ASSET_CAST)
  FX_GROUND_EXPLODE_02_05 = util.findMember("fx_ground_explode_02_05", ASSET_CAST)
  FX_GROUND_EXPLODE_02_06 = util.findMember("fx_ground_explode_02_06", ASSET_CAST)
  FX_GROUND_EXPLODE_02_07 = util.findMember("fx_ground_explode_02_07", ASSET_CAST)
  FX_GROUND_EXPLODE_02_08 = util.findMember("fx_ground_explode_02_08", ASSET_CAST)
  FX_GROUND_EXPLODE_02_09 = util.findMember("fx_ground_explode_02_09", ASSET_CAST)
  FX_GROUND_EXPLODE_02_10 = util.findMember("fx_ground_explode_02_10", ASSET_CAST)
  FX_GROUND_WAVE_01 = util.findMember("fx_ground_wave_01", ASSET_CAST)
  FX_GROUND_WAVE_02 = util.findMember("fx_ground_wave_02", ASSET_CAST)
  FX_GROUND_WAVE_03 = util.findMember("fx_ground_wave_03", ASSET_CAST)
  FX_GROUND_WAVE_04 = util.findMember("fx_ground_wave_04", ASSET_CAST)
  FX_GROUND_WAVE_05 = util.findMember("fx_ground_wave_05", ASSET_CAST)
  FX_GROUND_WAVE_06 = util.findMember("fx_ground_wave_06", ASSET_CAST)
  FX_GROUND_WAVE_07 = util.findMember("fx_ground_wave_07", ASSET_CAST)
  FX_GROUND_WAVE_08 = util.findMember("fx_ground_wave_08", ASSET_CAST)
  FX_GROUND_WAVE_09 = util.findMember("fx_ground_wave_09", ASSET_CAST)
  FX_GROUND_WAVE_10 = util.findMember("fx_ground_wave_10", ASSET_CAST)
  FX_GROUND_WAVE_11 = util.findMember("fx_ground_wave_11", ASSET_CAST)
  FX_GROUND_WAVE_12 = util.findMember("fx_ground_wave_12", ASSET_CAST)
  FX_HIT_01_01 = util.findMember("FX_hit_01_01", ASSET_CAST)
  FX_HIT_01_02 = util.findMember("FX_hit_01_02", ASSET_CAST)
  FX_HIT_01_03 = util.findMember("FX_hit_01_03", ASSET_CAST)
  FX_HIT_01_04 = util.findMember("FX_hit_01_04", ASSET_CAST)
  FX_HIT_02_01 = util.findMember("FX_hit_02_01", ASSET_CAST)
  FX_HIT_02_02 = util.findMember("FX_hit_02_02", ASSET_CAST)
  FX_HIT_02_03 = util.findMember("FX_hit_02_03", ASSET_CAST)
  FX_LIGHT_COLUMN_01 = util.findMember("fx_light_column_01", ASSET_CAST)
  FX_LIGHT_COLUMN_02 = util.findMember("fx_light_column_02", ASSET_CAST)
  FX_LIGHT_COLUMN_03 = util.findMember("fx_light_column_03", ASSET_CAST)
  FX_LIGHT_COLUMN_04 = util.findMember("fx_light_column_04", ASSET_CAST)
  FX_LIGHT_COLUMN_05 = util.findMember("fx_light_column_05", ASSET_CAST)
  FX_LIGHT_COLUMN_06 = util.findMember("fx_light_column_06", ASSET_CAST)
  FX_PUFF_01 = util.findMember("FX_puff_01", ASSET_CAST)
  FX_PUFF_02 = util.findMember("FX_puff_02", ASSET_CAST)
  FX_PUFF_03 = util.findMember("FX_puff_03", ASSET_CAST)
  FX_PUFF_04 = util.findMember("FX_puff_04", ASSET_CAST)
  FX_PUFF_05 = util.findMember("FX_puff_05", ASSET_CAST)
  FX_PUFF_06 = util.findMember("FX_puff_06", ASSET_CAST)
  FX_RAVEN_OBJ_COG_01 = util.findMember("fx_raven_obj_cog_01", ASSET_CAST)
  FX_RAVEN_OBJ_CONCRETE_LG_01 = util.findMember("fx_raven_obj_concrete_lg_01", ASSET_CAST)
  FX_RAVEN_OBJ_CONCRETE_SM_01 = util.findMember("fx_raven_obj_concrete_sm_01", ASSET_CAST)
  FX_RAVEN_OBJ_CRATE_01 = util.findMember("fx_raven_obj_crate_01", ASSET_CAST)
  FX_RAVEN_OBJ_ENGINE_01 = util.findMember("fx_raven_obj_engine_01", ASSET_CAST)
  FX_RAVEN_OBJ_HOTDOGCART_01 = util.findMember("fx_raven_obj_hotdogcart_01", ASSET_CAST)
  FX_RAVEN_OBJ_IBEAM_LG_01 = util.findMember("fx_raven_obj_ibeam_lg_01", ASSET_CAST)
  FX_RAVEN_OBJ_IBEAM_SM_01 = util.findMember("fx_raven_obj_ibeam_sm_01", ASSET_CAST)
  FX_RAVEN_OBJ_MACHINE_01 = util.findMember("fx_raven_obj_machine_01", ASSET_CAST)
  FX_RAVEN_OBJ_TIRE_01 = util.findMember("fx_raven_obj_tire_01", ASSET_CAST)
  FX_RAVEN_SWIRL_01 = util.findMember("fx_raven_swirl_01", ASSET_CAST)
  FX_RAVEN_SWIRL_02 = util.findMember("fx_raven_swirl_02", ASSET_CAST)
  FX_RAVEN_SWIRL_03 = util.findMember("fx_raven_swirl_03", ASSET_CAST)
  FX_RAVEN_SWIRL_04 = util.findMember("fx_raven_swirl_04", ASSET_CAST)
  FX_RAVEN_SWIRL_05 = util.findMember("fx_raven_swirl_05", ASSET_CAST)
  FX_RAVEN_SWIRL_06 = util.findMember("fx_raven_swirl_06", ASSET_CAST)
  FX_RAVEN_SWIRL_07 = util.findMember("fx_raven_swirl_07", ASSET_CAST)
  FX_RAVEN_SWIRL_08 = util.findMember("fx_raven_swirl_08", ASSET_CAST)
  FX_RAVEN_SWIRL_09 = util.findMember("fx_raven_swirl_09", ASSET_CAST)
  FX_RAVEN_SWIRL_10 = util.findMember("fx_raven_swirl_10", ASSET_CAST)
  FX_RAVEN_SWIRL_11 = util.findMember("fx_raven_swirl_11", ASSET_CAST)
  FX_RAVEN_SWIRL_12 = util.findMember("fx_raven_swirl_12", ASSET_CAST)
  FX_RAVEN_SWIRL_13 = util.findMember("fx_raven_swirl_13", ASSET_CAST)
  FX_RAVEN_SWIRL_14 = util.findMember("fx_raven_swirl_14", ASSET_CAST)
  FX_RAVEN_SWIRL_15 = util.findMember("fx_raven_swirl_15", ASSET_CAST)
  FX_RAVEN_SWIRL_16 = util.findMember("fx_raven_swirl_16", ASSET_CAST)
  FX_RAVEN_SWIRL_17 = util.findMember("fx_raven_swirl_17", ASSET_CAST)
  FX_RAVEN_SWIRL_18 = util.findMember("fx_raven_swirl_18", ASSET_CAST)
  FX_SHADOW = util.findMember("FX_shadow", ASSET_CAST)
  FX_STARFIRE_BOLT_02 = util.findMember("fx_starfire_bolt_02", ASSET_CAST)
  FX_STARFIRE_BOLT_03 = util.findMember("fx_starfire_bolt_03", ASSET_CAST)
  FX_STARFIRE_BOLT_04 = util.findMember("fx_starfire_bolt_04", ASSET_CAST)
  FX_STARFIRE_BOLT_05 = util.findMember("fx_starfire_bolt_05", ASSET_CAST)
  FX_STARFIRE_BOLT_06 = util.findMember("fx_starfire_bolt_06", ASSET_CAST)
  FX_STARFIRE_BOLT_06A = util.findMember("fx_starfire_bolt_06a", ASSET_CAST)
  FX_STARFIRE_COLUMN_01 = util.findMember("fx_starfire_column_01", ASSET_CAST)
  FX_STARFIRE_COLUMN_02 = util.findMember("fx_starfire_column_02", ASSET_CAST)
  FX_STARFIRE_COLUMN_03 = util.findMember("fx_starfire_column_03", ASSET_CAST)
  FX_STARFIRE_COLUMN_05 = util.findMember("fx_starfire_column_05", ASSET_CAST)
  FX_STARFIRE_COLUMN_FULL_01 = util.findMember("fx_starfire_column_full_01", ASSET_CAST)
  FX_STARFIRE_COLUMN_FULL_02 = util.findMember("fx_starfire_column_full_02", ASSET_CAST)
  FX_STARFIRE_EXPLODE_01 = util.findMember("fx_starfire_explode_01", ASSET_CAST)
  FX_STARFIRE_EXPLODE_02 = util.findMember("fx_starfire_explode_02", ASSET_CAST)
  FX_STARFIRE_EXPLODE_03 = util.findMember("fx_starfire_explode_03", ASSET_CAST)
  FX_STARFIRE_EXPLODE_04 = util.findMember("fx_starfire_explode_04", ASSET_CAST)
  FX_STARFIRE_EXPLODE_05 = util.findMember("fx_starfire_explode_05", ASSET_CAST)
  FX_STARFIRE_EXPLODE_06 = util.findMember("fx_starfire_explode_06", ASSET_CAST)
  FX_STARFIRE_EXPLODE_07 = util.findMember("fx_starfire_explode_07", ASSET_CAST)
  FX_STARFIRE_EXPLODE_08 = util.findMember("fx_starfire_explode_08", ASSET_CAST)
  FX_STARFIRE_EXPLODE_09 = util.findMember("fx_starfire_explode_09", ASSET_CAST)
  FX_STARFIRE_EXPLODE_10 = util.findMember("fx_starfire_explode_10", ASSET_CAST)
  FX_STARFIRE_EXPLODE_11 = util.findMember("fx_starfire_explode_11", ASSET_CAST)
  FX_STARFIRE_EXPLODE_12 = util.findMember("fx_starfire_explode_12", ASSET_CAST)
  FX_STARFIRE_EXPLODE_13 = util.findMember("fx_starfire_explode_13", ASSET_CAST)
  FX_STARFIRE_EXPLODE_14 = util.findMember("fx_starfire_explode_14", ASSET_CAST)
  FX_STARFIRE_EXPLODE_15 = util.findMember("fx_starfire_explode_15", ASSET_CAST)
  FX_STARFIRE_EXPLODE_16 = util.findMember("fx_starfire_explode_16", ASSET_CAST)
  FX_STARFIRE_EXPLODE_17 = util.findMember("fx_starfire_explode_17", ASSET_CAST)
  FX_STARFIRE_EXPLODE_18 = util.findMember("fx_starfire_explode_18", ASSET_CAST)
  FX_STARFIRE_EXPLODE_19 = util.findMember("fx_starfire_explode_19", ASSET_CAST)
  FX_STARFIRE_EXPLODE_20 = util.findMember("fx_starfire_explode_20", ASSET_CAST)
  FX_STARFIRE_EXPLODE_21 = util.findMember("fx_starfire_explode_21", ASSET_CAST)
  FX_STARFIRE_EXPLODE_22 = util.findMember("fx_starfire_explode_22", ASSET_CAST)
  fx_starfire_summon_glow_bg_01 = util.findMember("fx_starfire_summon_glow_bg_01", ASSET_CAST)
  FX_STARFIRE_SWEEP_01 = util.findMember("fx_starfire_sweep_01", ASSET_CAST)
  FX_STARFIRE_SWEEP_02 = util.findMember("fx_starfire_sweep_02", ASSET_CAST)
  RAVEN_SPECIAL_03 = util.findMember("raven_special_03", ASSET_CAST)
  RAVEN_SPECIAL_04 = util.findMember("raven_special_04", ASSET_CAST)
  RAVEN_SPECIAL_05 = util.findMember("raven_special_05", ASSET_CAST)
  RAVEN_SPECIAL_06 = util.findMember("raven_special_06", ASSET_CAST)
  RAVEN_SPECIAL_07 = util.findMember("raven_special_07", ASSET_CAST)
  ROBIN_FLYINGKICK_01 = util.findMember("robin_flyingkick_01", ASSET_CAST)
  ROBIN_FLYINGKICK_02 = util.findMember("robin_flyingkick_02", ASSET_CAST)
  SFX_BEASTBOY_PTERODACTYL = util.findMember("sfx_beastboy_pterodactyl", ASSET_CAST)
  SFX_RAVEN_FLINGOBJECT = util.findMember("sfx_raven_flingobject", ASSET_CAST)
  SFX_RAVEN_OBJECTS_HIT_GROUND = util.findMember("sfx_raven_objects_hit_ground", ASSET_CAST)
  SFX_RAVEN_VORTEX = util.findMember("sfx_raven_vortex", ASSET_CAST)
  SFX_ROBIN_FLYING_KICK_WOOSH = util.findMember("sfx_robin_flying_kick_woosh", ASSET_CAST)
  SFX_STARFIRE_BOLT_BARRAGE = util.findMember("sfx_starfire_bolt_barrage", ASSET_CAST)
  SFX_STARFIRE_MAKINGSTARBOLT = util.findMember("sfx_starfire_makingstarbolt", ASSET_CAST)
  STARFIRE_ATTACK_01 = util.findMember("starfire_attack_01", ASSET_CAST)
  STARFIRE_ATTACK_02 = util.findMember("starfire_attack_02", ASSET_CAST)
  STARFIRE_ATTACK_03 = util.findMember("starfire_attack_03", ASSET_CAST)
  STARFIRE_ATTACK_04 = util.findMember("starfire_attack_04", ASSET_CAST)
  STARFIRE_FLOAT_UP_01 = util.findMember("starfire_float_up_01", ASSET_CAST)
end

on precache me
  preloadMember(BEASTBOY_PTERODACTYL_01)
  preloadMember(BEASTBOY_PTERODACTYL_02)
  preloadMember(BEASTBOY_PTERODACTYL_03)
  preloadMember(BG_EN_STRETCH_000)
  preloadMember(BG_EN_STRETCH_001)
  preloadMember(BG_EN_STRETCH_002)
  preloadMember(BG_TITANS_STRETCH_000)
  preloadMember(BG_TITANS_STRETCH_001)
  preloadMember(BG_TITANS_STRETCH_002)
  preloadMember(CYBORG_JUMP_PUNCH_01)
  preloadMember(CYBORG_JUMP_PUNCH_02)
  preloadMember(CYBORG_JUMP_PUNCH_ALT_01)
  preloadMember(CYBORG_JUMP_PUNCH_ALT_02)
  preloadMember(FX_CYBORG_LINES_01)
  preloadMember(FX_CYBORG_LINES_02)
  preloadMember(FX_CYBORG_LINES_03)
  preloadMember(FX_CYBORG_LINES_04)
  preloadMember(FX_CYBORG_LINES_05)
  preloadMember(FX_DUST_JUMP_01)
  preloadMember(FX_DUST_JUMP_02)
  preloadMember(FX_DUST_JUMP_03)
  preloadMember(FX_DUST_JUMP_04)
  preloadMember(FX_DUST_JUMP_05)
  preloadMember(FX_DUST_JUMP_06)
  preloadMember(FX_DUST_JUMP_07)
  preloadMember(FX_DUST_JUMP_08)
  preloadMember(FX_DUST_JUMP_09)
  preloadMember(FX_DUST_JUMP_10)
  preloadMember(FX_DUST_PUSH_01)
  preloadMember(FX_DUST_PUSH_02)
  preloadMember(FX_DUST_PUSH_03)
  preloadMember(FX_DUST_PUSH_04)
  preloadMember(FX_DUST_PUSH_05)
  preloadMember(FX_DUST_PUSH_06)
  preloadMember(FX_DUST_PUSH_07)
  preloadMember(FX_DUST_PUSH_08)
  preloadMember(FX_DUST_PUSH_09)
  preloadMember(FX_DUST_SKID_01)
  preloadMember(FX_DUST_SKID_02)
  preloadMember(FX_DUST_SKID_03)
  preloadMember(FX_DUST_SKID_04)
  preloadMember(FX_DUST_SKID_05)
  preloadMember(FX_DUST_SKID_06)
  preloadMember(FX_DUST_SKID_07)
  preloadMember(FX_FIST_IN_01)
  preloadMember(FX_FIST_IN_02)
  preloadMember(FX_FIST_IN_03)
  preloadMember(FX_FIST_IN_04)
  preloadMember(FX_FIST_IN_05)
  preloadMember(FX_FIST_IN_06)
  preloadMember(FX_GROUND_EXPLODE_01_01)
  preloadMember(FX_GROUND_EXPLODE_01_02)
  preloadMember(FX_GROUND_EXPLODE_01_03)
  preloadMember(FX_GROUND_EXPLODE_01_04)
  preloadMember(FX_GROUND_EXPLODE_01_05)
  preloadMember(FX_GROUND_EXPLODE_01_06)
  preloadMember(FX_GROUND_EXPLODE_01_07)
  preloadMember(FX_GROUND_EXPLODE_01_08)
  preloadMember(FX_GROUND_EXPLODE_01_09)
  preloadMember(FX_GROUND_EXPLODE_01_10)
  preloadMember(FX_GROUND_EXPLODE_01_11)
  preloadMember(FX_GROUND_EXPLODE_02_01)
  preloadMember(FX_GROUND_EXPLODE_02_02)
  preloadMember(FX_GROUND_EXPLODE_02_03)
  preloadMember(FX_GROUND_EXPLODE_02_04)
  preloadMember(FX_GROUND_EXPLODE_02_05)
  preloadMember(FX_GROUND_EXPLODE_02_06)
  preloadMember(FX_GROUND_EXPLODE_02_07)
  preloadMember(FX_GROUND_EXPLODE_02_08)
  preloadMember(FX_GROUND_EXPLODE_02_09)
  preloadMember(FX_GROUND_EXPLODE_02_10)
  preloadMember(FX_GROUND_WAVE_01)
  preloadMember(FX_GROUND_WAVE_02)
  preloadMember(FX_GROUND_WAVE_03)
  preloadMember(FX_GROUND_WAVE_04)
  preloadMember(FX_GROUND_WAVE_05)
  preloadMember(FX_GROUND_WAVE_06)
  preloadMember(FX_GROUND_WAVE_07)
  preloadMember(FX_GROUND_WAVE_08)
  preloadMember(FX_GROUND_WAVE_09)
  preloadMember(FX_GROUND_WAVE_10)
  preloadMember(FX_GROUND_WAVE_11)
  preloadMember(FX_GROUND_WAVE_12)
  preloadMember(FX_HIT_01_01)
  preloadMember(FX_HIT_01_02)
  preloadMember(FX_HIT_01_03)
  preloadMember(FX_HIT_01_04)
  preloadMember(FX_HIT_02_01)
  preloadMember(FX_HIT_02_02)
  preloadMember(FX_HIT_02_03)
  preloadMember(FX_LIGHT_COLUMN_01)
  preloadMember(FX_LIGHT_COLUMN_02)
  preloadMember(FX_LIGHT_COLUMN_03)
  preloadMember(FX_LIGHT_COLUMN_04)
  preloadMember(FX_LIGHT_COLUMN_05)
  preloadMember(FX_LIGHT_COLUMN_06)
  preloadMember(FX_PUFF_01)
  preloadMember(FX_PUFF_02)
  preloadMember(FX_PUFF_03)
  preloadMember(FX_PUFF_04)
  preloadMember(FX_PUFF_05)
  preloadMember(FX_PUFF_06)
  preloadMember(FX_RAVEN_OBJ_COG_01)
  preloadMember(FX_RAVEN_OBJ_CONCRETE_LG_01)
  preloadMember(FX_RAVEN_OBJ_CONCRETE_SM_01)
  preloadMember(FX_RAVEN_OBJ_CRATE_01)
  preloadMember(FX_RAVEN_OBJ_ENGINE_01)
  preloadMember(FX_RAVEN_OBJ_HOTDOGCART_01)
  preloadMember(FX_RAVEN_OBJ_IBEAM_LG_01)
  preloadMember(FX_RAVEN_OBJ_IBEAM_SM_01)
  preloadMember(FX_RAVEN_OBJ_MACHINE_01)
  preloadMember(FX_RAVEN_OBJ_TIRE_01)
  preloadMember(FX_RAVEN_SWIRL_01)
  preloadMember(FX_RAVEN_SWIRL_02)
  preloadMember(FX_RAVEN_SWIRL_03)
  preloadMember(FX_RAVEN_SWIRL_04)
  preloadMember(FX_RAVEN_SWIRL_05)
  preloadMember(FX_RAVEN_SWIRL_06)
  preloadMember(FX_RAVEN_SWIRL_07)
  preloadMember(FX_RAVEN_SWIRL_08)
  preloadMember(FX_RAVEN_SWIRL_09)
  preloadMember(FX_RAVEN_SWIRL_10)
  preloadMember(FX_RAVEN_SWIRL_11)
  preloadMember(FX_RAVEN_SWIRL_12)
  preloadMember(FX_RAVEN_SWIRL_13)
  preloadMember(FX_RAVEN_SWIRL_14)
  preloadMember(FX_RAVEN_SWIRL_15)
  preloadMember(FX_RAVEN_SWIRL_16)
  preloadMember(FX_RAVEN_SWIRL_17)
  preloadMember(FX_RAVEN_SWIRL_18)
  preloadMember(FX_SHADOW)
  preloadMember(FX_STARFIRE_BOLT_02)
  preloadMember(FX_STARFIRE_BOLT_03)
  preloadMember(FX_STARFIRE_BOLT_04)
  preloadMember(FX_STARFIRE_BOLT_05)
  preloadMember(FX_STARFIRE_BOLT_06)
  preloadMember(FX_STARFIRE_BOLT_06A)
  preloadMember(FX_STARFIRE_COLUMN_01)
  preloadMember(FX_STARFIRE_COLUMN_02)
  preloadMember(FX_STARFIRE_COLUMN_03)
  preloadMember(FX_STARFIRE_COLUMN_05)
  preloadMember(FX_STARFIRE_COLUMN_FULL_01)
  preloadMember(FX_STARFIRE_COLUMN_FULL_02)
  preloadMember(FX_STARFIRE_EXPLODE_01)
  preloadMember(FX_STARFIRE_EXPLODE_02)
  preloadMember(FX_STARFIRE_EXPLODE_03)
  preloadMember(FX_STARFIRE_EXPLODE_04)
  preloadMember(FX_STARFIRE_EXPLODE_05)
  preloadMember(FX_STARFIRE_EXPLODE_06)
  preloadMember(FX_STARFIRE_EXPLODE_07)
  preloadMember(FX_STARFIRE_EXPLODE_08)
  preloadMember(FX_STARFIRE_EXPLODE_09)
  preloadMember(FX_STARFIRE_EXPLODE_10)
  preloadMember(FX_STARFIRE_EXPLODE_11)
  preloadMember(FX_STARFIRE_EXPLODE_12)
  preloadMember(FX_STARFIRE_EXPLODE_13)
  preloadMember(FX_STARFIRE_EXPLODE_14)
  preloadMember(FX_STARFIRE_EXPLODE_15)
  preloadMember(FX_STARFIRE_EXPLODE_16)
  preloadMember(FX_STARFIRE_EXPLODE_17)
  preloadMember(FX_STARFIRE_EXPLODE_18)
  preloadMember(FX_STARFIRE_EXPLODE_19)
  preloadMember(FX_STARFIRE_EXPLODE_20)
  preloadMember(FX_STARFIRE_EXPLODE_21)
  preloadMember(FX_STARFIRE_EXPLODE_22)
  preloadMember(fx_starfire_summon_glow_bg_01)
  preloadMember(FX_STARFIRE_SWEEP_01)
  preloadMember(FX_STARFIRE_SWEEP_02)
  preloadMember(RAVEN_SPECIAL_03)
  preloadMember(RAVEN_SPECIAL_04)
  preloadMember(RAVEN_SPECIAL_05)
  preloadMember(RAVEN_SPECIAL_06)
  preloadMember(RAVEN_SPECIAL_07)
  preloadMember(ROBIN_FLYINGKICK_01)
  preloadMember(ROBIN_FLYINGKICK_02)
  preloadMember(SFX_BEASTBOY_PTERODACTYL)
  preloadMember(SFX_RAVEN_FLINGOBJECT)
  preloadMember(SFX_RAVEN_OBJECTS_HIT_GROUND)
  preloadMember(SFX_RAVEN_VORTEX)
  preloadMember(SFX_ROBIN_FLYING_KICK_WOOSH)
  preloadMember(SFX_STARFIRE_BOLT_BARRAGE)
  preloadMember(SFX_STARFIRE_MAKINGSTARBOLT)
  preloadMember(STARFIRE_ATTACK_01)
  preloadMember(STARFIRE_ATTACK_02)
  preloadMember(STARFIRE_ATTACK_03)
  preloadMember(STARFIRE_ATTACK_04)
  preloadMember(STARFIRE_FLOAT_UP_01)
end
