property FX_JINX_ENERGYBALL_01, FX_JINX_ENERGYBALL_02, FX_JINX_ENERGYBALL_03, FX_JINX_ENERGYBALL_04, FX_JINX_ENERGYBALL_05, FX_JINX_ENERGYBALL_06, FX_JINX_ENERGYBALL_07, FX_JINX_ENERGYBALL_08, FX_JINX_ENERGYBALL_09, FX_JINX_ENERGYBALL_10, FX_JINX_ENERGYBALL_11, FX_JINX_ENERGYBALL_12, FX_JINX_ENERGYBALL_12A, FX_JINX_ENERGYBALL_13, FX_JINX_ENERGYBALL_14, FX_JINX_ENERGYBALL_15, FX_JINX_ENERGYBALL_16, FX_JINX_ENERGYBALL_17, FX_JINX_ENERGYBALL_18, FX_JINX_ENERGYBALL_19, FX_JINX_ENERGYBALL_20, FX_JINX_ENERGYBALL_21, FX_JINX_ENERGYBALL_22, FX_JINX_ENERGYBALL_23, FX_JINX_ENERGYBALL_24, FX_JINX_ENERGYBALL_25, FX_JINX_ENERGYBALL_26, FX_JINX_ENERGYBALL_27, FX_JINX_ENERGYBALL_28, FX_JINX_ENERGYBALL_29, FX_JINX_ENERGYBALL_30, FX_JINX_ENERGYBALL_31, FX_JINX_ENERGYBALL_32, FX_JINX_ENERGYBALL_33, FX_JINX_ENERGYBALL_34, FX_JINX_ENERGYBALL_35, FX_JINX_TWIRL_06, FX_JINX_TWIRL_07, FX_JINX_TWIRL_08, FX_JINX_TWIRL_09, FX_JINX_TWIRL_10, FX_JINX_TWIRL_11, FX_JINX_TWIRL_12, FX_JINX_TWIRL_13, FX_JINX_TWIRL_14, FX_JINX_TWIRL_15, FX_JINX_TWIRL_16, FX_JINX_TWIRL_17, FX_JINX_TWIRL_18, FX_JINX_TWIRL_19, JINX_BACKGROUND, JINX_FALL_01, JINX_FALL_01D, JINX_FALL_02, JINX_FALL_02D, JINX_FALL_03, JINX_FALL_03D, JINX_HIT_01, JINX_HIT_01D, JINX_JUMP_01, JINX_JUMP_01D, JINX_JUMP_02, JINX_JUMP_02D, JINX_JUMP_03, JINX_JUMP_03D, JINX_JUMP_04, JINX_JUMP_04D, JINX_JUMP_05, JINX_JUMP_05D, JINX_JUMP_06, JINX_JUMP_06D, JINX_KICK_01, JINX_KICK_01D, JINX_KICK_02, JINX_KICK_02D, JINX_KICK_03, JINX_KICK_03D, JINX_KICK_04, JINX_KICK_04A, JINX_KICK_04D, JINX_KICK_05, JINX_KICK_05D, JINX_KICK_06, JINX_KICK_06D, JINX_KICK_07, JINX_KICK_07D, JINX_NEWFIST_01, JINX_NEWFIST_02, JINX_NEWFIST_03, JINX_NEWFIST_04, JINX_NEWFIST_05, JINX_NEWFIST_06, JINX_NEWFIST_07, JINX_NEWFIST_08, JINX_NEWFIST_09, JINX_NEWFIST_10, JINX_PUNCH_01, JINX_PUNCH_01D, JINX_PUNCH_02, JINX_PUNCH_02A, JINX_PUNCH_02D, JINX_PUNCH_03, JINX_PUNCH_03D, JINX_SPIN_01, JINX_SPIN_01D, JINX_SPIN_02, JINX_SPIN_02A, JINX_SPIN_02D, JINX_SPIN_03, JINX_SPIN_03A, JINX_SPIN_03D, JINX_SPIN_04, JINX_SPIN_04A, JINX_SPIN_04D, JINX_SPIN_05, JINX_SPIN_05A, JINX_SPIN_05D, JINX_STAND_01, JINX_STAND_01D, JINX_WALK_01, JINX_WALK_02, JINX_WALK_03, JINX_WALK_04, JINX_WALK_05, JINX_WALK_06, JINX_WALK_07, JINX_WALK_08, SFX_JINX_BG_CROWDNOISE3, SFX_JINX_ENERGY_BALL_HIT, SFX_JINX_ENERGY_BALL_MISS, SFX_JINX_ENERGY_SPIN, SFX_JINX_FLYING_KICK, SFX_JINX_MAKE_ENERGY_BALL, SFX_JINX_RELEASE_ENERGY_BALL

on new me
  me.locateMembers()
  return me
end

on locateMembers me
  util = new(script("Class_Utility"))
  ASSET_CAST = "char_Jinx"
  FX_JINX_ENERGYBALL_01 = util.findMember("FX_jinx_energyball_01", ASSET_CAST)
  FX_JINX_ENERGYBALL_02 = util.findMember("FX_jinx_energyball_02", ASSET_CAST)
  FX_JINX_ENERGYBALL_03 = util.findMember("FX_jinx_energyball_03", ASSET_CAST)
  FX_JINX_ENERGYBALL_04 = util.findMember("FX_jinx_energyball_04", ASSET_CAST)
  FX_JINX_ENERGYBALL_05 = util.findMember("FX_jinx_energyball_05", ASSET_CAST)
  FX_JINX_ENERGYBALL_06 = util.findMember("FX_jinx_energyball_06", ASSET_CAST)
  FX_JINX_ENERGYBALL_07 = util.findMember("FX_jinx_energyball_07", ASSET_CAST)
  FX_JINX_ENERGYBALL_08 = util.findMember("FX_jinx_energyball_08", ASSET_CAST)
  FX_JINX_ENERGYBALL_09 = util.findMember("FX_jinx_energyball_09", ASSET_CAST)
  FX_JINX_ENERGYBALL_10 = util.findMember("FX_jinx_energyball_10", ASSET_CAST)
  FX_JINX_ENERGYBALL_11 = util.findMember("FX_jinx_energyball_11", ASSET_CAST)
  FX_JINX_ENERGYBALL_12 = util.findMember("FX_jinx_energyball_12", ASSET_CAST)
  FX_JINX_ENERGYBALL_12A = util.findMember("FX_jinx_energyball_12a", ASSET_CAST)
  FX_JINX_ENERGYBALL_13 = util.findMember("FX_jinx_energyball_13", ASSET_CAST)
  FX_JINX_ENERGYBALL_14 = util.findMember("FX_jinx_energyball_14", ASSET_CAST)
  FX_JINX_ENERGYBALL_15 = util.findMember("FX_jinx_energyball_15", ASSET_CAST)
  FX_JINX_ENERGYBALL_16 = util.findMember("FX_jinx_energyball_16", ASSET_CAST)
  FX_JINX_ENERGYBALL_17 = util.findMember("FX_jinx_energyball_17", ASSET_CAST)
  FX_JINX_ENERGYBALL_18 = util.findMember("FX_jinx_energyball_18", ASSET_CAST)
  FX_JINX_ENERGYBALL_19 = util.findMember("FX_jinx_energyball_19", ASSET_CAST)
  FX_JINX_ENERGYBALL_20 = util.findMember("FX_jinx_energyball_20", ASSET_CAST)
  FX_JINX_ENERGYBALL_21 = util.findMember("FX_jinx_energyball_21", ASSET_CAST)
  FX_JINX_ENERGYBALL_22 = util.findMember("FX_jinx_energyball_22", ASSET_CAST)
  FX_JINX_ENERGYBALL_23 = util.findMember("FX_jinx_energyball_23", ASSET_CAST)
  FX_JINX_ENERGYBALL_24 = util.findMember("FX_jinx_energyball_24", ASSET_CAST)
  FX_JINX_ENERGYBALL_25 = util.findMember("FX_jinx_energyball_25", ASSET_CAST)
  FX_JINX_ENERGYBALL_26 = util.findMember("FX_jinx_energyball_26", ASSET_CAST)
  FX_JINX_ENERGYBALL_27 = util.findMember("FX_jinx_energyball_27", ASSET_CAST)
  FX_JINX_ENERGYBALL_28 = util.findMember("FX_jinx_energyball_28", ASSET_CAST)
  FX_JINX_ENERGYBALL_29 = util.findMember("FX_jinx_energyball_29", ASSET_CAST)
  FX_JINX_ENERGYBALL_30 = util.findMember("FX_jinx_energyball_30", ASSET_CAST)
  FX_JINX_ENERGYBALL_31 = util.findMember("FX_jinx_energyball_31", ASSET_CAST)
  FX_JINX_ENERGYBALL_32 = util.findMember("FX_jinx_energyball_32", ASSET_CAST)
  FX_JINX_ENERGYBALL_33 = util.findMember("FX_jinx_energyball_33", ASSET_CAST)
  FX_JINX_ENERGYBALL_34 = util.findMember("FX_jinx_energyball_34", ASSET_CAST)
  FX_JINX_ENERGYBALL_35 = util.findMember("FX_jinx_energyball_35", ASSET_CAST)
  FX_JINX_TWIRL_06 = util.findMember("FX_jinx_twirl_06", ASSET_CAST)
  FX_JINX_TWIRL_07 = util.findMember("FX_jinx_twirl_07", ASSET_CAST)
  FX_JINX_TWIRL_08 = util.findMember("FX_jinx_twirl_08", ASSET_CAST)
  FX_JINX_TWIRL_09 = util.findMember("FX_jinx_twirl_09", ASSET_CAST)
  FX_JINX_TWIRL_10 = util.findMember("FX_jinx_twirl_10", ASSET_CAST)
  FX_JINX_TWIRL_11 = util.findMember("FX_jinx_twirl_11", ASSET_CAST)
  FX_JINX_TWIRL_12 = util.findMember("FX_jinx_twirl_12", ASSET_CAST)
  FX_JINX_TWIRL_13 = util.findMember("FX_jinx_twirl_13", ASSET_CAST)
  FX_JINX_TWIRL_14 = util.findMember("FX_jinx_twirl_14", ASSET_CAST)
  FX_JINX_TWIRL_15 = util.findMember("FX_jinx_twirl_15", ASSET_CAST)
  FX_JINX_TWIRL_16 = util.findMember("FX_jinx_twirl_16", ASSET_CAST)
  FX_JINX_TWIRL_17 = util.findMember("FX_jinx_twirl_17", ASSET_CAST)
  FX_JINX_TWIRL_18 = util.findMember("FX_jinx_twirl_18", ASSET_CAST)
  FX_JINX_TWIRL_19 = util.findMember("FX_jinx_twirl_19", ASSET_CAST)
  JINX_BACKGROUND = util.findMember("jinx_background", ASSET_CAST)
  JINX_FALL_01 = util.findMember("jinx_fall_01", ASSET_CAST)
  JINX_FALL_01D = util.findMember("jinx_fall_01d", ASSET_CAST)
  JINX_FALL_02 = util.findMember("jinx_fall_02", ASSET_CAST)
  JINX_FALL_02D = util.findMember("jinx_fall_02d", ASSET_CAST)
  JINX_FALL_03 = util.findMember("jinx_fall_03", ASSET_CAST)
  JINX_FALL_03D = util.findMember("jinx_fall_03d", ASSET_CAST)
  JINX_HIT_01 = util.findMember("jinx_hit_01", ASSET_CAST)
  JINX_HIT_01D = util.findMember("jinx_hit_01d", ASSET_CAST)
  JINX_JUMP_01 = util.findMember("jinx_jump_01", ASSET_CAST)
  JINX_JUMP_01D = util.findMember("jinx_jump_01d", ASSET_CAST)
  JINX_JUMP_02 = util.findMember("jinx_jump_02", ASSET_CAST)
  JINX_JUMP_02D = util.findMember("jinx_jump_02d", ASSET_CAST)
  JINX_JUMP_03 = util.findMember("jinx_jump_03", ASSET_CAST)
  JINX_JUMP_03D = util.findMember("jinx_jump_03d", ASSET_CAST)
  JINX_JUMP_04 = util.findMember("jinx_jump_04", ASSET_CAST)
  JINX_JUMP_04D = util.findMember("jinx_jump_04d", ASSET_CAST)
  JINX_JUMP_05 = util.findMember("jinx_jump_05", ASSET_CAST)
  JINX_JUMP_05D = util.findMember("jinx_jump_05d", ASSET_CAST)
  JINX_JUMP_06 = util.findMember("jinx_jump_06", ASSET_CAST)
  JINX_JUMP_06D = util.findMember("jinx_jump_06d", ASSET_CAST)
  JINX_KICK_01 = util.findMember("jinx_kick_01", ASSET_CAST)
  JINX_KICK_01D = util.findMember("jinx_kick_01d", ASSET_CAST)
  JINX_KICK_02 = util.findMember("jinx_kick_02", ASSET_CAST)
  JINX_KICK_02D = util.findMember("jinx_kick_02d", ASSET_CAST)
  JINX_KICK_03 = util.findMember("jinx_kick_03", ASSET_CAST)
  JINX_KICK_03D = util.findMember("jinx_kick_03d", ASSET_CAST)
  JINX_KICK_04 = util.findMember("jinx_kick_04", ASSET_CAST)
  JINX_KICK_04A = util.findMember("jinx_kick_04a", ASSET_CAST)
  JINX_KICK_04D = util.findMember("jinx_kick_04d", ASSET_CAST)
  JINX_KICK_05 = util.findMember("jinx_kick_05", ASSET_CAST)
  JINX_KICK_05D = util.findMember("jinx_kick_05d", ASSET_CAST)
  JINX_KICK_06 = util.findMember("jinx_kick_06", ASSET_CAST)
  JINX_KICK_06D = util.findMember("jinx_kick_06d", ASSET_CAST)
  JINX_KICK_07 = util.findMember("jinx_kick_07", ASSET_CAST)
  JINX_KICK_07D = util.findMember("jinx_kick_07d", ASSET_CAST)
  JINX_NEWFIST_01 = util.findMember("jinx_newfist_01", ASSET_CAST)
  JINX_NEWFIST_02 = util.findMember("jinx_newfist_02", ASSET_CAST)
  JINX_NEWFIST_03 = util.findMember("jinx_newfist_03", ASSET_CAST)
  JINX_NEWFIST_04 = util.findMember("jinx_newfist_04", ASSET_CAST)
  JINX_NEWFIST_05 = util.findMember("jinx_newfist_05", ASSET_CAST)
  JINX_NEWFIST_06 = util.findMember("jinx_newfist_06", ASSET_CAST)
  JINX_NEWFIST_07 = util.findMember("jinx_newfist_07", ASSET_CAST)
  JINX_NEWFIST_08 = util.findMember("jinx_newfist_08", ASSET_CAST)
  JINX_NEWFIST_09 = util.findMember("jinx_newfist_09", ASSET_CAST)
  JINX_NEWFIST_10 = util.findMember("jinx_newfist_10", ASSET_CAST)
  JINX_PUNCH_01 = util.findMember("jinx_punch_01", ASSET_CAST)
  JINX_PUNCH_01D = util.findMember("jinx_punch_01d", ASSET_CAST)
  JINX_PUNCH_02 = util.findMember("jinx_punch_02", ASSET_CAST)
  JINX_PUNCH_02A = util.findMember("jinx_punch_02a", ASSET_CAST)
  JINX_PUNCH_02D = util.findMember("jinx_punch_02d", ASSET_CAST)
  JINX_PUNCH_03 = util.findMember("jinx_punch_03", ASSET_CAST)
  JINX_PUNCH_03D = util.findMember("jinx_punch_03d", ASSET_CAST)
  JINX_SPIN_01 = util.findMember("jinx_spin_01", ASSET_CAST)
  JINX_SPIN_01D = util.findMember("jinx_spin_01d", ASSET_CAST)
  JINX_SPIN_02 = util.findMember("jinx_spin_02", ASSET_CAST)
  JINX_SPIN_02A = util.findMember("jinx_spin_02a", ASSET_CAST)
  JINX_SPIN_02D = util.findMember("jinx_spin_02d", ASSET_CAST)
  JINX_SPIN_03 = util.findMember("jinx_spin_03", ASSET_CAST)
  JINX_SPIN_03A = util.findMember("jinx_spin_03a", ASSET_CAST)
  JINX_SPIN_03D = util.findMember("jinx_spin_03d", ASSET_CAST)
  JINX_SPIN_04 = util.findMember("jinx_spin_04", ASSET_CAST)
  JINX_SPIN_04A = util.findMember("jinx_spin_04a", ASSET_CAST)
  JINX_SPIN_04D = util.findMember("jinx_spin_04d", ASSET_CAST)
  JINX_SPIN_05 = util.findMember("jinx_spin_05", ASSET_CAST)
  JINX_SPIN_05A = util.findMember("jinx_spin_05a", ASSET_CAST)
  JINX_SPIN_05D = util.findMember("jinx_spin_05d", ASSET_CAST)
  JINX_STAND_01 = util.findMember("jinx_stand_01", ASSET_CAST)
  JINX_STAND_01D = util.findMember("jinx_stand_01d", ASSET_CAST)
  JINX_WALK_01 = util.findMember("jinx_walk_01", ASSET_CAST)
  JINX_WALK_02 = util.findMember("jinx_walk_02", ASSET_CAST)
  JINX_WALK_03 = util.findMember("jinx_walk_03", ASSET_CAST)
  JINX_WALK_04 = util.findMember("jinx_walk_04", ASSET_CAST)
  JINX_WALK_05 = util.findMember("jinx_walk_05", ASSET_CAST)
  JINX_WALK_06 = util.findMember("jinx_walk_06", ASSET_CAST)
  JINX_WALK_07 = util.findMember("jinx_walk_07", ASSET_CAST)
  JINX_WALK_08 = util.findMember("jinx_walk_08", ASSET_CAST)
  SFX_JINX_BG_CROWDNOISE3 = util.findMember("sfx_jinx_bg_crowdnoise3", ASSET_CAST)
  SFX_JINX_ENERGY_BALL_HIT = util.findMember("sfx_jinx_energy_ball_hit", ASSET_CAST)
  SFX_JINX_ENERGY_BALL_MISS = util.findMember("sfx_jinx_energy_ball_miss", ASSET_CAST)
  SFX_JINX_ENERGY_SPIN = util.findMember("sfx_jinx_energy_spin", ASSET_CAST)
  SFX_JINX_FLYING_KICK = util.findMember("sfx_jinx_flying_kick", ASSET_CAST)
  SFX_JINX_MAKE_ENERGY_BALL = util.findMember("sfx_jinx_make_energy_ball", ASSET_CAST)
  SFX_JINX_RELEASE_ENERGY_BALL = util.findMember("sfx_jinx_release_energy_ball", ASSET_CAST)
end

on precache me
  preloadMember(FX_JINX_ENERGYBALL_01)
  preloadMember(FX_JINX_ENERGYBALL_02)
  preloadMember(FX_JINX_ENERGYBALL_03)
  preloadMember(FX_JINX_ENERGYBALL_04)
  preloadMember(FX_JINX_ENERGYBALL_05)
  preloadMember(FX_JINX_ENERGYBALL_06)
  preloadMember(FX_JINX_ENERGYBALL_07)
  preloadMember(FX_JINX_ENERGYBALL_08)
  preloadMember(FX_JINX_ENERGYBALL_09)
  preloadMember(FX_JINX_ENERGYBALL_10)
  preloadMember(FX_JINX_ENERGYBALL_11)
  preloadMember(FX_JINX_ENERGYBALL_12)
  preloadMember(FX_JINX_ENERGYBALL_12A)
  preloadMember(FX_JINX_ENERGYBALL_13)
  preloadMember(FX_JINX_ENERGYBALL_14)
  preloadMember(FX_JINX_ENERGYBALL_15)
  preloadMember(FX_JINX_ENERGYBALL_16)
  preloadMember(FX_JINX_ENERGYBALL_17)
  preloadMember(FX_JINX_ENERGYBALL_18)
  preloadMember(FX_JINX_ENERGYBALL_19)
  preloadMember(FX_JINX_ENERGYBALL_20)
  preloadMember(FX_JINX_ENERGYBALL_21)
  preloadMember(FX_JINX_ENERGYBALL_22)
  preloadMember(FX_JINX_ENERGYBALL_23)
  preloadMember(FX_JINX_ENERGYBALL_24)
  preloadMember(FX_JINX_ENERGYBALL_25)
  preloadMember(FX_JINX_ENERGYBALL_26)
  preloadMember(FX_JINX_ENERGYBALL_27)
  preloadMember(FX_JINX_ENERGYBALL_28)
  preloadMember(FX_JINX_ENERGYBALL_29)
  preloadMember(FX_JINX_ENERGYBALL_30)
  preloadMember(FX_JINX_ENERGYBALL_31)
  preloadMember(FX_JINX_ENERGYBALL_32)
  preloadMember(FX_JINX_ENERGYBALL_33)
  preloadMember(FX_JINX_ENERGYBALL_34)
  preloadMember(FX_JINX_ENERGYBALL_35)
  preloadMember(FX_JINX_TWIRL_06)
  preloadMember(FX_JINX_TWIRL_07)
  preloadMember(FX_JINX_TWIRL_08)
  preloadMember(FX_JINX_TWIRL_09)
  preloadMember(FX_JINX_TWIRL_10)
  preloadMember(FX_JINX_TWIRL_11)
  preloadMember(FX_JINX_TWIRL_12)
  preloadMember(FX_JINX_TWIRL_13)
  preloadMember(FX_JINX_TWIRL_14)
  preloadMember(FX_JINX_TWIRL_15)
  preloadMember(FX_JINX_TWIRL_16)
  preloadMember(FX_JINX_TWIRL_17)
  preloadMember(FX_JINX_TWIRL_18)
  preloadMember(FX_JINX_TWIRL_19)
  preloadMember(JINX_BACKGROUND)
  preloadMember(JINX_FALL_01)
  preloadMember(JINX_FALL_01D)
  preloadMember(JINX_FALL_02)
  preloadMember(JINX_FALL_02D)
  preloadMember(JINX_FALL_03)
  preloadMember(JINX_FALL_03D)
  preloadMember(JINX_HIT_01)
  preloadMember(JINX_HIT_01D)
  preloadMember(JINX_JUMP_01)
  preloadMember(JINX_JUMP_01D)
  preloadMember(JINX_JUMP_02)
  preloadMember(JINX_JUMP_02D)
  preloadMember(JINX_JUMP_03)
  preloadMember(JINX_JUMP_03D)
  preloadMember(JINX_JUMP_04)
  preloadMember(JINX_JUMP_04D)
  preloadMember(JINX_JUMP_05)
  preloadMember(JINX_JUMP_05D)
  preloadMember(JINX_JUMP_06)
  preloadMember(JINX_JUMP_06D)
  preloadMember(JINX_KICK_01)
  preloadMember(JINX_KICK_01D)
  preloadMember(JINX_KICK_02)
  preloadMember(JINX_KICK_02D)
  preloadMember(JINX_KICK_03)
  preloadMember(JINX_KICK_03D)
  preloadMember(JINX_KICK_04)
  preloadMember(JINX_KICK_04A)
  preloadMember(JINX_KICK_04D)
  preloadMember(JINX_KICK_05)
  preloadMember(JINX_KICK_05D)
  preloadMember(JINX_KICK_06)
  preloadMember(JINX_KICK_06D)
  preloadMember(JINX_KICK_07)
  preloadMember(JINX_KICK_07D)
  preloadMember(JINX_NEWFIST_01)
  preloadMember(JINX_NEWFIST_02)
  preloadMember(JINX_NEWFIST_03)
  preloadMember(JINX_NEWFIST_04)
  preloadMember(JINX_NEWFIST_05)
  preloadMember(JINX_NEWFIST_06)
  preloadMember(JINX_NEWFIST_07)
  preloadMember(JINX_NEWFIST_08)
  preloadMember(JINX_NEWFIST_09)
  preloadMember(JINX_NEWFIST_10)
  preloadMember(JINX_PUNCH_01)
  preloadMember(JINX_PUNCH_01D)
  preloadMember(JINX_PUNCH_02)
  preloadMember(JINX_PUNCH_02A)
  preloadMember(JINX_PUNCH_02D)
  preloadMember(JINX_PUNCH_03)
  preloadMember(JINX_PUNCH_03D)
  preloadMember(JINX_SPIN_01)
  preloadMember(JINX_SPIN_01D)
  preloadMember(JINX_SPIN_02)
  preloadMember(JINX_SPIN_02A)
  preloadMember(JINX_SPIN_02D)
  preloadMember(JINX_SPIN_03)
  preloadMember(JINX_SPIN_03A)
  preloadMember(JINX_SPIN_03D)
  preloadMember(JINX_SPIN_04)
  preloadMember(JINX_SPIN_04A)
  preloadMember(JINX_SPIN_04D)
  preloadMember(JINX_SPIN_05)
  preloadMember(JINX_SPIN_05A)
  preloadMember(JINX_SPIN_05D)
  preloadMember(JINX_STAND_01)
  preloadMember(JINX_STAND_01D)
  preloadMember(JINX_WALK_01)
  preloadMember(JINX_WALK_02)
  preloadMember(JINX_WALK_03)
  preloadMember(JINX_WALK_04)
  preloadMember(JINX_WALK_05)
  preloadMember(JINX_WALK_06)
  preloadMember(JINX_WALK_07)
  preloadMember(JINX_WALK_08)
  preloadMember(SFX_JINX_BG_CROWDNOISE3)
  preloadMember(SFX_JINX_ENERGY_BALL_HIT)
  preloadMember(SFX_JINX_ENERGY_BALL_MISS)
  preloadMember(SFX_JINX_ENERGY_SPIN)
  preloadMember(SFX_JINX_FLYING_KICK)
  preloadMember(SFX_JINX_MAKE_ENERGY_BALL)
  preloadMember(SFX_JINX_RELEASE_ENERGY_BALL)
end
