property CYBORG_CANNON_01, CYBORG_CANNON_01D, CYBORG_CANNON_02, CYBORG_CANNON_02D, CYBORG_CANNON_03, CYBORG_CANNON_03D, CYBORG_CANNON_ALT_01, CYBORG_CANNON_ALT_02, CYBORG_CANNON_ALT_03, CYBORG_CROUCH_01, CYBORG_CROUCH_01D, CYBORG_CROUCH_ALT_01, CYBORG_HIT_01, CYBORG_HIT_01D, CYBORG_HIT_02, CYBORG_HIT_02D, CYBORG_HIT_03, CYBORG_HIT_03D, CYBORG_HIT_ALT_01, CYBORG_HIT_ALT_02, CYBORG_HIT_ALT_03, CYBORG_JUMP_01, CYBORG_JUMP_01D, CYBORG_JUMP_02, CYBORG_JUMP_02D, CYBORG_JUMP_ALT_01, CYBORG_JUMP_ALT_02, CYBORG_JUMP_PUNCH_01D, CYBORG_JUMP_PUNCH_02A, CYBORG_JUMP_PUNCH_02D, CYBORG_KNEE_01, CYBORG_KNEE_01D, CYBORG_KNEE_02, CYBORG_KNEE_02A, CYBORG_KNEE_02D, CYBORG_KNEE_ALT_01, CYBORG_KNEE_ALT_02, CYBORG_PUNCH_01, CYBORG_PUNCH_01D, CYBORG_PUNCH_02, CYBORG_PUNCH_02A, CYBORG_PUNCH_02D, CYBORG_PUNCH_03, CYBORG_PUNCH_03D, CYBORG_PUNCH_04, CYBORG_PUNCH_04D, CYBORG_PUNCH_ALT_01, CYBORG_PUNCH_ALT_02, CYBORG_PUNCH_ALT_03, CYBORG_PUNCH_ALT_04, CYBORG_RUN_01, CYBORG_RUN_02, CYBORG_RUN_03, CYBORG_RUN_04, CYBORG_RUN_05, CYBORG_RUN_06, CYBORG_RUN_07, CYBORG_RUN_08, CYBORG_RUN_ALT_01, CYBORG_RUN_ALT_02, CYBORG_RUN_ALT_03, CYBORG_RUN_ALT_04, CYBORG_RUN_ALT_05, CYBORG_RUN_ALT_06, CYBORG_RUN_ALT_07, CYBORG_RUN_ALT_08, CYBORG_STAND_01, CYBORG_STAND_01D, CYBORG_STAND_ALT_01, FX_CYBORG_CANNON_BURST_01, FX_CYBORG_CANNON_BURST_02, FX_CYBORG_CANNON_BURST_03, FX_CYBORG_CANNON_BURST_04, FX_CYBORG_CANNON_BURST_05, FX_CYBORG_CANNON_BURST_06, FX_CYBORG_CANNON_BURST_07, FX_CYBORG_CANNON_CAP_01, FX_CYBORG_CANNON_CAP_02, FX_CYBORG_CANNON_STREAM_01, FX_CYBORG_CANNON_STREAM_01A, FX_CYBORG_CANNON_STREAM_02, FX_CYBORG_CANNON_STREAM_03, FX_CYBORG_CANNON_STREAM_04, FX_CYBORG_CANNON_STREAM_05, FX_CYBORG_CANNON_STREAM_06, FX_CYBORG_CANNON_STREAM_07, FX_CYBORG_EXPLODE_01, FX_CYBORG_EXPLODE_02, FX_CYBORG_EXPLODE_03, FX_CYBORG_EXPLODE_04, FX_CYBORG_EXPLODE_05, FX_CYBORG_EXPLODE_06, FX_CYBORG_EXPLODE_07, FX_CYBORG_EXPLODE_08, FX_CYBORG_EXPLODE_09, FX_CYBORG_EXPLODE_10, FX_CYBORG_EXPLODE_11, FX_CYBORG_EXPLODE_12, FX_CYBORG_EXPLODE_13, FX_CYBORG_EXPLODE_14, FX_CYBORG_EXPLODE_15, FX_CYBORG_EXPLODE_16, FX_CYBORG_EXPLODE_17, FX_CYBORG_EXPLODE_18, FX_CYBORG_EXPLODE_19, FX_CYBORG_EXPLODE_20, FX_CYBORG_EXPLODE_21, FX_CYBORG_EXPLODE_22, FX_CYBORG_FLARE_01, FX_CYBORG_FLARE_02, FX_CYBORG_POWERUP_01, FX_CYBORG_POWERUP_02, FX_CYBORG_POWERUP_03, FX_CYBORG_POWERUP_04, FX_CYBORG_POWERUP_05, FX_CYBORG_POWERUP_06, FX_CYBORG_POWERUP_07, FX_CYBORG_POWERUP_08, FX_CYBORG_POWERUP_09, FX_CYBORG_POWERUP_10, FX_CYBORG_POWERUP_11, FX_CYBORG_POWERUP_12, FX_CYBORG_POWERUP_13, FX_CYBORG_POWERUP_14, FX_CYBORG_POWERUP_15, FX_CYBORG_RING_01, FX_CYBORG_RING_02, FX_CYBORG_RING_03, FX_CYBORG_RING_04, FX_CYBORG_RING_05, FX_CYBORG_RING_06, SFX_CYBORG_CANNON_IN, SFX_CYBORG_CANNON_OUT, SFX_CYBORG_CANNONBLAST, SFX_CYBORG_CANNONBLASTSUSTAINED_LOOP, SFX_CYBORG_CANNONHIT, SFX_CYBORG_CANNONMISS, SFX_CYBORG_CYBERSTOMP_HIT, SFX_CYBORG_FLYINGPUNCH, SFX_CYBORG_FLYINGPUNCHMISS, SFX_CYBORG_FLYINGPUNCHWOOSH, SFX_CYBORG_POWERSMASH

on new me
  me.locateMembers()
  return me
end

on locateMembers me
  util = new(script("Class_Utility"))
  ASSET_CAST = "char_Cyborg"
  CYBORG_CANNON_01 = util.findMember("cyborg_cannon_01", ASSET_CAST)
  CYBORG_CANNON_01D = util.findMember("cyborg_cannon_01d", ASSET_CAST)
  CYBORG_CANNON_02 = util.findMember("cyborg_cannon_02", ASSET_CAST)
  CYBORG_CANNON_02D = util.findMember("cyborg_cannon_02d", ASSET_CAST)
  CYBORG_CANNON_03 = util.findMember("cyborg_cannon_03", ASSET_CAST)
  CYBORG_CANNON_03D = util.findMember("cyborg_cannon_03d", ASSET_CAST)
  CYBORG_CANNON_ALT_01 = util.findMember("cyborg_cannon_ALT_01", ASSET_CAST)
  CYBORG_CANNON_ALT_02 = util.findMember("cyborg_cannon_ALT_02", ASSET_CAST)
  CYBORG_CANNON_ALT_03 = util.findMember("cyborg_cannon_ALT_03", ASSET_CAST)
  CYBORG_CROUCH_01 = util.findMember("cyborg_crouch_01", ASSET_CAST)
  CYBORG_CROUCH_01D = util.findMember("cyborg_crouch_01d", ASSET_CAST)
  CYBORG_CROUCH_ALT_01 = util.findMember("cyborg_crouch_ALT_01", ASSET_CAST)
  CYBORG_HIT_01 = util.findMember("cyborg_hit_01", ASSET_CAST)
  CYBORG_HIT_01D = util.findMember("cyborg_hit_01d", ASSET_CAST)
  CYBORG_HIT_02 = util.findMember("cyborg_hit_02", ASSET_CAST)
  CYBORG_HIT_02D = util.findMember("cyborg_hit_02d", ASSET_CAST)
  CYBORG_HIT_03 = util.findMember("cyborg_hit_03", ASSET_CAST)
  CYBORG_HIT_03D = util.findMember("cyborg_hit_03d", ASSET_CAST)
  CYBORG_HIT_ALT_01 = util.findMember("cyborg_hit_ALT_01", ASSET_CAST)
  CYBORG_HIT_ALT_02 = util.findMember("cyborg_hit_ALT_02", ASSET_CAST)
  CYBORG_HIT_ALT_03 = util.findMember("cyborg_hit_ALT_03", ASSET_CAST)
  CYBORG_JUMP_01 = util.findMember("cyborg_jump_01", ASSET_CAST)
  CYBORG_JUMP_01D = util.findMember("cyborg_jump_01d", ASSET_CAST)
  CYBORG_JUMP_02 = util.findMember("cyborg_jump_02", ASSET_CAST)
  CYBORG_JUMP_02D = util.findMember("cyborg_jump_02d", ASSET_CAST)
  CYBORG_JUMP_ALT_01 = util.findMember("cyborg_jump_ALT_01", ASSET_CAST)
  CYBORG_JUMP_ALT_02 = util.findMember("cyborg_jump_ALT_02", ASSET_CAST)
  CYBORG_JUMP_PUNCH_01D = util.findMember("cyborg_jump_punch_01d", ASSET_CAST)
  CYBORG_JUMP_PUNCH_02A = util.findMember("cyborg_jump_punch_02a", ASSET_CAST)
  CYBORG_JUMP_PUNCH_02D = util.findMember("cyborg_jump_punch_02d", ASSET_CAST)
  CYBORG_KNEE_01 = util.findMember("cyborg_knee_01", ASSET_CAST)
  CYBORG_KNEE_01D = util.findMember("cyborg_knee_01d", ASSET_CAST)
  CYBORG_KNEE_02 = util.findMember("cyborg_knee_02", ASSET_CAST)
  CYBORG_KNEE_02A = util.findMember("cyborg_knee_02a", ASSET_CAST)
  CYBORG_KNEE_02D = util.findMember("cyborg_knee_02d", ASSET_CAST)
  CYBORG_KNEE_ALT_01 = util.findMember("cyborg_knee_ALT_01", ASSET_CAST)
  CYBORG_KNEE_ALT_02 = util.findMember("cyborg_knee_ALT_02", ASSET_CAST)
  CYBORG_PUNCH_01 = util.findMember("cyborg_punch_01", ASSET_CAST)
  CYBORG_PUNCH_01D = util.findMember("cyborg_punch_01d", ASSET_CAST)
  CYBORG_PUNCH_02 = util.findMember("cyborg_punch_02", ASSET_CAST)
  CYBORG_PUNCH_02A = util.findMember("cyborg_punch_02a", ASSET_CAST)
  CYBORG_PUNCH_02D = util.findMember("cyborg_punch_02d", ASSET_CAST)
  CYBORG_PUNCH_03 = util.findMember("cyborg_punch_03", ASSET_CAST)
  CYBORG_PUNCH_03D = util.findMember("cyborg_punch_03d", ASSET_CAST)
  CYBORG_PUNCH_04 = util.findMember("cyborg_punch_04", ASSET_CAST)
  CYBORG_PUNCH_04D = util.findMember("cyborg_punch_04d", ASSET_CAST)
  CYBORG_PUNCH_ALT_01 = util.findMember("cyborg_punch_ALT_01", ASSET_CAST)
  CYBORG_PUNCH_ALT_02 = util.findMember("cyborg_punch_ALT_02", ASSET_CAST)
  CYBORG_PUNCH_ALT_03 = util.findMember("cyborg_punch_ALT_03", ASSET_CAST)
  CYBORG_PUNCH_ALT_04 = util.findMember("cyborg_punch_ALT_04", ASSET_CAST)
  CYBORG_RUN_01 = util.findMember("cyborg_run_01", ASSET_CAST)
  CYBORG_RUN_02 = util.findMember("cyborg_run_02", ASSET_CAST)
  CYBORG_RUN_03 = util.findMember("cyborg_run_03", ASSET_CAST)
  CYBORG_RUN_04 = util.findMember("cyborg_run_04", ASSET_CAST)
  CYBORG_RUN_05 = util.findMember("cyborg_run_05", ASSET_CAST)
  CYBORG_RUN_06 = util.findMember("cyborg_run_06", ASSET_CAST)
  CYBORG_RUN_07 = util.findMember("cyborg_run_07", ASSET_CAST)
  CYBORG_RUN_08 = util.findMember("cyborg_run_08", ASSET_CAST)
  CYBORG_RUN_ALT_01 = util.findMember("cyborg_run_ALT_01", ASSET_CAST)
  CYBORG_RUN_ALT_02 = util.findMember("cyborg_run_ALT_02", ASSET_CAST)
  CYBORG_RUN_ALT_03 = util.findMember("cyborg_run_ALT_03", ASSET_CAST)
  CYBORG_RUN_ALT_04 = util.findMember("cyborg_run_ALT_04", ASSET_CAST)
  CYBORG_RUN_ALT_05 = util.findMember("cyborg_run_ALT_05", ASSET_CAST)
  CYBORG_RUN_ALT_06 = util.findMember("cyborg_run_ALT_06", ASSET_CAST)
  CYBORG_RUN_ALT_07 = util.findMember("cyborg_run_ALT_07", ASSET_CAST)
  CYBORG_RUN_ALT_08 = util.findMember("cyborg_run_ALT_08", ASSET_CAST)
  CYBORG_STAND_01 = util.findMember("cyborg_stand_01", ASSET_CAST)
  CYBORG_STAND_01D = util.findMember("cyborg_stand_01d", ASSET_CAST)
  CYBORG_STAND_ALT_01 = util.findMember("cyborg_stand_ALT_01", ASSET_CAST)
  FX_CYBORG_CANNON_BURST_01 = util.findMember("fx_cyborg_cannon_burst_01", ASSET_CAST)
  FX_CYBORG_CANNON_BURST_02 = util.findMember("fx_cyborg_cannon_burst_02", ASSET_CAST)
  FX_CYBORG_CANNON_BURST_03 = util.findMember("fx_cyborg_cannon_burst_03", ASSET_CAST)
  FX_CYBORG_CANNON_BURST_04 = util.findMember("fx_cyborg_cannon_burst_04", ASSET_CAST)
  FX_CYBORG_CANNON_BURST_05 = util.findMember("fx_cyborg_cannon_burst_05", ASSET_CAST)
  FX_CYBORG_CANNON_BURST_06 = util.findMember("fx_cyborg_cannon_burst_06", ASSET_CAST)
  FX_CYBORG_CANNON_BURST_07 = util.findMember("fx_cyborg_cannon_burst_07", ASSET_CAST)
  FX_CYBORG_CANNON_CAP_01 = util.findMember("fx_cyborg_cannon_cap_01", ASSET_CAST)
  FX_CYBORG_CANNON_CAP_02 = util.findMember("fx_cyborg_cannon_cap_02", ASSET_CAST)
  FX_CYBORG_CANNON_STREAM_01 = util.findMember("fx_cyborg_cannon_stream_01", ASSET_CAST)
  FX_CYBORG_CANNON_STREAM_01A = util.findMember("fx_cyborg_cannon_stream_01a", ASSET_CAST)
  FX_CYBORG_CANNON_STREAM_02 = util.findMember("fx_cyborg_cannon_stream_02", ASSET_CAST)
  FX_CYBORG_CANNON_STREAM_03 = util.findMember("fx_cyborg_cannon_stream_03", ASSET_CAST)
  FX_CYBORG_CANNON_STREAM_04 = util.findMember("fx_cyborg_cannon_stream_04", ASSET_CAST)
  FX_CYBORG_CANNON_STREAM_05 = util.findMember("fx_cyborg_cannon_stream_05", ASSET_CAST)
  FX_CYBORG_CANNON_STREAM_06 = util.findMember("fx_cyborg_cannon_stream_06", ASSET_CAST)
  FX_CYBORG_CANNON_STREAM_07 = util.findMember("fx_cyborg_cannon_stream_07", ASSET_CAST)
  FX_CYBORG_EXPLODE_01 = util.findMember("fx_cyborg_explode_01", ASSET_CAST)
  FX_CYBORG_EXPLODE_02 = util.findMember("fx_cyborg_explode_02", ASSET_CAST)
  FX_CYBORG_EXPLODE_03 = util.findMember("fx_cyborg_explode_03", ASSET_CAST)
  FX_CYBORG_EXPLODE_04 = util.findMember("fx_cyborg_explode_04", ASSET_CAST)
  FX_CYBORG_EXPLODE_05 = util.findMember("fx_cyborg_explode_05", ASSET_CAST)
  FX_CYBORG_EXPLODE_06 = util.findMember("fx_cyborg_explode_06", ASSET_CAST)
  FX_CYBORG_EXPLODE_07 = util.findMember("fx_cyborg_explode_07", ASSET_CAST)
  FX_CYBORG_EXPLODE_08 = util.findMember("fx_cyborg_explode_08", ASSET_CAST)
  FX_CYBORG_EXPLODE_09 = util.findMember("fx_cyborg_explode_09", ASSET_CAST)
  FX_CYBORG_EXPLODE_10 = util.findMember("fx_cyborg_explode_10", ASSET_CAST)
  FX_CYBORG_EXPLODE_11 = util.findMember("fx_cyborg_explode_11", ASSET_CAST)
  FX_CYBORG_EXPLODE_12 = util.findMember("fx_cyborg_explode_12", ASSET_CAST)
  FX_CYBORG_EXPLODE_13 = util.findMember("fx_cyborg_explode_13", ASSET_CAST)
  FX_CYBORG_EXPLODE_14 = util.findMember("fx_cyborg_explode_14", ASSET_CAST)
  FX_CYBORG_EXPLODE_15 = util.findMember("fx_cyborg_explode_15", ASSET_CAST)
  FX_CYBORG_EXPLODE_16 = util.findMember("fx_cyborg_explode_16", ASSET_CAST)
  FX_CYBORG_EXPLODE_17 = util.findMember("fx_cyborg_explode_17", ASSET_CAST)
  FX_CYBORG_EXPLODE_18 = util.findMember("fx_cyborg_explode_18", ASSET_CAST)
  FX_CYBORG_EXPLODE_19 = util.findMember("fx_cyborg_explode_19", ASSET_CAST)
  FX_CYBORG_EXPLODE_20 = util.findMember("fx_cyborg_explode_20", ASSET_CAST)
  FX_CYBORG_EXPLODE_21 = util.findMember("fx_cyborg_explode_21", ASSET_CAST)
  FX_CYBORG_EXPLODE_22 = util.findMember("fx_cyborg_explode_22", ASSET_CAST)
  FX_CYBORG_FLARE_01 = util.findMember("fx_cyborg_flare_01", ASSET_CAST)
  FX_CYBORG_FLARE_02 = util.findMember("fx_cyborg_flare_02", ASSET_CAST)
  FX_CYBORG_POWERUP_01 = util.findMember("fx_cyborg_powerup_01", ASSET_CAST)
  FX_CYBORG_POWERUP_02 = util.findMember("fx_cyborg_powerup_02", ASSET_CAST)
  FX_CYBORG_POWERUP_03 = util.findMember("fx_cyborg_powerup_03", ASSET_CAST)
  FX_CYBORG_POWERUP_04 = util.findMember("fx_cyborg_powerup_04", ASSET_CAST)
  FX_CYBORG_POWERUP_05 = util.findMember("fx_cyborg_powerup_05", ASSET_CAST)
  FX_CYBORG_POWERUP_06 = util.findMember("fx_cyborg_powerup_06", ASSET_CAST)
  FX_CYBORG_POWERUP_07 = util.findMember("fx_cyborg_powerup_07", ASSET_CAST)
  FX_CYBORG_POWERUP_08 = util.findMember("fx_cyborg_powerup_08", ASSET_CAST)
  FX_CYBORG_POWERUP_09 = util.findMember("fx_cyborg_powerup_09", ASSET_CAST)
  FX_CYBORG_POWERUP_10 = util.findMember("fx_cyborg_powerup_10", ASSET_CAST)
  FX_CYBORG_POWERUP_11 = util.findMember("fx_cyborg_powerup_11", ASSET_CAST)
  FX_CYBORG_POWERUP_12 = util.findMember("fx_cyborg_powerup_12", ASSET_CAST)
  FX_CYBORG_POWERUP_13 = util.findMember("fx_cyborg_powerup_13", ASSET_CAST)
  FX_CYBORG_POWERUP_14 = util.findMember("fx_cyborg_powerup_14", ASSET_CAST)
  FX_CYBORG_POWERUP_15 = util.findMember("fx_cyborg_powerup_15", ASSET_CAST)
  FX_CYBORG_RING_01 = util.findMember("fx_cyborg_ring_01", ASSET_CAST)
  FX_CYBORG_RING_02 = util.findMember("fx_cyborg_ring_02", ASSET_CAST)
  FX_CYBORG_RING_03 = util.findMember("fx_cyborg_ring_03", ASSET_CAST)
  FX_CYBORG_RING_04 = util.findMember("fx_cyborg_ring_04", ASSET_CAST)
  FX_CYBORG_RING_05 = util.findMember("fx_cyborg_ring_05", ASSET_CAST)
  FX_CYBORG_RING_06 = util.findMember("fx_cyborg_ring_06", ASSET_CAST)
  SFX_CYBORG_CANNON_IN = util.findMember("sfx_cyborg_cannon_in", ASSET_CAST)
  SFX_CYBORG_CANNON_OUT = util.findMember("sfx_cyborg_cannon_out", ASSET_CAST)
  SFX_CYBORG_CANNONBLAST = util.findMember("sfx_cyborg_cannonblast", ASSET_CAST)
  SFX_CYBORG_CANNONBLASTSUSTAINED_LOOP = util.findMember("sfx_cyborg_cannonblastsustained_loop", ASSET_CAST)
  SFX_CYBORG_CANNONHIT = util.findMember("sfx_cyborg_cannonhit", ASSET_CAST)
  SFX_CYBORG_CANNONMISS = util.findMember("sfx_cyborg_cannonmiss", ASSET_CAST)
  SFX_CYBORG_CYBERSTOMP_HIT = util.findMember("sfx_cyborg_cyberstomp_hit", ASSET_CAST)
  SFX_CYBORG_FLYINGPUNCH = util.findMember("sfx_cyborg_flyingpunch", ASSET_CAST)
  SFX_CYBORG_FLYINGPUNCHMISS = util.findMember("sfx_cyborg_flyingpunchmiss", ASSET_CAST)
  SFX_CYBORG_FLYINGPUNCHWOOSH = util.findMember("sfx_cyborg_flyingpunchwoosh", ASSET_CAST)
  SFX_CYBORG_POWERSMASH = util.findMember("sfx_cyborg_powersmash", ASSET_CAST)
end

on precache me
  preloadMember(CYBORG_CANNON_01)
  preloadMember(CYBORG_CANNON_01D)
  preloadMember(CYBORG_CANNON_02)
  preloadMember(CYBORG_CANNON_02D)
  preloadMember(CYBORG_CANNON_03)
  preloadMember(CYBORG_CANNON_03D)
  preloadMember(CYBORG_CANNON_ALT_01)
  preloadMember(CYBORG_CANNON_ALT_02)
  preloadMember(CYBORG_CANNON_ALT_03)
  preloadMember(CYBORG_CROUCH_01)
  preloadMember(CYBORG_CROUCH_01D)
  preloadMember(CYBORG_CROUCH_ALT_01)
  preloadMember(CYBORG_HIT_01)
  preloadMember(CYBORG_HIT_01D)
  preloadMember(CYBORG_HIT_02)
  preloadMember(CYBORG_HIT_02D)
  preloadMember(CYBORG_HIT_03)
  preloadMember(CYBORG_HIT_03D)
  preloadMember(CYBORG_HIT_ALT_01)
  preloadMember(CYBORG_HIT_ALT_02)
  preloadMember(CYBORG_HIT_ALT_03)
  preloadMember(CYBORG_JUMP_01)
  preloadMember(CYBORG_JUMP_01D)
  preloadMember(CYBORG_JUMP_02)
  preloadMember(CYBORG_JUMP_02D)
  preloadMember(CYBORG_JUMP_ALT_01)
  preloadMember(CYBORG_JUMP_ALT_02)
  preloadMember(CYBORG_JUMP_PUNCH_01D)
  preloadMember(CYBORG_JUMP_PUNCH_02A)
  preloadMember(CYBORG_JUMP_PUNCH_02D)
  preloadMember(CYBORG_KNEE_01)
  preloadMember(CYBORG_KNEE_01D)
  preloadMember(CYBORG_KNEE_02)
  preloadMember(CYBORG_KNEE_02A)
  preloadMember(CYBORG_KNEE_02D)
  preloadMember(CYBORG_KNEE_ALT_01)
  preloadMember(CYBORG_KNEE_ALT_02)
  preloadMember(CYBORG_PUNCH_01)
  preloadMember(CYBORG_PUNCH_01D)
  preloadMember(CYBORG_PUNCH_02)
  preloadMember(CYBORG_PUNCH_02A)
  preloadMember(CYBORG_PUNCH_02D)
  preloadMember(CYBORG_PUNCH_03)
  preloadMember(CYBORG_PUNCH_03D)
  preloadMember(CYBORG_PUNCH_04)
  preloadMember(CYBORG_PUNCH_04D)
  preloadMember(CYBORG_PUNCH_ALT_01)
  preloadMember(CYBORG_PUNCH_ALT_02)
  preloadMember(CYBORG_PUNCH_ALT_03)
  preloadMember(CYBORG_PUNCH_ALT_04)
  preloadMember(CYBORG_RUN_01)
  preloadMember(CYBORG_RUN_02)
  preloadMember(CYBORG_RUN_03)
  preloadMember(CYBORG_RUN_04)
  preloadMember(CYBORG_RUN_05)
  preloadMember(CYBORG_RUN_06)
  preloadMember(CYBORG_RUN_07)
  preloadMember(CYBORG_RUN_08)
  preloadMember(CYBORG_RUN_ALT_01)
  preloadMember(CYBORG_RUN_ALT_02)
  preloadMember(CYBORG_RUN_ALT_03)
  preloadMember(CYBORG_RUN_ALT_04)
  preloadMember(CYBORG_RUN_ALT_05)
  preloadMember(CYBORG_RUN_ALT_06)
  preloadMember(CYBORG_RUN_ALT_07)
  preloadMember(CYBORG_RUN_ALT_08)
  preloadMember(CYBORG_STAND_01)
  preloadMember(CYBORG_STAND_01D)
  preloadMember(CYBORG_STAND_ALT_01)
  preloadMember(FX_CYBORG_CANNON_BURST_01)
  preloadMember(FX_CYBORG_CANNON_BURST_02)
  preloadMember(FX_CYBORG_CANNON_BURST_03)
  preloadMember(FX_CYBORG_CANNON_BURST_04)
  preloadMember(FX_CYBORG_CANNON_BURST_05)
  preloadMember(FX_CYBORG_CANNON_BURST_06)
  preloadMember(FX_CYBORG_CANNON_BURST_07)
  preloadMember(FX_CYBORG_CANNON_CAP_01)
  preloadMember(FX_CYBORG_CANNON_CAP_02)
  preloadMember(FX_CYBORG_CANNON_STREAM_01)
  preloadMember(FX_CYBORG_CANNON_STREAM_01A)
  preloadMember(FX_CYBORG_CANNON_STREAM_02)
  preloadMember(FX_CYBORG_CANNON_STREAM_03)
  preloadMember(FX_CYBORG_CANNON_STREAM_04)
  preloadMember(FX_CYBORG_CANNON_STREAM_05)
  preloadMember(FX_CYBORG_CANNON_STREAM_06)
  preloadMember(FX_CYBORG_CANNON_STREAM_07)
  preloadMember(FX_CYBORG_EXPLODE_01)
  preloadMember(FX_CYBORG_EXPLODE_02)
  preloadMember(FX_CYBORG_EXPLODE_03)
  preloadMember(FX_CYBORG_EXPLODE_04)
  preloadMember(FX_CYBORG_EXPLODE_05)
  preloadMember(FX_CYBORG_EXPLODE_06)
  preloadMember(FX_CYBORG_EXPLODE_07)
  preloadMember(FX_CYBORG_EXPLODE_08)
  preloadMember(FX_CYBORG_EXPLODE_09)
  preloadMember(FX_CYBORG_EXPLODE_10)
  preloadMember(FX_CYBORG_EXPLODE_11)
  preloadMember(FX_CYBORG_EXPLODE_12)
  preloadMember(FX_CYBORG_EXPLODE_13)
  preloadMember(FX_CYBORG_EXPLODE_14)
  preloadMember(FX_CYBORG_EXPLODE_15)
  preloadMember(FX_CYBORG_EXPLODE_16)
  preloadMember(FX_CYBORG_EXPLODE_17)
  preloadMember(FX_CYBORG_EXPLODE_18)
  preloadMember(FX_CYBORG_EXPLODE_19)
  preloadMember(FX_CYBORG_EXPLODE_20)
  preloadMember(FX_CYBORG_EXPLODE_21)
  preloadMember(FX_CYBORG_EXPLODE_22)
  preloadMember(FX_CYBORG_FLARE_01)
  preloadMember(FX_CYBORG_FLARE_02)
  preloadMember(FX_CYBORG_POWERUP_01)
  preloadMember(FX_CYBORG_POWERUP_02)
  preloadMember(FX_CYBORG_POWERUP_03)
  preloadMember(FX_CYBORG_POWERUP_04)
  preloadMember(FX_CYBORG_POWERUP_05)
  preloadMember(FX_CYBORG_POWERUP_06)
  preloadMember(FX_CYBORG_POWERUP_07)
  preloadMember(FX_CYBORG_POWERUP_08)
  preloadMember(FX_CYBORG_POWERUP_09)
  preloadMember(FX_CYBORG_POWERUP_10)
  preloadMember(FX_CYBORG_POWERUP_11)
  preloadMember(FX_CYBORG_POWERUP_12)
  preloadMember(FX_CYBORG_POWERUP_13)
  preloadMember(FX_CYBORG_POWERUP_14)
  preloadMember(FX_CYBORG_POWERUP_15)
  preloadMember(FX_CYBORG_RING_01)
  preloadMember(FX_CYBORG_RING_02)
  preloadMember(FX_CYBORG_RING_03)
  preloadMember(FX_CYBORG_RING_04)
  preloadMember(FX_CYBORG_RING_05)
  preloadMember(FX_CYBORG_RING_06)
  preloadMember(SFX_CYBORG_CANNON_IN)
  preloadMember(SFX_CYBORG_CANNON_OUT)
  preloadMember(SFX_CYBORG_CANNONBLAST)
  preloadMember(SFX_CYBORG_CANNONBLASTSUSTAINED_LOOP)
  preloadMember(SFX_CYBORG_CANNONHIT)
  preloadMember(SFX_CYBORG_CANNONMISS)
  preloadMember(SFX_CYBORG_CYBERSTOMP_HIT)
  preloadMember(SFX_CYBORG_FLYINGPUNCH)
  preloadMember(SFX_CYBORG_FLYINGPUNCHMISS)
  preloadMember(SFX_CYBORG_FLYINGPUNCHWOOSH)
  preloadMember(SFX_CYBORG_POWERSMASH)
end
