property FX_ROBIN_BOMB_11, FX_ROBIN_BOMB_12, FX_ROBIN_BOMB_13, FX_ROBIN_BOMB_14, FX_ROBIN_BOMB_15, FX_ROBIN_BOMB_EXPLODE_01, FX_ROBIN_BOMB_EXPLODE_02, FX_ROBIN_BOMB_EXPLODE_02A, FX_ROBIN_BOMB_EXPLODE_03, FX_ROBIN_BOMB_EXPLODE_04, FX_ROBIN_BOMB_EXPLODE_05, FX_ROBIN_BOMB_EXPLODE_06, FX_ROBIN_BOMB_EXPLODE_07, FX_ROBIN_BOMB_EXPLODE_08, FX_ROBIN_BOMB_EXPLODE_09, FX_ROBIN_BOMB_EXPLODE_10, FX_ROBIN_BOMB_EXPLODE_11, FX_ROBIN_BOMB_EXPLODE_12, FX_ROBIN_COLUMN_01, FX_ROBIN_COLUMN_02, FX_ROBIN_COLUMN_03, FX_ROBIN_COLUMN_04, FX_ROBIN_COLUMN_05, FX_ROBIN_COLUMN_06, FX_ROBIN_DISC_EXPLODE_01, FX_ROBIN_DISC_EXPLODE_02, FX_ROBIN_DISC_EXPLODE_03, FX_ROBIN_DISC_EXPLODE_04, FX_ROBIN_DISC_EXPLODE_05, FX_ROBIN_DISC_EXPLODE_06, FX_ROBIN_DISC_EXPLODE_07, FX_ROBIN_DISC_EXPLODE_08, FX_ROBIN_DISC_EXPLODE_09, FX_ROBIN_DISC_EXPLODE_10, FX_ROBIN_DISC_EXPLODE_11, FX_ROBIN_DISC_EXPLODE_12, FX_ROBIN_DISC_EXPLODE_13, FX_ROBIN_DISC_EXPLODE_14, FX_ROBIN_DISC_EXPLODE_15, FX_ROBIN_DISC_EXPLODE_16, FX_ROBIN_DISC_EXPLODE_17, FX_ROBIN_DISC_EXPLODE_18, FX_ROBIN_DISC_EXPLODE_19, FX_ROBIN_DISC_EXPLODE_20, FX_ROBIN_DISC_EXPLODE_21, FX_ROBIN_DISC_EXPLODE_22, ROBIN_BOMB_01, ROBIN_BOMB_02, ROBIN_BOMBTHROW_03, ROBIN_BOMBTHROW_03D, ROBIN_BOMBTHROW_04, ROBIN_BOMBTHROW_05, ROBIN_BOMBTHROW_06, ROBIN_BOMBTHROW_07, ROBIN_DISC_01, ROBIN_DISC_02, ROBIN_DISC_03, ROBIN_DISC_04, ROBIN_DISC_04A, ROBIN_DISCTHROW_03, ROBIN_DISCTHROW_03D, ROBIN_DISCTHROW_04, ROBIN_DISCTHROW_05, ROBIN_DISCTHROW_06, ROBIN_DISCTHROW_07, ROBIN_FALL_01, ROBIN_FALL_01D, ROBIN_FALL_02, ROBIN_FALL_02D, ROBIN_FLYINGKICK_01D, ROBIN_FLYINGKICK_02A, ROBIN_FLYINGKICK_02D, ROBIN_HIT_01, ROBIN_HIT_01D, ROBIN_JUMP_01, ROBIN_JUMP_01D, ROBIN_JUMP_02, ROBIN_JUMP_02D, ROBIN_JUMP_03, ROBIN_JUMP_03D, ROBIN_JUMP_04, ROBIN_JUMP_04D, ROBIN_JUMP_05, ROBIN_JUMP_05D, ROBIN_KICK_01, ROBIN_KICK_01D, ROBIN_KICK_02, ROBIN_KICK_02D, ROBIN_KICK_03, ROBIN_KICK_03A, ROBIN_KICK_03D, ROBIN_KICK_04, ROBIN_KICK_04D, ROBIN_PUNCH_01, ROBIN_PUNCH_01A, ROBIN_PUNCH_01D, ROBIN_PUNCH_02, ROBIN_PUNCH_02D, ROBIN_PUNCH_03, ROBIN_PUNCH_03A, ROBIN_PUNCH_03D, ROBIN_PUNCH_04, ROBIN_PUNCH_04D, ROBIN_SOFTLANDING_01, ROBIN_SOFTLANDING_01D, ROBIN_STAND_01, ROBIN_STAND_01D, ROBIN_STANDUP_01, ROBIN_STANDUP_01D, ROBIN_THROW_01, ROBIN_THROW_01D, ROBIN_THROW_02, ROBIN_THROW_02D, ROBIN_THROW_08, ROBIN_THROW_09, ROBIN_WALK_01, ROBIN_WALK_02, ROBIN_WALK_03, ROBIN_WALK_04, ROBIN_WALK_05, ROBIN_WALK_06, SFX_ROBIN_BOMB_EXPLODE, SFX_ROBIN_BOMB_FLYING, SFX_ROBIN_DISK_BLOCKED, SFX_ROBIN_DISK_EXPLODE, SFX_ROBIN_DISK_FLYING

on new me
  me.locateMembers()
  return me
end

on locateMembers me
  util = new(script("Class_Utility"))
  ASSET_CAST = "char_Robin"
  FX_ROBIN_BOMB_11 = util.findMember("FX_robin_bomb_11", ASSET_CAST)
  FX_ROBIN_BOMB_12 = util.findMember("FX_robin_bomb_12", ASSET_CAST)
  FX_ROBIN_BOMB_13 = util.findMember("FX_robin_bomb_13", ASSET_CAST)
  FX_ROBIN_BOMB_14 = util.findMember("FX_robin_bomb_14", ASSET_CAST)
  FX_ROBIN_BOMB_15 = util.findMember("FX_robin_bomb_15", ASSET_CAST)
  FX_ROBIN_BOMB_EXPLODE_01 = util.findMember("FX_robin_bomb_explode_01", ASSET_CAST)
  FX_ROBIN_BOMB_EXPLODE_02 = util.findMember("FX_robin_bomb_explode_02", ASSET_CAST)
  FX_ROBIN_BOMB_EXPLODE_02A = util.findMember("FX_robin_bomb_explode_02a", ASSET_CAST)
  FX_ROBIN_BOMB_EXPLODE_03 = util.findMember("FX_robin_bomb_explode_03", ASSET_CAST)
  FX_ROBIN_BOMB_EXPLODE_04 = util.findMember("FX_robin_bomb_explode_04", ASSET_CAST)
  FX_ROBIN_BOMB_EXPLODE_05 = util.findMember("FX_robin_bomb_explode_05", ASSET_CAST)
  FX_ROBIN_BOMB_EXPLODE_06 = util.findMember("FX_robin_bomb_explode_06", ASSET_CAST)
  FX_ROBIN_BOMB_EXPLODE_07 = util.findMember("FX_robin_bomb_explode_07", ASSET_CAST)
  FX_ROBIN_BOMB_EXPLODE_08 = util.findMember("FX_robin_bomb_explode_08", ASSET_CAST)
  FX_ROBIN_BOMB_EXPLODE_09 = util.findMember("FX_robin_bomb_explode_09", ASSET_CAST)
  FX_ROBIN_BOMB_EXPLODE_10 = util.findMember("FX_robin_bomb_explode_10", ASSET_CAST)
  FX_ROBIN_BOMB_EXPLODE_11 = util.findMember("FX_robin_bomb_explode_11", ASSET_CAST)
  FX_ROBIN_BOMB_EXPLODE_12 = util.findMember("FX_robin_bomb_explode_12", ASSET_CAST)
  FX_ROBIN_COLUMN_01 = util.findMember("FX_robin_column_01", ASSET_CAST)
  FX_ROBIN_COLUMN_02 = util.findMember("FX_robin_column_02", ASSET_CAST)
  FX_ROBIN_COLUMN_03 = util.findMember("FX_robin_column_03", ASSET_CAST)
  FX_ROBIN_COLUMN_04 = util.findMember("FX_robin_column_04", ASSET_CAST)
  FX_ROBIN_COLUMN_05 = util.findMember("FX_robin_column_05", ASSET_CAST)
  FX_ROBIN_COLUMN_06 = util.findMember("FX_robin_column_06", ASSET_CAST)
  FX_ROBIN_DISC_EXPLODE_01 = util.findMember("FX_robin_disc_explode_01", ASSET_CAST)
  FX_ROBIN_DISC_EXPLODE_02 = util.findMember("FX_robin_disc_explode_02", ASSET_CAST)
  FX_ROBIN_DISC_EXPLODE_03 = util.findMember("FX_robin_disc_explode_03", ASSET_CAST)
  FX_ROBIN_DISC_EXPLODE_04 = util.findMember("FX_robin_disc_explode_04", ASSET_CAST)
  FX_ROBIN_DISC_EXPLODE_05 = util.findMember("FX_robin_disc_explode_05", ASSET_CAST)
  FX_ROBIN_DISC_EXPLODE_06 = util.findMember("FX_robin_disc_explode_06", ASSET_CAST)
  FX_ROBIN_DISC_EXPLODE_07 = util.findMember("FX_robin_disc_explode_07", ASSET_CAST)
  FX_ROBIN_DISC_EXPLODE_08 = util.findMember("FX_robin_disc_explode_08", ASSET_CAST)
  FX_ROBIN_DISC_EXPLODE_09 = util.findMember("FX_robin_disc_explode_09", ASSET_CAST)
  FX_ROBIN_DISC_EXPLODE_10 = util.findMember("FX_robin_disc_explode_10", ASSET_CAST)
  FX_ROBIN_DISC_EXPLODE_11 = util.findMember("FX_robin_disc_explode_11", ASSET_CAST)
  FX_ROBIN_DISC_EXPLODE_12 = util.findMember("FX_robin_disc_explode_12", ASSET_CAST)
  FX_ROBIN_DISC_EXPLODE_13 = util.findMember("FX_robin_disc_explode_13", ASSET_CAST)
  FX_ROBIN_DISC_EXPLODE_14 = util.findMember("FX_robin_disc_explode_14", ASSET_CAST)
  FX_ROBIN_DISC_EXPLODE_15 = util.findMember("FX_robin_disc_explode_15", ASSET_CAST)
  FX_ROBIN_DISC_EXPLODE_16 = util.findMember("FX_robin_disc_explode_16", ASSET_CAST)
  FX_ROBIN_DISC_EXPLODE_17 = util.findMember("FX_robin_disc_explode_17", ASSET_CAST)
  FX_ROBIN_DISC_EXPLODE_18 = util.findMember("FX_robin_disc_explode_18", ASSET_CAST)
  FX_ROBIN_DISC_EXPLODE_19 = util.findMember("FX_robin_disc_explode_19", ASSET_CAST)
  FX_ROBIN_DISC_EXPLODE_20 = util.findMember("FX_robin_disc_explode_20", ASSET_CAST)
  FX_ROBIN_DISC_EXPLODE_21 = util.findMember("FX_robin_disc_explode_21", ASSET_CAST)
  FX_ROBIN_DISC_EXPLODE_22 = util.findMember("FX_robin_disc_explode_22", ASSET_CAST)
  ROBIN_BOMB_01 = util.findMember("robin_bomb_01", ASSET_CAST)
  ROBIN_BOMB_02 = util.findMember("robin_bomb_02", ASSET_CAST)
  ROBIN_BOMBTHROW_03 = util.findMember("robin_bombthrow_03", ASSET_CAST)
  ROBIN_BOMBTHROW_03D = util.findMember("robin_bombthrow_03d", ASSET_CAST)
  ROBIN_BOMBTHROW_04 = util.findMember("robin_bombthrow_04", ASSET_CAST)
  ROBIN_BOMBTHROW_05 = util.findMember("robin_bombthrow_05", ASSET_CAST)
  ROBIN_BOMBTHROW_06 = util.findMember("robin_bombthrow_06", ASSET_CAST)
  ROBIN_BOMBTHROW_07 = util.findMember("robin_bombthrow_07", ASSET_CAST)
  ROBIN_DISC_01 = util.findMember("robin_disc_01", ASSET_CAST)
  ROBIN_DISC_02 = util.findMember("robin_disc_02", ASSET_CAST)
  ROBIN_DISC_03 = util.findMember("robin_disc_03", ASSET_CAST)
  ROBIN_DISC_04 = util.findMember("robin_disc_04", ASSET_CAST)
  ROBIN_DISC_04A = util.findMember("robin_disc_04a", ASSET_CAST)
  ROBIN_DISCTHROW_03 = util.findMember("robin_discthrow_03", ASSET_CAST)
  ROBIN_DISCTHROW_03D = util.findMember("robin_discthrow_03d", ASSET_CAST)
  ROBIN_DISCTHROW_04 = util.findMember("robin_discthrow_04", ASSET_CAST)
  ROBIN_DISCTHROW_05 = util.findMember("robin_discthrow_05", ASSET_CAST)
  ROBIN_DISCTHROW_06 = util.findMember("robin_discthrow_06", ASSET_CAST)
  ROBIN_DISCTHROW_07 = util.findMember("robin_discthrow_07", ASSET_CAST)
  ROBIN_FALL_01 = util.findMember("robin_fall_01", ASSET_CAST)
  ROBIN_FALL_01D = util.findMember("robin_fall_01d", ASSET_CAST)
  ROBIN_FALL_02 = util.findMember("robin_fall_02", ASSET_CAST)
  ROBIN_FALL_02D = util.findMember("robin_fall_02d", ASSET_CAST)
  ROBIN_FLYINGKICK_01D = util.findMember("robin_flyingkick_01d", ASSET_CAST)
  ROBIN_FLYINGKICK_02A = util.findMember("robin_flyingkick_02a", ASSET_CAST)
  ROBIN_FLYINGKICK_02D = util.findMember("robin_flyingkick_02d", ASSET_CAST)
  ROBIN_HIT_01 = util.findMember("robin_hit_01", ASSET_CAST)
  ROBIN_HIT_01D = util.findMember("robin_hit_01d", ASSET_CAST)
  ROBIN_JUMP_01 = util.findMember("robin_jump_01", ASSET_CAST)
  ROBIN_JUMP_01D = util.findMember("robin_jump_01d", ASSET_CAST)
  ROBIN_JUMP_02 = util.findMember("robin_jump_02", ASSET_CAST)
  ROBIN_JUMP_02D = util.findMember("robin_jump_02d", ASSET_CAST)
  ROBIN_JUMP_03 = util.findMember("robin_jump_03", ASSET_CAST)
  ROBIN_JUMP_03D = util.findMember("robin_jump_03d", ASSET_CAST)
  ROBIN_JUMP_04 = util.findMember("robin_jump_04", ASSET_CAST)
  ROBIN_JUMP_04D = util.findMember("robin_jump_04d", ASSET_CAST)
  ROBIN_JUMP_05 = util.findMember("robin_jump_05", ASSET_CAST)
  ROBIN_JUMP_05D = util.findMember("robin_jump_05d", ASSET_CAST)
  ROBIN_KICK_01 = util.findMember("robin_kick_01", ASSET_CAST)
  ROBIN_KICK_01D = util.findMember("robin_kick_01d", ASSET_CAST)
  ROBIN_KICK_02 = util.findMember("robin_kick_02", ASSET_CAST)
  ROBIN_KICK_02D = util.findMember("robin_kick_02d", ASSET_CAST)
  ROBIN_KICK_03 = util.findMember("robin_kick_03", ASSET_CAST)
  ROBIN_KICK_03A = util.findMember("robin_kick_03a", ASSET_CAST)
  ROBIN_KICK_03D = util.findMember("robin_kick_03d", ASSET_CAST)
  ROBIN_KICK_04 = util.findMember("robin_kick_04", ASSET_CAST)
  ROBIN_KICK_04D = util.findMember("robin_kick_04d", ASSET_CAST)
  ROBIN_PUNCH_01 = util.findMember("robin_punch_01", ASSET_CAST)
  ROBIN_PUNCH_01A = util.findMember("robin_punch_01a", ASSET_CAST)
  ROBIN_PUNCH_01D = util.findMember("robin_punch_01d", ASSET_CAST)
  ROBIN_PUNCH_02 = util.findMember("robin_punch_02", ASSET_CAST)
  ROBIN_PUNCH_02D = util.findMember("robin_punch_02d", ASSET_CAST)
  ROBIN_PUNCH_03 = util.findMember("robin_punch_03", ASSET_CAST)
  ROBIN_PUNCH_03A = util.findMember("robin_punch_03a", ASSET_CAST)
  ROBIN_PUNCH_03D = util.findMember("robin_punch_03d", ASSET_CAST)
  ROBIN_PUNCH_04 = util.findMember("robin_punch_04", ASSET_CAST)
  ROBIN_PUNCH_04D = util.findMember("robin_punch_04d", ASSET_CAST)
  ROBIN_SOFTLANDING_01 = util.findMember("robin_softlanding_01", ASSET_CAST)
  ROBIN_SOFTLANDING_01D = util.findMember("robin_softlanding_01d", ASSET_CAST)
  ROBIN_STAND_01 = util.findMember("robin_stand_01", ASSET_CAST)
  ROBIN_STAND_01D = util.findMember("robin_stand_01d", ASSET_CAST)
  ROBIN_STANDUP_01 = util.findMember("robin_standup_01", ASSET_CAST)
  ROBIN_STANDUP_01D = util.findMember("robin_standup_01d", ASSET_CAST)
  ROBIN_THROW_01 = util.findMember("robin_throw_01", ASSET_CAST)
  ROBIN_THROW_01D = util.findMember("robin_throw_01d", ASSET_CAST)
  ROBIN_THROW_02 = util.findMember("robin_throw_02", ASSET_CAST)
  ROBIN_THROW_02D = util.findMember("robin_throw_02d", ASSET_CAST)
  ROBIN_THROW_08 = util.findMember("robin_throw_08", ASSET_CAST)
  ROBIN_THROW_09 = util.findMember("robin_throw_09", ASSET_CAST)
  ROBIN_WALK_01 = util.findMember("robin_walk_01", ASSET_CAST)
  ROBIN_WALK_02 = util.findMember("robin_walk_02", ASSET_CAST)
  ROBIN_WALK_03 = util.findMember("robin_walk_03", ASSET_CAST)
  ROBIN_WALK_04 = util.findMember("robin_walk_04", ASSET_CAST)
  ROBIN_WALK_05 = util.findMember("robin_walk_05", ASSET_CAST)
  ROBIN_WALK_06 = util.findMember("robin_walk_06", ASSET_CAST)
  SFX_ROBIN_BOMB_EXPLODE = util.findMember("sfx_robin_bomb_explode", ASSET_CAST)
  SFX_ROBIN_BOMB_FLYING = util.findMember("sfx_robin_bomb_flying", ASSET_CAST)
  SFX_ROBIN_DISK_BLOCKED = util.findMember("sfx_robin_disk_blocked", ASSET_CAST)
  SFX_ROBIN_DISK_EXPLODE = util.findMember("sfx_robin_disk_explode", ASSET_CAST)
  SFX_ROBIN_DISK_FLYING = util.findMember("sfx_robin_disk_flying", ASSET_CAST)
end

on precache me
  preloadMember(FX_ROBIN_BOMB_11)
  preloadMember(FX_ROBIN_BOMB_12)
  preloadMember(FX_ROBIN_BOMB_13)
  preloadMember(FX_ROBIN_BOMB_14)
  preloadMember(FX_ROBIN_BOMB_15)
  preloadMember(FX_ROBIN_BOMB_EXPLODE_01)
  preloadMember(FX_ROBIN_BOMB_EXPLODE_02)
  preloadMember(FX_ROBIN_BOMB_EXPLODE_02A)
  preloadMember(FX_ROBIN_BOMB_EXPLODE_03)
  preloadMember(FX_ROBIN_BOMB_EXPLODE_04)
  preloadMember(FX_ROBIN_BOMB_EXPLODE_05)
  preloadMember(FX_ROBIN_BOMB_EXPLODE_06)
  preloadMember(FX_ROBIN_BOMB_EXPLODE_07)
  preloadMember(FX_ROBIN_BOMB_EXPLODE_08)
  preloadMember(FX_ROBIN_BOMB_EXPLODE_09)
  preloadMember(FX_ROBIN_BOMB_EXPLODE_10)
  preloadMember(FX_ROBIN_BOMB_EXPLODE_11)
  preloadMember(FX_ROBIN_BOMB_EXPLODE_12)
  preloadMember(FX_ROBIN_COLUMN_01)
  preloadMember(FX_ROBIN_COLUMN_02)
  preloadMember(FX_ROBIN_COLUMN_03)
  preloadMember(FX_ROBIN_COLUMN_04)
  preloadMember(FX_ROBIN_COLUMN_05)
  preloadMember(FX_ROBIN_COLUMN_06)
  preloadMember(FX_ROBIN_DISC_EXPLODE_01)
  preloadMember(FX_ROBIN_DISC_EXPLODE_02)
  preloadMember(FX_ROBIN_DISC_EXPLODE_03)
  preloadMember(FX_ROBIN_DISC_EXPLODE_04)
  preloadMember(FX_ROBIN_DISC_EXPLODE_05)
  preloadMember(FX_ROBIN_DISC_EXPLODE_06)
  preloadMember(FX_ROBIN_DISC_EXPLODE_07)
  preloadMember(FX_ROBIN_DISC_EXPLODE_08)
  preloadMember(FX_ROBIN_DISC_EXPLODE_09)
  preloadMember(FX_ROBIN_DISC_EXPLODE_10)
  preloadMember(FX_ROBIN_DISC_EXPLODE_11)
  preloadMember(FX_ROBIN_DISC_EXPLODE_12)
  preloadMember(FX_ROBIN_DISC_EXPLODE_13)
  preloadMember(FX_ROBIN_DISC_EXPLODE_14)
  preloadMember(FX_ROBIN_DISC_EXPLODE_15)
  preloadMember(FX_ROBIN_DISC_EXPLODE_16)
  preloadMember(FX_ROBIN_DISC_EXPLODE_17)
  preloadMember(FX_ROBIN_DISC_EXPLODE_18)
  preloadMember(FX_ROBIN_DISC_EXPLODE_19)
  preloadMember(FX_ROBIN_DISC_EXPLODE_20)
  preloadMember(FX_ROBIN_DISC_EXPLODE_21)
  preloadMember(FX_ROBIN_DISC_EXPLODE_22)
  preloadMember(ROBIN_BOMB_01)
  preloadMember(ROBIN_BOMB_02)
  preloadMember(ROBIN_BOMBTHROW_03)
  preloadMember(ROBIN_BOMBTHROW_03D)
  preloadMember(ROBIN_BOMBTHROW_04)
  preloadMember(ROBIN_BOMBTHROW_05)
  preloadMember(ROBIN_BOMBTHROW_06)
  preloadMember(ROBIN_BOMBTHROW_07)
  preloadMember(ROBIN_DISC_01)
  preloadMember(ROBIN_DISC_02)
  preloadMember(ROBIN_DISC_03)
  preloadMember(ROBIN_DISC_04)
  preloadMember(ROBIN_DISC_04A)
  preloadMember(ROBIN_DISCTHROW_03)
  preloadMember(ROBIN_DISCTHROW_03D)
  preloadMember(ROBIN_DISCTHROW_04)
  preloadMember(ROBIN_DISCTHROW_05)
  preloadMember(ROBIN_DISCTHROW_06)
  preloadMember(ROBIN_DISCTHROW_07)
  preloadMember(ROBIN_FALL_01)
  preloadMember(ROBIN_FALL_01D)
  preloadMember(ROBIN_FALL_02)
  preloadMember(ROBIN_FALL_02D)
  preloadMember(ROBIN_FLYINGKICK_01D)
  preloadMember(ROBIN_FLYINGKICK_02A)
  preloadMember(ROBIN_FLYINGKICK_02D)
  preloadMember(ROBIN_HIT_01)
  preloadMember(ROBIN_HIT_01D)
  preloadMember(ROBIN_JUMP_01)
  preloadMember(ROBIN_JUMP_01D)
  preloadMember(ROBIN_JUMP_02)
  preloadMember(ROBIN_JUMP_02D)
  preloadMember(ROBIN_JUMP_03)
  preloadMember(ROBIN_JUMP_03D)
  preloadMember(ROBIN_JUMP_04)
  preloadMember(ROBIN_JUMP_04D)
  preloadMember(ROBIN_JUMP_05)
  preloadMember(ROBIN_JUMP_05D)
  preloadMember(ROBIN_KICK_01)
  preloadMember(ROBIN_KICK_01D)
  preloadMember(ROBIN_KICK_02)
  preloadMember(ROBIN_KICK_02D)
  preloadMember(ROBIN_KICK_03)
  preloadMember(ROBIN_KICK_03A)
  preloadMember(ROBIN_KICK_03D)
  preloadMember(ROBIN_KICK_04)
  preloadMember(ROBIN_KICK_04D)
  preloadMember(ROBIN_PUNCH_01)
  preloadMember(ROBIN_PUNCH_01A)
  preloadMember(ROBIN_PUNCH_01D)
  preloadMember(ROBIN_PUNCH_02)
  preloadMember(ROBIN_PUNCH_02D)
  preloadMember(ROBIN_PUNCH_03)
  preloadMember(ROBIN_PUNCH_03A)
  preloadMember(ROBIN_PUNCH_03D)
  preloadMember(ROBIN_PUNCH_04)
  preloadMember(ROBIN_PUNCH_04D)
  preloadMember(ROBIN_SOFTLANDING_01)
  preloadMember(ROBIN_SOFTLANDING_01D)
  preloadMember(ROBIN_STAND_01)
  preloadMember(ROBIN_STAND_01D)
  preloadMember(ROBIN_STANDUP_01)
  preloadMember(ROBIN_STANDUP_01D)
  preloadMember(ROBIN_THROW_01)
  preloadMember(ROBIN_THROW_01D)
  preloadMember(ROBIN_THROW_02)
  preloadMember(ROBIN_THROW_02D)
  preloadMember(ROBIN_THROW_08)
  preloadMember(ROBIN_THROW_09)
  preloadMember(ROBIN_WALK_01)
  preloadMember(ROBIN_WALK_02)
  preloadMember(ROBIN_WALK_03)
  preloadMember(ROBIN_WALK_04)
  preloadMember(ROBIN_WALK_05)
  preloadMember(ROBIN_WALK_06)
  preloadMember(SFX_ROBIN_BOMB_EXPLODE)
  preloadMember(SFX_ROBIN_BOMB_FLYING)
  preloadMember(SFX_ROBIN_DISK_BLOCKED)
  preloadMember(SFX_ROBIN_DISK_EXPLODE)
  preloadMember(SFX_ROBIN_DISK_FLYING)
end
