property POWERS_OF_TEN, FRAME_RATE, FRAME_DURATION_MIN, SPRITE_POOL_CHANNEL_MIN, SPRITE_POOL_CHANNEL_MAX, SPRITE_LOCZ_BACKGROUND, SPRITE_LOCZ_BACKGROUND_EFFECT, SPRITE_LOCZ_SHADOWS, SPRITE_LOCZ_EFFECTS_BACKGROUND, SPRITE_LOCZ_VILLAIN_FIGHTER_BG, SPRITE_LOCZ_VILLAIN_FIGHTER, SPRITE_LOCZ_VILLAIN_FIGHTER_FG, SPRITE_LOCZ_TITAN_FIGHTER_BG, SPRITE_LOCZ_TITAN_FIGHTER, SPRITE_LOCZ_TITAN_FIGHTER_FG, SPRITE_LOCZ_PROJECTILES, SPRITE_LOCZ_EFFECTS_FOREGROUND, SPRITE_LOCZ_SCREEN_FLASH, SPRITE_LOCZ_HUD_BG, SPRITE_LOCZ_HUD_FG, SPRITE_LOCZ_GAME_FADE, SPRITE_LOCZ_GAME_TEXT, SPRITE_LOCZ_ALL_FADE, SPRITE_LOCZ_POPUP_CONTROLS_BG, SPRITE_LOCZ_POPUP_CONTROLS_OVERLAY, SPRITE_LOCZ_POPUP_CONTROLS_TEXTURE, SPRITE_LOCZ_POPUP_CONTROLS_BUTTONS, INK_COPY, INK_MATTE, INK_BGTRANSPARENT, INK_DARKEST, MEMBER_0, SFX_EVENT_PRIORITY_NONE, SFX_EVENT_PRIORITY_LOW, SFX_EVENT_PRIORITY_HIGH, SFX_EVENT_PRIORITY_UNINTERRUPTIBLE, KEYCODE_A, KEYCODE_S, KEYCODE_D, KEYCODE_F, KEYCODE_H, KEYCODE_G, KEYCODE_Z, KEYCODE_X, KEYCODE_C, KEYCODE_V, KEYCODE_B, KEYCODE_Q, KEYCODE_W, KEYCODE_E, KEYCODE_R, KEYCODE_Y, KEYCODE_T, KEYCODE_1, KEYCODE_2, KEYCODE_3, KEYCODE_4, KEYCODE_6, KEYCODE_5, KEYCODE_PLUS, KEYCODE_9, KEYCODE_7, KEYCODE_MINUS, KEYCODE_8, KEYCODE_ZERO, KEYCODE_RIGHTBRACKET, KEYCODE_O, KEYCODE_U, KEYCODE_LEFTBRACKET, KEYCODE_I, KEYCODE_P, KEYCODE_ENTER, KEYCODE_L, KEYCODE_J, KEYCODE_APOSTROPHE, KEYCODE_K, KEYCODE_SEMICOLON, KEYCODE_BACKSLASH, KEYCODE_COMMA, KEYCODE_SLASH, KEYCODE_N, KEYCODE_M, KEYCODE_PERIOD, KEYCODE_TAB, KEYCODE_SPACEBAR, KEYCODE_ESC, KEYCODE_LEFT_ARROW, KEYCODE_RIGHT_ARROW, KEYCODE_DOWN_ARROW, KEYCODE_UP_ARROW, SCREEN_TITLE, SCREEN_INTRO, SCREEN_SELECTFIGHTER, SCREEN_CONTROLS, SCREEN_VERSUS, SCREEN_GAME, SCREEN_WIN, PLAYMODE_AS_TITANS, PLAYMODE_AS_VILLAINS, FIGHTER_ID_ROBIN, FIGHTER_ID_RAVEN, FIGHTER_ID_CYBORG, FIGHTER_ID_STARFIRE, FIGHTER_ID_BEASTBOY, FIGHTER_ID_JINX, FIGHTER_ID_MAMMOTH, FIGHTER_ID_GIZMO, FIGHTER_ID_CINDERBLOCK, FIGHTER_ID_PLASMUS, FIGHTER_COUNT, CASTLIB_NAME_ROBIN, CASTLIB_NAME_RAVEN, CASTLIB_NAME_CYBORG, CASTLIB_NAME_STARFIRE, CASTLIB_NAME_BEASTBOY, CASTLIB_NAME_JINX, CASTLIB_NAME_MAMMOTH, CASTLIB_NAME_GIZMO, CASTLIB_NAME_CINDERBLOCK, CASTLIB_NAME_PLASMUS, CASTLIB_NAME_EFFECTS, CASTLIB_NAME_HUD, CASTLIB_NAMES, CASTLIB_NUM_ROBIN, CASTLIB_NUM_RAVEN, CASTLIB_NUM_CYBORG, CASTLIB_NUM_STARFIRE, CASTLIB_NUM_BEASTBOY, CASTLIB_NUM_JINX, CASTLIB_NUM_MAMMOTH, CASTLIB_NUM_GIZMO, CASTLIB_NUM_CINDERBLOCK, CASTLIB_NUM_PLASMUS, CASTLIB_NUM_EFFECTS, CASTLIB_NUM_HUD, CASTLIB_NUMS, DIFFICULTY_BEGINNER, DIFFICULTY_INTERMEDIATE, DIFFICULTY_EXPERT, MOVE_COUNT_MAX, MOVE_UNDEFINED, MOVE_STAND, MOVE_WALK_FORWARD, MOVE_WALK_BACKWARD, MOVE_BLOCK, MOVE_JUMP, MOVE_PUNCH, MOVE_KICK, MOVE_STUN, MOVE_KNOCK_DOWN, MOVE_DEFEAT, MOVE_FALL, MOVE_SUMMON_FIGHTER, MOVE_CINDERBLOCK_DOUBLE_PUNCH, MOVE_CINDERBLOCK_STOMP, MOVE_CINDERBLOCK_BACKHAND, MOVE_JINX_ENERGY_SPIN, MOVE_JINX_ENERGY_BALL, MOVE_JINX_POWER_KICK, MOVE_GIZMO_HOVER, MOVE_GIZMO_TAKE_OFF, MOVE_GIZMO_LAND, MOVE_GIZMO_FLY_FORWARD, MOVE_GIZMO_FLY_BACKWARD, MOVE_GIZMO_AIR_STUN, MOVE_GIZMO_AIR_KNOCK_DOWN, MOVE_GIZMO_AIR_DEFEAT, MOVE_GIZMO_CANNON, MOVE_GIZMO_AIR_CANNON, MOVE_GIZMO_AIR_MISSILE, MOVE_GIZMO_HIGH_AIR_MISSILE, MOVE_GIZMO_AIR_JUMP, MOVE_GIZMO_AIR_BLOCK, MOVE_GIZMO_AIR_PUNCH, MOVE_MAMMOTH_GROUND_PUNCH, MOVE_MAMMOTH_JUMP_PUNCH, MOVE_MAMMOTH_SHOULDER_BARGE, MOVE_PLASMUS_SLUDGE_THROW, MOVE_PLASMUS_CRAB_THROW, MOVE_PLASMUS_CHEST_BLAST, MOVE_PLASMUS_ARM_SWIPE, MOVE_ROBIN_FLYING_KICK, MOVE_ROBIN_DISC_THROW, MOVE_ROBIN_DIAG_JUMP_KICK, MOVE_ROBIN_BOMB_THROW, MOVE_RAVEN_TELEKINETIC_THROW, MOVE_RAVEN_EXPLOSIVE_DROP, MOVE_RAVEN_TELEKINETIC_SPIN, MOVE_RAVEN_MIDAIR_ATTACK, MOVE_CYBORG_SONIC_CANNON, MOVE_CYBORG_FLYING_PUNCH, MOVE_CYBORG_POWER_SMASH, MOVE_CYBORG_CYBER_STOMP, MOVE_STARFIRE_DIAG_JUMP_KICK, MOVE_STARFIRE_ENERGY_BALL, MOVE_STARFIRE_BOLT_BARRAGE, MOVE_STARFIRE_FLYING_KNEE, MOVE_BEASTBOY_GORILLA_SMASH, MOVE_BEASTBOY_EAGLE_STRIKE, MOVE_BEASTBOY_RHINO_CHARGE, MOVE_BEASTBOY_PTERODACTYL_SWOOP, MOVE_PRIORITIES, SUMMON_DAMAGE_PERCENT, DAMAGE_ROBIN_PUNCH, DAMAGE_ROBIN_KICK, DAMAGE_ROBIN_FLYING_KICK, DAMAGE_ROBIN_DIAG_JUMP_KICK, DAMAGE_ROBIN_DISC_THROW, DAMAGE_ROBIN_BOMB_THROW, DAMAGE_RAVEN_PUNCH, DAMAGE_RAVEN_KICK, DAMAGE_RAVEN_TELEKINETIC_THROW, DAMAGE_RAVEN_EXPLOSIVE_DROP, DAMAGE_RAVEN_TELEKINETIC_SPIN, DAMAGE_RAVEN_MIDAIR_ATTACK, DAMAGE_CYBORG_PUNCH, DAMAGE_CYBORG_KICK, DAMAGE_CYBORG_SONIC_CANNON, DAMAGE_CYBORG_FLYING_PUNCH, DAMAGE_CYBORG_POWER_SMASH, DAMAGE_CYBORG_CYBER_STOMP, DAMAGE_STARFIRE_PUNCH, DAMAGE_STARFIRE_KICK, DAMAGE_STARFIRE_ENERGY_BALL, DAMAGE_STARFIRE_BOLT_BARRAGE, DAMAGE_STARFIRE_FLYING_KNEE, DAMAGE_STARFIRE_DIAG_JUMP_KICK, DAMAGE_BEASTBOY_PUNCH, DAMAGE_BEASTBOY_KICK, DAMAGE_BEASTBOY_GORILLA_SMASH, DAMAGE_BEASTBOY_EAGLE_STRIKE, DAMAGE_BEASTBOY_RHINO_CHARGE, DAMAGE_BEASTBOY_PTERODACTYL_SWOOP, DAMAGE_JINX_PUNCH, DAMAGE_JINX_KICK, DAMAGE_JINX_ENERGY_SPIN, DAMAGE_JINX_ENERGY_BALL, DAMAGE_JINX_POWER_KICK, DAMAGE_MAMMOTH_PUNCH, DAMAGE_MAMMOTH_KICK, DAMAGE_MAMMOTH_GROUND_PUNCH, DAMAGE_MAMMOTH_JUMP_PUNCH, DAMAGE_MAMMOTH_SHOULDER_BARGE, DAMAGE_GIZMO_PUNCH, DAMAGE_GIZMO_CANNON, DAMAGE_GIZMO_AIR_MISSILE, DAMAGE_GIZMO_AIR_CANNON, DAMAGE_GIZMO_HIGH_AIR_MISSILE, DAMAGE_CINDERBLOCK_PUNCH, DAMAGE_CINDERBLOCK_DOUBLE_PUNCH, DAMAGE_CINDERBLOCK_KICK, DAMAGE_CINDERBLOCK_STOMP, DAMAGE_CINDERBLOCK_BACKHAND, DAMAGE_PLASMUS_PUNCH, DAMAGE_PLASMUS_SLUDGE_THROW, DAMAGE_PLASMUS_CRAB_THROW, DAMAGE_PLASMUS_SLUDGE_SPLAT, DAMAGE_PLASMUS_ARM_SWIPE, DAMAGE_KNOCK_DOWN_THRESHOLD, PLAYER_HEALTH_DEFAULT, TITAN_HEALTH_DEFAULTS, VILLAIN_HEALTH_DEFAULTS, TITAN_FIGHTER_ORDER, VILLAIN_FIGHTER_ORDER, RECT_0, gravity, KNOCK_DOWN_VELOCITY, KNOCK_OUT_VELOCITY, JUMP_VELOCITY, DEFENSE_BLOCK_DEFAULT, STUN_DURATION_DEFAULT, FIGHTER_HEALTH_MAX, ROUND_DURATION, classes, util, assets, audioMgr, defaultBoundingBox, rect0, frameTimestamp, frameCount, difficulty, victories, playMode, titanID, villainID, playerID, enemyID, main, screen, game, goFrame, fps, gameSpeed, availablePlayers, availableEnemies, unlockedPlayers, unlockedEnemies, defeatedEnemies, playerScores, linkedFighterCasts, linkedSharedCast

on new me
  classes = new(script("_ClassDefinitions"))
  util = new(classes.Class_Utility)
  POWERS_OF_TEN = [1, 10, 100, 1000, 10000, 100000, 1000000, 10000000, 100000000, 1000000000]
  FRAME_RATE = 30
  FRAME_DURATION_MIN = 1000 / FRAME_RATE
  SPRITE_POOL_CHANNEL_MIN = 11
  SPRITE_POOL_CHANNEL_MAX = 150
  SPRITE_LOCZ_BACKGROUND = 101
  SPRITE_LOCZ_BACKGROUND_EFFECT = 102
  SPRITE_LOCZ_SHADOWS = 103
  SPRITE_LOCZ_EFFECTS_BACKGROUND = 104
  SPRITE_LOCZ_VILLAIN_FIGHTER_BG = 105
  SPRITE_LOCZ_VILLAIN_FIGHTER = 106
  SPRITE_LOCZ_VILLAIN_FIGHTER_FG = 107
  SPRITE_LOCZ_TITAN_FIGHTER_BG = 108
  SPRITE_LOCZ_TITAN_FIGHTER = 109
  SPRITE_LOCZ_TITAN_FIGHTER_FG = 110
  SPRITE_LOCZ_PROJECTILES = 111
  SPRITE_LOCZ_EFFECTS_FOREGROUND = 112
  SPRITE_LOCZ_SCREEN_FLASH = 113
  SPRITE_LOCZ_HUD_BG = 114
  SPRITE_LOCZ_HUD_FG = 115
  SPRITE_LOCZ_GAME_FADE = 116
  SPRITE_LOCZ_GAME_TEXT = 117
  SPRITE_LOCZ_ALL_FADE = 118
  SPRITE_LOCZ_POPUP_CONTROLS_BG = 119
  SPRITE_LOCZ_POPUP_CONTROLS_TEXTURE = 120
  SPRITE_LOCZ_POPUP_CONTROLS_OVERLAY = 121
  SPRITE_LOCZ_POPUP_CONTROLS_BUTTONS = 122
  INK_COPY = 0
  INK_MATTE = 8
  INK_BGTRANSPARENT = 36
  INK_DARKEST = 39
  MEMBER_0 = member(0)
  SFX_EVENT_PRIORITY_NONE = 0
  SFX_EVENT_PRIORITY_LOW = 1
  SFX_EVENT_PRIORITY_HIGH = 2
  SFX_EVENT_PRIORITY_UNINTERRUPTIBLE = 3
  KEYCODE_A = 0
  KEYCODE_S = 1
  KEYCODE_D = 2
  KEYCODE_F = 3
  KEYCODE_H = 4
  KEYCODE_G = 5
  KEYCODE_Z = 6
  KEYCODE_X = 7
  KEYCODE_C = 8
  KEYCODE_V = 9
  KEYCODE_B = 11
  KEYCODE_Q = 12
  KEYCODE_W = 13
  KEYCODE_E = 14
  KEYCODE_R = 15
  KEYCODE_Y = 16
  KEYCODE_T = 17
  KEYCODE_1 = 18
  KEYCODE_2 = 19
  KEYCODE_3 = 20
  KEYCODE_4 = 21
  KEYCODE_6 = 22
  KEYCODE_5 = 23
  KEYCODE_PLUS = 24
  KEYCODE_9 = 25
  KEYCODE_7 = 26
  KEYCODE_MINUS = 27
  KEYCODE_8 = 28
  KEYCODE_ZERO = 29
  KEYCODE_RIGHTBRACKET = 30
  KEYCODE_O = 31
  KEYCODE_U = 32
  KEYCODE_LEFTBRACKET = 32
  KEYCODE_I = 34
  KEYCODE_P = 35
  KEYCODE_ENTER = 36
  KEYCODE_L = 37
  KEYCODE_J = 38
  KEYCODE_APOSTROPHE = 39
  KEYCODE_K = 40
  KEYCODE_SEMICOLON = 41
  KEYCODE_BACKSLASH = 42
  KEYCODE_COMMA = 43
  KEYCODE_SLASH = 44
  KEYCODE_N = 45
  KEYCODE_M = 46
  KEYCODE_PERIOD = 47
  KEYCODE_TAB = 48
  KEYCODE_SPACEBAR = 49
  KEYCODE_ESC = 53
  KEYCODE_LEFT_ARROW = 123
  KEYCODE_RIGHT_ARROW = 124
  KEYCODE_DOWN_ARROW = 125
  KEYCODE_UP_ARROW = 126
  SCREEN_TITLE = 1
  SCREEN_INTRO = 2
  SCREEN_SELECTFIGHTER = 3
  SCREEN_CONTROLS = 4
  SCREEN_VERSUS = 5
  SCREEN_GAME = 6
  SCREEN_WIN = 7
  PLAYMODE_AS_TITANS = 1
  PLAYMODE_AS_VILLAINS = 2
  FIGHTER_ID_ROBIN = 1
  FIGHTER_ID_RAVEN = 2
  FIGHTER_ID_CYBORG = 3
  FIGHTER_ID_STARFIRE = 4
  FIGHTER_ID_BEASTBOY = 5
  FIGHTER_ID_JINX = 6
  FIGHTER_ID_GIZMO = 7
  FIGHTER_ID_MAMMOTH = 8
  FIGHTER_ID_CINDERBLOCK = 9
  FIGHTER_ID_PLASMUS = 10
  FIGHTER_COUNT = 10
  CASTLIB_NAME_ROBIN = "char_Robin"
  CASTLIB_NAME_RAVEN = "char_Raven"
  CASTLIB_NAME_CYBORG = "char_Cyborg"
  CASTLIB_NAME_STARFIRE = "char_Starfire"
  CASTLIB_NAME_BEASTBOY = "char_Beastboy"
  CASTLIB_NAME_JINX = "char_Jinx"
  CASTLIB_NAME_MAMMOTH = "char_Mammoth"
  CASTLIB_NAME_GIZMO = "char_Gizmo"
  CASTLIB_NAME_CINDERBLOCK = "char_Cinderblock"
  CASTLIB_NAME_PLASMUS = "char_Plasmus"
  CASTLIB_NAME_EFFECTS = "effects"
  CASTLIB_NAME_HUD = "hud"
  CASTLIB_NAMES = []
  CASTLIB_NAMES[FIGHTER_ID_ROBIN] = CASTLIB_NAME_ROBIN
  CASTLIB_NAMES[FIGHTER_ID_RAVEN] = CASTLIB_NAME_RAVEN
  CASTLIB_NAMES[FIGHTER_ID_CYBORG] = CASTLIB_NAME_CYBORG
  CASTLIB_NAMES[FIGHTER_ID_STARFIRE] = CASTLIB_NAME_STARFIRE
  CASTLIB_NAMES[FIGHTER_ID_BEASTBOY] = CASTLIB_NAME_BEASTBOY
  CASTLIB_NAMES[FIGHTER_ID_JINX] = CASTLIB_NAME_JINX
  CASTLIB_NAMES[FIGHTER_ID_GIZMO] = CASTLIB_NAME_GIZMO
  CASTLIB_NAMES[FIGHTER_ID_MAMMOTH] = CASTLIB_NAME_MAMMOTH
  CASTLIB_NAMES[FIGHTER_ID_CINDERBLOCK] = CASTLIB_NAME_CINDERBLOCK
  CASTLIB_NAMES[FIGHTER_ID_PLASMUS] = CASTLIB_NAME_PLASMUS
  CASTLIB_NUM_ROBIN = castLib(CASTLIB_NAME_ROBIN).number
  CASTLIB_NUM_RAVEN = castLib(CASTLIB_NAME_RAVEN).number
  CASTLIB_NUM_CYBORG = castLib(CASTLIB_NAME_CYBORG).number
  CASTLIB_NUM_STARFIRE = castLib(CASTLIB_NAME_STARFIRE).number
  CASTLIB_NUM_BEASTBOY = castLib(CASTLIB_NAME_BEASTBOY).number
  CASTLIB_NUM_JINX = castLib(CASTLIB_NAME_JINX).number
  CASTLIB_NUM_MAMMOTH = castLib(CASTLIB_NAME_MAMMOTH).number
  CASTLIB_NUM_GIZMO = castLib(CASTLIB_NAME_GIZMO).number
  CASTLIB_NUM_CINDERBLOCK = castLib(CASTLIB_NAME_CINDERBLOCK).number
  CASTLIB_NUM_PLASMUS = castLib(CASTLIB_NAME_PLASMUS).number
  CASTLIB_NUM_EFFECTS = castLib(CASTLIB_NAME_EFFECTS).number
  CASTLIB_NUM_HUD = castLib(CASTLIB_NAME_HUD).number
  CASTLIB_NUMS = []
  CASTLIB_NUMS[FIGHTER_ID_ROBIN] = CASTLIB_NUM_ROBIN
  CASTLIB_NUMS[FIGHTER_ID_RAVEN] = CASTLIB_NUM_RAVEN
  CASTLIB_NUMS[FIGHTER_ID_CYBORG] = CASTLIB_NUM_CYBORG
  CASTLIB_NUMS[FIGHTER_ID_STARFIRE] = CASTLIB_NUM_STARFIRE
  CASTLIB_NUMS[FIGHTER_ID_BEASTBOY] = CASTLIB_NUM_BEASTBOY
  CASTLIB_NUMS[FIGHTER_ID_JINX] = CASTLIB_NUM_JINX
  CASTLIB_NUMS[FIGHTER_ID_GIZMO] = CASTLIB_NUM_GIZMO
  CASTLIB_NUMS[FIGHTER_ID_MAMMOTH] = CASTLIB_NUM_MAMMOTH
  CASTLIB_NUMS[FIGHTER_ID_CINDERBLOCK] = CASTLIB_NUM_CINDERBLOCK
  CASTLIB_NUMS[FIGHTER_ID_PLASMUS] = CASTLIB_NUM_PLASMUS
  DIFFICULTY_BEGINNER = 1
  DIFFICULTY_INTERMEDIATE = 2
  DIFFICULTY_EXPERT = 3
  MOVE_COUNT_MAX = 32
  MOVE_UNDEFINED = 0
  MOVE_STAND = 1
  MOVE_WALK_FORWARD = 2
  MOVE_WALK_BACKWARD = 3
  MOVE_BLOCK = 4
  MOVE_JUMP = 5
  MOVE_PUNCH = 6
  MOVE_KICK = 7
  MOVE_STUN = 8
  MOVE_KNOCK_DOWN = 9
  MOVE_DEFEAT = 10
  MOVE_FALL = 11
  MOVE_SUMMON_FIGHTER = 12
  MOVE_CINDERBLOCK_DOUBLE_PUNCH = 21
  MOVE_CINDERBLOCK_STOMP = 22
  MOVE_CINDERBLOCK_BACKHAND = 23
  MOVE_GIZMO_HOVER = 21
  MOVE_GIZMO_TAKE_OFF = 22
  MOVE_GIZMO_LAND = 23
  MOVE_GIZMO_FLY_FORWARD = 24
  MOVE_GIZMO_FLY_BACKWARD = 25
  MOVE_GIZMO_AIR_STUN = 26
  MOVE_GIZMO_CANNON = 27
  MOVE_GIZMO_AIR_CANNON = 28
  MOVE_GIZMO_AIR_MISSILE = 29
  MOVE_GIZMO_HIGH_AIR_MISSILE = 30
  MOVE_GIZMO_AIR_JUMP = 31
  MOVE_GIZMO_AIR_BLOCK = 32
  MOVE_GIZMO_AIR_PUNCH = 33
  MOVE_JINX_ENERGY_SPIN = 21
  MOVE_JINX_ENERGY_BALL = 22
  MOVE_JINX_POWER_KICK = 23
  MOVE_MAMMOTH_GROUND_PUNCH = 21
  MOVE_MAMMOTH_JUMP_PUNCH = 22
  MOVE_MAMMOTH_SHOULDER_BARGE = 23
  MOVE_ROBIN_FLYING_KICK = 21
  MOVE_ROBIN_DISC_THROW = 22
  MOVE_ROBIN_DIAG_JUMP_KICK = 23
  MOVE_ROBIN_BOMB_THROW = 24
  MOVE_RAVEN_TELEKINETIC_THROW = 21
  MOVE_RAVEN_EXPLOSIVE_DROP = 22
  MOVE_RAVEN_TELEKINETIC_SPIN = 23
  MOVE_RAVEN_MIDAIR_ATTACK = 24
  MOVE_CYBORG_SONIC_CANNON = 21
  MOVE_CYBORG_FLYING_PUNCH = 22
  MOVE_CYBORG_POWER_SMASH = 23
  MOVE_CYBORG_CYBER_STOMP = 24
  MOVE_STARFIRE_DIAG_JUMP_KICK = 21
  MOVE_STARFIRE_ENERGY_BALL = 22
  MOVE_STARFIRE_BOLT_BARRAGE = 23
  MOVE_STARFIRE_FLYING_KNEE = 24
  MOVE_BEASTBOY_GORILLA_SMASH = 21
  MOVE_BEASTBOY_EAGLE_STRIKE = 22
  MOVE_BEASTBOY_RHINO_CHARGE = 23
  MOVE_BEASTBOY_PTERODACTYL_SWOOP = 24
  MOVE_PLASMUS_SLUDGE_THROW = 21
  MOVE_PLASMUS_CRAB_THROW = 22
  MOVE_PLASMUS_CHEST_BLAST = 23
  MOVE_PLASMUS_ARM_SWIPE = 24
  MOVE_PRIORITIES = util.newArray(MOVE_COUNT_MAX, 1)
  MOVE_PRIORITIES[MOVE_STUN] = 2
  MOVE_PRIORITIES[MOVE_KNOCK_DOWN] = 3
  MOVE_PRIORITIES[MOVE_DEFEAT] = 4
  SUMMON_DAMAGE_PERCENT = 25
  DAMAGE_ROBIN_PUNCH = 50
  DAMAGE_ROBIN_KICK = 80
  DAMAGE_ROBIN_FLYING_KICK = 150
  DAMAGE_ROBIN_DIAG_JUMP_KICK = 100
  DAMAGE_ROBIN_DISC_THROW = 150
  DAMAGE_ROBIN_BOMB_THROW = 200
  DAMAGE_RAVEN_PUNCH = 50
  DAMAGE_RAVEN_KICK = 80
  DAMAGE_RAVEN_TELEKINETIC_THROW = 150
  DAMAGE_RAVEN_EXPLOSIVE_DROP = 200
  DAMAGE_RAVEN_TELEKINETIC_SPIN = 150
  DAMAGE_RAVEN_MIDAIR_ATTACK = 100
  DAMAGE_CYBORG_PUNCH = 50
  DAMAGE_CYBORG_KICK = 80
  DAMAGE_CYBORG_SONIC_CANNON = 150
  DAMAGE_CYBORG_FLYING_PUNCH = 100
  DAMAGE_CYBORG_POWER_SMASH = 150
  DAMAGE_CYBORG_CYBER_STOMP = 200
  DAMAGE_STARFIRE_PUNCH = 50
  DAMAGE_STARFIRE_KICK = 80
  DAMAGE_STARFIRE_ENERGY_BALL = 150
  DAMAGE_STARFIRE_BOLT_BARRAGE = 200
  DAMAGE_STARFIRE_FLYING_KNEE = 150
  DAMAGE_STARFIRE_DIAG_JUMP_KICK = 100
  DAMAGE_BEASTBOY_PUNCH = 50
  DAMAGE_BEASTBOY_KICK = 80
  DAMAGE_BEASTBOY_GORILLA_SMASH = 150
  DAMAGE_BEASTBOY_EAGLE_STRIKE = 100
  DAMAGE_BEASTBOY_RHINO_CHARGE = 150
  DAMAGE_BEASTBOY_PTERODACTYL_SWOOP = 200
  DAMAGE_JINX_PUNCH = 50
  DAMAGE_JINX_KICK = 80
  DAMAGE_JINX_ENERGY_SPIN = 125
  DAMAGE_JINX_ENERGY_BALL = 200
  DAMAGE_JINX_POWER_KICK = 150
  DAMAGE_MAMMOTH_PUNCH = 50
  DAMAGE_MAMMOTH_KICK = 80
  DAMAGE_MAMMOTH_GROUND_PUNCH = 150
  DAMAGE_MAMMOTH_JUMP_PUNCH = 200
  DAMAGE_MAMMOTH_SHOULDER_BARGE = 125
  DAMAGE_GIZMO_PUNCH = 80
  DAMAGE_GIZMO_CANNON = 150
  DAMAGE_GIZMO_AIR_MISSILE = 150
  DAMAGE_GIZMO_AIR_CANNON = 150
  DAMAGE_GIZMO_HIGH_AIR_MISSILE = 200
  DAMAGE_CINDERBLOCK_PUNCH = 50
  DAMAGE_CINDERBLOCK_DOUBLE_PUNCH = 100
  DAMAGE_CINDERBLOCK_KICK = 80
  DAMAGE_CINDERBLOCK_STOMP = 200
  DAMAGE_CINDERBLOCK_BACKHAND = 150
  DAMAGE_PLASMUS_PUNCH = 50
  DAMAGE_PLASMUS_SLUDGE_THROW = 150
  DAMAGE_PLASMUS_CRAB_THROW = 200
  DAMAGE_PLASMUS_SLUDGE_SPLAT = 150
  DAMAGE_PLASMUS_ARM_SWIPE = 100
  DAMAGE_KNOCK_DOWN_THRESHOLD = 100
  PLAYER_HEALTH_DEFAULT = 1000
  TITAN_HEALTH_DEFAULTS = []
  TITAN_HEALTH_DEFAULTS[DIFFICULTY_BEGINNER] = []
  TITAN_HEALTH_DEFAULTS[DIFFICULTY_INTERMEDIATE] = []
  TITAN_HEALTH_DEFAULTS[DIFFICULTY_EXPERT] = []
  TITAN_HEALTH_DEFAULTS[DIFFICULTY_BEGINNER][FIGHTER_ID_ROBIN] = 1000
  TITAN_HEALTH_DEFAULTS[DIFFICULTY_BEGINNER][FIGHTER_ID_RAVEN] = 1000
  TITAN_HEALTH_DEFAULTS[DIFFICULTY_BEGINNER][FIGHTER_ID_CYBORG] = 1000
  TITAN_HEALTH_DEFAULTS[DIFFICULTY_BEGINNER][FIGHTER_ID_STARFIRE] = 1500
  TITAN_HEALTH_DEFAULTS[DIFFICULTY_BEGINNER][FIGHTER_ID_BEASTBOY] = 1800
  TITAN_HEALTH_DEFAULTS[DIFFICULTY_INTERMEDIATE][FIGHTER_ID_ROBIN] = 1500
  TITAN_HEALTH_DEFAULTS[DIFFICULTY_INTERMEDIATE][FIGHTER_ID_RAVEN] = 1500
  TITAN_HEALTH_DEFAULTS[DIFFICULTY_INTERMEDIATE][FIGHTER_ID_CYBORG] = 1500
  TITAN_HEALTH_DEFAULTS[DIFFICULTY_INTERMEDIATE][FIGHTER_ID_STARFIRE] = 2000
  TITAN_HEALTH_DEFAULTS[DIFFICULTY_INTERMEDIATE][FIGHTER_ID_BEASTBOY] = 2500
  TITAN_HEALTH_DEFAULTS[DIFFICULTY_EXPERT][FIGHTER_ID_ROBIN] = 2000
  TITAN_HEALTH_DEFAULTS[DIFFICULTY_EXPERT][FIGHTER_ID_RAVEN] = 2000
  TITAN_HEALTH_DEFAULTS[DIFFICULTY_EXPERT][FIGHTER_ID_CYBORG] = 2000
  TITAN_HEALTH_DEFAULTS[DIFFICULTY_EXPERT][FIGHTER_ID_STARFIRE] = 2500
  TITAN_HEALTH_DEFAULTS[DIFFICULTY_EXPERT][FIGHTER_ID_BEASTBOY] = 3000
  VILLAIN_HEALTH_DEFAULTS = []
  VILLAIN_HEALTH_DEFAULTS[DIFFICULTY_BEGINNER] = []
  VILLAIN_HEALTH_DEFAULTS[DIFFICULTY_INTERMEDIATE] = []
  VILLAIN_HEALTH_DEFAULTS[DIFFICULTY_EXPERT] = []
  VILLAIN_HEALTH_DEFAULTS[DIFFICULTY_BEGINNER][FIGHTER_ID_JINX] = 1000
  VILLAIN_HEALTH_DEFAULTS[DIFFICULTY_BEGINNER][FIGHTER_ID_GIZMO] = 1000
  VILLAIN_HEALTH_DEFAULTS[DIFFICULTY_BEGINNER][FIGHTER_ID_MAMMOTH] = 1000
  VILLAIN_HEALTH_DEFAULTS[DIFFICULTY_BEGINNER][FIGHTER_ID_CINDERBLOCK] = 1500
  VILLAIN_HEALTH_DEFAULTS[DIFFICULTY_BEGINNER][FIGHTER_ID_PLASMUS] = 1800
  VILLAIN_HEALTH_DEFAULTS[DIFFICULTY_INTERMEDIATE][FIGHTER_ID_JINX] = 1500
  VILLAIN_HEALTH_DEFAULTS[DIFFICULTY_INTERMEDIATE][FIGHTER_ID_GIZMO] = 1500
  VILLAIN_HEALTH_DEFAULTS[DIFFICULTY_INTERMEDIATE][FIGHTER_ID_MAMMOTH] = 1500
  VILLAIN_HEALTH_DEFAULTS[DIFFICULTY_INTERMEDIATE][FIGHTER_ID_CINDERBLOCK] = 2000
  VILLAIN_HEALTH_DEFAULTS[DIFFICULTY_INTERMEDIATE][FIGHTER_ID_PLASMUS] = 2500
  VILLAIN_HEALTH_DEFAULTS[DIFFICULTY_EXPERT][FIGHTER_ID_JINX] = 2000
  VILLAIN_HEALTH_DEFAULTS[DIFFICULTY_EXPERT][FIGHTER_ID_GIZMO] = 2000
  VILLAIN_HEALTH_DEFAULTS[DIFFICULTY_EXPERT][FIGHTER_ID_MAMMOTH] = 2000
  VILLAIN_HEALTH_DEFAULTS[DIFFICULTY_EXPERT][FIGHTER_ID_CINDERBLOCK] = 2500
  VILLAIN_HEALTH_DEFAULTS[DIFFICULTY_EXPERT][FIGHTER_ID_PLASMUS] = 3000
  TITAN_FIGHTER_ORDER = [FIGHTER_ID_ROBIN, FIGHTER_ID_RAVEN, FIGHTER_ID_CYBORG, FIGHTER_ID_STARFIRE, FIGHTER_ID_BEASTBOY]
  VILLAIN_FIGHTER_ORDER = [FIGHTER_ID_JINX, FIGHTER_ID_GIZMO, FIGHTER_ID_MAMMOTH, FIGHTER_ID_CINDERBLOCK, FIGHTER_ID_PLASMUS]
  RECT_0 = rect(0, 0, 0, 0)
  gravity = point(0.0, 3.0)
  KNOCK_DOWN_VELOCITY = point(-6.0, -20.0)
  KNOCK_OUT_VELOCITY = point(-6.0, -30.0)
  JUMP_VELOCITY = point(15.0, -40.0)
  DEFENSE_BLOCK_DEFAULT = 70
  STUN_DURATION_DEFAULT = 4
  FIGHTER_HEALTH_MAX = 1000
  ROUND_DURATION = 90
  defaultBoundingBox = rect(0, 0, 50, 50)
  frameTimestamp = the milliSeconds - 1
  frameCount = 0
  difficulty = DIFFICULTY_BEGINNER
  playMode = PLAYMODE_AS_TITANS
  titanID = TITAN_FIGHTER_ORDER[1]
  villainID = VILLAIN_FIGHTER_ORDER[1]
  playerID = titanID
  enemyID = villainID
  goFrame = 0
  fps = 0.0
  gameSpeed = 1.0
  availablePlayers = []
  availableEnemies = []
  unlockedPlayers = []
  unlockedEnemies = []
  defeatedEnemies = []
  victories = []
  linkedFighterCasts = []
  playerScores = []
  repeat with i = 1 to FIGHTER_COUNT
    availablePlayers.append(1)
    availableEnemies.append(1)
    unlockedPlayers.append(1)
    victories.append(0)
    unlockedTmp = []
    defeatedTmp = []
    repeat with j = 1 to FIGHTER_COUNT
      unlockedTmp.append((j = TITAN_FIGHTER_ORDER[1]) or (j = VILLAIN_FIGHTER_ORDER[1]))
      defeatedTmp.append(0)
    end repeat
    unlockedEnemies.append(unlockedTmp)
    defeatedEnemies.append(defeatedTmp)
    linkedFighterCasts.append(0)
    scores = []
    repeat with j = 1 to FIGHTER_COUNT
      scores.append(0)
    end repeat
    playerScores.append(scores)
  end repeat
  linkedSharedCast = 0
  return me
end

on destroy me
  if objectp(main) then
    main = main.destroy()
  end if
  if objectp(util) then
    util = util.destroy()
  end if
  return VOID
end

on init me
  assets = [:]
  assets.addProp(#ROBIN, new(classes.Class_AssetsRobin))
  assets.addProp(#RAVEN, new(classes.Class_AssetsRaven))
  assets.addProp(#CYBORG, new(classes.Class_AssetsCyborg))
  assets.addProp(#STARFIRE, new(classes.Class_AssetsStarfire))
  assets.addProp(#BEASTBOY, new(classes.Class_AssetsBeastboy))
  assets.addProp(#JINX, new(classes.Class_AssetsJinx))
  assets.addProp(#MAMMOTH, new(classes.Class_AssetsMammoth))
  assets.addProp(#GIZMO, new(classes.Class_AssetsGizmo))
  assets.addProp(#CINDERBLOCK, new(classes.Class_AssetsCinderblock))
  assets.addProp(#PLASMUS, new(classes.Class_AssetsPlasmus))
  assets.addProp(#hud, new(classes.Class_AssetsHUD))
  assets.addProp(#GAME_MESSAGES, new(classes.Class_AssetsGameMessages))
  assets.addProp(#AUDIO, new(classes.Class_AssetsAudio))
  assets.addProp(#CHAR_SHARED, new(classes.Class_AssetsCharShared))
  assets.addProp(#FIGHTERS, [])
  assets.FIGHTERS[FIGHTER_ID_ROBIN] = assets.ROBIN
  assets.FIGHTERS[FIGHTER_ID_RAVEN] = assets.RAVEN
  assets.FIGHTERS[FIGHTER_ID_CYBORG] = assets.CYBORG
  assets.FIGHTERS[FIGHTER_ID_STARFIRE] = assets.STARFIRE
  assets.FIGHTERS[FIGHTER_ID_BEASTBOY] = assets.BEASTBOY
  assets.FIGHTERS[FIGHTER_ID_JINX] = assets.JINX
  assets.FIGHTERS[FIGHTER_ID_MAMMOTH] = assets.MAMMOTH
  assets.FIGHTERS[FIGHTER_ID_GIZMO] = assets.GIZMO
  assets.FIGHTERS[FIGHTER_ID_CINDERBLOCK] = assets.CINDERBLOCK
  assets.FIGHTERS[FIGHTER_ID_PLASMUS] = assets.PLASMUS
  main = new(classes.Class_Main)
end
