"""web/cards.js from original/cards.json (Club Penguin's card database): the basic, non-power cards
the Sensei game deals from, as [id, element, value, colour]. Power cards are left out for now."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
cards = json.loads((ROOT / 'original' / 'cards.json').read_text())
basic = [c for c in cards if c['power_id'] == '0' and c['is_active'] == '1' and (ROOT / 'assets' / 'icons' / c['card_id'] / 'movie.json').exists()]
rows = ',\n'.join(f"  [{int(c['card_id'])}, '{c['element']}', {int(c['value'])}, '{c['color']}', {json.dumps(c['name'].title())}]" for c in basic)
(ROOT / 'web' / 'cards.js').write_text(f"""// Generated by tools/gen_cards.py from original/cards.json — do not edit.
// [card id (= icon), element f/w/s, value, colour r/g/b/p/o/y, name]
export const CARDS = [
{rows},
];
""")
print(len(basic), 'cards')
